// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module receiver_receiver_Pipeline_VITIS_LOOP_111_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        filt_1_I_address0,
        filt_1_I_ce0,
        filt_1_I_q0,
        filt_1_I_address1,
        filt_1_I_ce1,
        filt_1_I_q1,
        filt_1_I_1_address0,
        filt_1_I_1_ce0,
        filt_1_I_1_q0,
        filt_1_I_1_address1,
        filt_1_I_1_ce1,
        filt_1_I_1_q1,
        filt_1_Q_address0,
        filt_1_Q_ce0,
        filt_1_Q_q0,
        filt_1_Q_address1,
        filt_1_Q_ce1,
        filt_1_Q_q1,
        filt_1_Q_1_address0,
        filt_1_Q_1_ce0,
        filt_1_Q_1_q0,
        filt_1_Q_1_address1,
        filt_1_Q_1_ce1,
        filt_1_Q_1_q1,
        filt_1_I_2_address0,
        filt_1_I_2_ce0,
        filt_1_I_2_q0,
        filt_1_I_2_address1,
        filt_1_I_2_ce1,
        filt_1_I_2_q1,
        filt_1_I_3_address0,
        filt_1_I_3_ce0,
        filt_1_I_3_q0,
        filt_1_I_3_address1,
        filt_1_I_3_ce1,
        filt_1_I_3_q1,
        filt_1_Q_2_address0,
        filt_1_Q_2_ce0,
        filt_1_Q_2_q0,
        filt_1_Q_2_address1,
        filt_1_Q_2_ce1,
        filt_1_Q_2_q1,
        filt_1_Q_3_address0,
        filt_1_Q_3_ce0,
        filt_1_Q_3_q0,
        filt_1_Q_3_address1,
        filt_1_Q_3_ce1,
        filt_1_Q_3_q1,
        filt_1_I_4_address0,
        filt_1_I_4_ce0,
        filt_1_I_4_q0,
        filt_1_I_4_address1,
        filt_1_I_4_ce1,
        filt_1_I_4_q1,
        filt_1_I_5_address0,
        filt_1_I_5_ce0,
        filt_1_I_5_q0,
        filt_1_I_5_address1,
        filt_1_I_5_ce1,
        filt_1_I_5_q1,
        filt_1_Q_4_address0,
        filt_1_Q_4_ce0,
        filt_1_Q_4_q0,
        filt_1_Q_4_address1,
        filt_1_Q_4_ce1,
        filt_1_Q_4_q1,
        filt_1_Q_5_address0,
        filt_1_Q_5_ce0,
        filt_1_Q_5_q0,
        filt_1_Q_5_address1,
        filt_1_Q_5_ce1,
        filt_1_Q_5_q1,
        filt_1_I_6_address0,
        filt_1_I_6_ce0,
        filt_1_I_6_q0,
        filt_1_I_6_address1,
        filt_1_I_6_ce1,
        filt_1_I_6_q1,
        filt_1_I_7_address0,
        filt_1_I_7_ce0,
        filt_1_I_7_q0,
        filt_1_I_7_address1,
        filt_1_I_7_ce1,
        filt_1_I_7_q1,
        filt_1_Q_6_address0,
        filt_1_Q_6_ce0,
        filt_1_Q_6_q0,
        filt_1_Q_6_address1,
        filt_1_Q_6_ce1,
        filt_1_Q_6_q1,
        filt_1_Q_7_address0,
        filt_1_Q_7_ce0,
        filt_1_Q_7_q0,
        filt_1_Q_7_address1,
        filt_1_Q_7_ce1,
        filt_1_Q_7_q1,
        filt_2_Q_2_7_052_out,
        filt_2_Q_2_7_052_out_ap_vld,
        filt_2_Q_1_7_051_out,
        filt_2_Q_1_7_051_out_ap_vld,
        filt_2_Q_0_7_050_out,
        filt_2_Q_0_7_050_out_ap_vld,
        filt_2_Q_2_6_049_out,
        filt_2_Q_2_6_049_out_ap_vld,
        filt_2_Q_1_6_048_out,
        filt_2_Q_1_6_048_out_ap_vld,
        filt_2_Q_0_6_047_out,
        filt_2_Q_0_6_047_out_ap_vld,
        filt_2_Q_2_5_046_out,
        filt_2_Q_2_5_046_out_ap_vld,
        filt_2_Q_1_5_045_out,
        filt_2_Q_1_5_045_out_ap_vld,
        filt_2_Q_0_5_044_out,
        filt_2_Q_0_5_044_out_ap_vld,
        filt_2_Q_2_4_043_out,
        filt_2_Q_2_4_043_out_ap_vld,
        filt_2_Q_1_4_042_out,
        filt_2_Q_1_4_042_out_ap_vld,
        filt_2_Q_0_4_041_out,
        filt_2_Q_0_4_041_out_ap_vld,
        filt_2_Q_2_3_040_out,
        filt_2_Q_2_3_040_out_ap_vld,
        filt_2_Q_1_3_039_out,
        filt_2_Q_1_3_039_out_ap_vld,
        filt_2_Q_0_3_038_out,
        filt_2_Q_0_3_038_out_ap_vld,
        filt_2_Q_2_2_037_out,
        filt_2_Q_2_2_037_out_ap_vld,
        filt_2_Q_1_2_036_out,
        filt_2_Q_1_2_036_out_ap_vld,
        filt_2_Q_0_2_035_out,
        filt_2_Q_0_2_035_out_ap_vld,
        filt_2_Q_2_1_034_out,
        filt_2_Q_2_1_034_out_ap_vld,
        filt_2_Q_1_1_033_out,
        filt_2_Q_1_1_033_out_ap_vld,
        filt_2_Q_0_1_032_out,
        filt_2_Q_0_1_032_out_ap_vld,
        filt_2_Q_2_030_out,
        filt_2_Q_2_030_out_ap_vld,
        filt_2_Q_1_028_out,
        filt_2_Q_1_028_out_ap_vld,
        filt_2_Q_0_0_out,
        filt_2_Q_0_0_out_ap_vld,
        filt_2_I_2_7_026_out,
        filt_2_I_2_7_026_out_ap_vld,
        filt_2_I_1_7_025_out,
        filt_2_I_1_7_025_out_ap_vld,
        filt_2_I_0_7_024_out,
        filt_2_I_0_7_024_out_ap_vld,
        filt_2_I_2_6_023_out,
        filt_2_I_2_6_023_out_ap_vld,
        filt_2_I_1_6_022_out,
        filt_2_I_1_6_022_out_ap_vld,
        filt_2_I_0_6_021_out,
        filt_2_I_0_6_021_out_ap_vld,
        filt_2_I_2_5_020_out,
        filt_2_I_2_5_020_out_ap_vld,
        filt_2_I_1_5_019_out,
        filt_2_I_1_5_019_out_ap_vld,
        filt_2_I_0_5_018_out,
        filt_2_I_0_5_018_out_ap_vld,
        filt_2_I_2_4_017_out,
        filt_2_I_2_4_017_out_ap_vld,
        filt_2_I_1_4_016_out,
        filt_2_I_1_4_016_out_ap_vld,
        filt_2_I_0_4_015_out,
        filt_2_I_0_4_015_out_ap_vld,
        filt_2_I_2_3_014_out,
        filt_2_I_2_3_014_out_ap_vld,
        filt_2_I_1_3_013_out,
        filt_2_I_1_3_013_out_ap_vld,
        filt_2_I_0_3_012_out,
        filt_2_I_0_3_012_out_ap_vld,
        filt_2_I_2_2_011_out,
        filt_2_I_2_2_011_out_ap_vld,
        filt_2_I_1_2_010_out,
        filt_2_I_1_2_010_out_ap_vld,
        filt_2_I_0_2_09_out,
        filt_2_I_0_2_09_out_ap_vld,
        filt_2_I_2_1_08_out,
        filt_2_I_2_1_08_out_ap_vld,
        filt_2_I_1_1_07_out,
        filt_2_I_1_1_07_out_ap_vld,
        filt_2_I_0_1_06_out,
        filt_2_I_0_1_06_out_ap_vld,
        filt_2_I_2_04_out,
        filt_2_I_2_04_out_ap_vld,
        filt_2_I_1_02_out,
        filt_2_I_1_02_out_ap_vld,
        filt_2_I_0_0_out,
        filt_2_I_0_0_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] filt_1_I_address0;
output   filt_1_I_ce0;
input  [17:0] filt_1_I_q0;
output  [2:0] filt_1_I_address1;
output   filt_1_I_ce1;
input  [17:0] filt_1_I_q1;
output  [2:0] filt_1_I_1_address0;
output   filt_1_I_1_ce0;
input  [17:0] filt_1_I_1_q0;
output  [2:0] filt_1_I_1_address1;
output   filt_1_I_1_ce1;
input  [17:0] filt_1_I_1_q1;
output  [2:0] filt_1_Q_address0;
output   filt_1_Q_ce0;
input  [17:0] filt_1_Q_q0;
output  [2:0] filt_1_Q_address1;
output   filt_1_Q_ce1;
input  [17:0] filt_1_Q_q1;
output  [2:0] filt_1_Q_1_address0;
output   filt_1_Q_1_ce0;
input  [17:0] filt_1_Q_1_q0;
output  [2:0] filt_1_Q_1_address1;
output   filt_1_Q_1_ce1;
input  [17:0] filt_1_Q_1_q1;
output  [2:0] filt_1_I_2_address0;
output   filt_1_I_2_ce0;
input  [17:0] filt_1_I_2_q0;
output  [2:0] filt_1_I_2_address1;
output   filt_1_I_2_ce1;
input  [17:0] filt_1_I_2_q1;
output  [2:0] filt_1_I_3_address0;
output   filt_1_I_3_ce0;
input  [17:0] filt_1_I_3_q0;
output  [2:0] filt_1_I_3_address1;
output   filt_1_I_3_ce1;
input  [17:0] filt_1_I_3_q1;
output  [2:0] filt_1_Q_2_address0;
output   filt_1_Q_2_ce0;
input  [17:0] filt_1_Q_2_q0;
output  [2:0] filt_1_Q_2_address1;
output   filt_1_Q_2_ce1;
input  [17:0] filt_1_Q_2_q1;
output  [2:0] filt_1_Q_3_address0;
output   filt_1_Q_3_ce0;
input  [17:0] filt_1_Q_3_q0;
output  [2:0] filt_1_Q_3_address1;
output   filt_1_Q_3_ce1;
input  [17:0] filt_1_Q_3_q1;
output  [2:0] filt_1_I_4_address0;
output   filt_1_I_4_ce0;
input  [17:0] filt_1_I_4_q0;
output  [2:0] filt_1_I_4_address1;
output   filt_1_I_4_ce1;
input  [17:0] filt_1_I_4_q1;
output  [2:0] filt_1_I_5_address0;
output   filt_1_I_5_ce0;
input  [17:0] filt_1_I_5_q0;
output  [2:0] filt_1_I_5_address1;
output   filt_1_I_5_ce1;
input  [17:0] filt_1_I_5_q1;
output  [2:0] filt_1_Q_4_address0;
output   filt_1_Q_4_ce0;
input  [17:0] filt_1_Q_4_q0;
output  [2:0] filt_1_Q_4_address1;
output   filt_1_Q_4_ce1;
input  [17:0] filt_1_Q_4_q1;
output  [2:0] filt_1_Q_5_address0;
output   filt_1_Q_5_ce0;
input  [17:0] filt_1_Q_5_q0;
output  [2:0] filt_1_Q_5_address1;
output   filt_1_Q_5_ce1;
input  [17:0] filt_1_Q_5_q1;
output  [2:0] filt_1_I_6_address0;
output   filt_1_I_6_ce0;
input  [17:0] filt_1_I_6_q0;
output  [2:0] filt_1_I_6_address1;
output   filt_1_I_6_ce1;
input  [17:0] filt_1_I_6_q1;
output  [2:0] filt_1_I_7_address0;
output   filt_1_I_7_ce0;
input  [17:0] filt_1_I_7_q0;
output  [2:0] filt_1_I_7_address1;
output   filt_1_I_7_ce1;
input  [17:0] filt_1_I_7_q1;
output  [2:0] filt_1_Q_6_address0;
output   filt_1_Q_6_ce0;
input  [17:0] filt_1_Q_6_q0;
output  [2:0] filt_1_Q_6_address1;
output   filt_1_Q_6_ce1;
input  [17:0] filt_1_Q_6_q1;
output  [2:0] filt_1_Q_7_address0;
output   filt_1_Q_7_ce0;
input  [17:0] filt_1_Q_7_q0;
output  [2:0] filt_1_Q_7_address1;
output   filt_1_Q_7_ce1;
input  [17:0] filt_1_Q_7_q1;
output  [17:0] filt_2_Q_2_7_052_out;
output   filt_2_Q_2_7_052_out_ap_vld;
output  [17:0] filt_2_Q_1_7_051_out;
output   filt_2_Q_1_7_051_out_ap_vld;
output  [17:0] filt_2_Q_0_7_050_out;
output   filt_2_Q_0_7_050_out_ap_vld;
output  [17:0] filt_2_Q_2_6_049_out;
output   filt_2_Q_2_6_049_out_ap_vld;
output  [17:0] filt_2_Q_1_6_048_out;
output   filt_2_Q_1_6_048_out_ap_vld;
output  [17:0] filt_2_Q_0_6_047_out;
output   filt_2_Q_0_6_047_out_ap_vld;
output  [17:0] filt_2_Q_2_5_046_out;
output   filt_2_Q_2_5_046_out_ap_vld;
output  [17:0] filt_2_Q_1_5_045_out;
output   filt_2_Q_1_5_045_out_ap_vld;
output  [17:0] filt_2_Q_0_5_044_out;
output   filt_2_Q_0_5_044_out_ap_vld;
output  [17:0] filt_2_Q_2_4_043_out;
output   filt_2_Q_2_4_043_out_ap_vld;
output  [17:0] filt_2_Q_1_4_042_out;
output   filt_2_Q_1_4_042_out_ap_vld;
output  [17:0] filt_2_Q_0_4_041_out;
output   filt_2_Q_0_4_041_out_ap_vld;
output  [17:0] filt_2_Q_2_3_040_out;
output   filt_2_Q_2_3_040_out_ap_vld;
output  [17:0] filt_2_Q_1_3_039_out;
output   filt_2_Q_1_3_039_out_ap_vld;
output  [17:0] filt_2_Q_0_3_038_out;
output   filt_2_Q_0_3_038_out_ap_vld;
output  [17:0] filt_2_Q_2_2_037_out;
output   filt_2_Q_2_2_037_out_ap_vld;
output  [17:0] filt_2_Q_1_2_036_out;
output   filt_2_Q_1_2_036_out_ap_vld;
output  [17:0] filt_2_Q_0_2_035_out;
output   filt_2_Q_0_2_035_out_ap_vld;
output  [17:0] filt_2_Q_2_1_034_out;
output   filt_2_Q_2_1_034_out_ap_vld;
output  [17:0] filt_2_Q_1_1_033_out;
output   filt_2_Q_1_1_033_out_ap_vld;
output  [17:0] filt_2_Q_0_1_032_out;
output   filt_2_Q_0_1_032_out_ap_vld;
output  [17:0] filt_2_Q_2_030_out;
output   filt_2_Q_2_030_out_ap_vld;
output  [17:0] filt_2_Q_1_028_out;
output   filt_2_Q_1_028_out_ap_vld;
output  [17:0] filt_2_Q_0_0_out;
output   filt_2_Q_0_0_out_ap_vld;
output  [17:0] filt_2_I_2_7_026_out;
output   filt_2_I_2_7_026_out_ap_vld;
output  [17:0] filt_2_I_1_7_025_out;
output   filt_2_I_1_7_025_out_ap_vld;
output  [17:0] filt_2_I_0_7_024_out;
output   filt_2_I_0_7_024_out_ap_vld;
output  [17:0] filt_2_I_2_6_023_out;
output   filt_2_I_2_6_023_out_ap_vld;
output  [17:0] filt_2_I_1_6_022_out;
output   filt_2_I_1_6_022_out_ap_vld;
output  [17:0] filt_2_I_0_6_021_out;
output   filt_2_I_0_6_021_out_ap_vld;
output  [17:0] filt_2_I_2_5_020_out;
output   filt_2_I_2_5_020_out_ap_vld;
output  [17:0] filt_2_I_1_5_019_out;
output   filt_2_I_1_5_019_out_ap_vld;
output  [17:0] filt_2_I_0_5_018_out;
output   filt_2_I_0_5_018_out_ap_vld;
output  [17:0] filt_2_I_2_4_017_out;
output   filt_2_I_2_4_017_out_ap_vld;
output  [17:0] filt_2_I_1_4_016_out;
output   filt_2_I_1_4_016_out_ap_vld;
output  [17:0] filt_2_I_0_4_015_out;
output   filt_2_I_0_4_015_out_ap_vld;
output  [17:0] filt_2_I_2_3_014_out;
output   filt_2_I_2_3_014_out_ap_vld;
output  [17:0] filt_2_I_1_3_013_out;
output   filt_2_I_1_3_013_out_ap_vld;
output  [17:0] filt_2_I_0_3_012_out;
output   filt_2_I_0_3_012_out_ap_vld;
output  [17:0] filt_2_I_2_2_011_out;
output   filt_2_I_2_2_011_out_ap_vld;
output  [17:0] filt_2_I_1_2_010_out;
output   filt_2_I_1_2_010_out_ap_vld;
output  [17:0] filt_2_I_0_2_09_out;
output   filt_2_I_0_2_09_out_ap_vld;
output  [17:0] filt_2_I_2_1_08_out;
output   filt_2_I_2_1_08_out_ap_vld;
output  [17:0] filt_2_I_1_1_07_out;
output   filt_2_I_1_1_07_out_ap_vld;
output  [17:0] filt_2_I_0_1_06_out;
output   filt_2_I_0_1_06_out_ap_vld;
output  [17:0] filt_2_I_2_04_out;
output   filt_2_I_2_04_out_ap_vld;
output  [17:0] filt_2_I_1_02_out;
output   filt_2_I_1_02_out_ap_vld;
output  [17:0] filt_2_I_0_0_out;
output   filt_2_I_0_0_out_ap_vld;

reg ap_idle;
reg filt_1_I_ce0;
reg filt_1_I_ce1;
reg filt_1_I_1_ce0;
reg filt_1_I_1_ce1;
reg filt_1_Q_ce0;
reg filt_1_Q_ce1;
reg filt_1_Q_1_ce0;
reg filt_1_Q_1_ce1;
reg filt_1_I_2_ce0;
reg filt_1_I_2_ce1;
reg filt_1_I_3_ce0;
reg filt_1_I_3_ce1;
reg filt_1_Q_2_ce0;
reg filt_1_Q_2_ce1;
reg filt_1_Q_3_ce0;
reg filt_1_Q_3_ce1;
reg filt_1_I_4_ce0;
reg filt_1_I_4_ce1;
reg filt_1_I_5_ce0;
reg filt_1_I_5_ce1;
reg filt_1_Q_4_ce0;
reg filt_1_Q_4_ce1;
reg filt_1_Q_5_ce0;
reg filt_1_Q_5_ce1;
reg filt_1_I_6_ce0;
reg filt_1_I_6_ce1;
reg filt_1_I_7_ce0;
reg filt_1_I_7_ce1;
reg filt_1_Q_6_ce0;
reg filt_1_Q_6_ce1;
reg filt_1_Q_7_ce0;
reg filt_1_Q_7_ce1;
reg filt_2_Q_2_7_052_out_ap_vld;
reg filt_2_Q_1_7_051_out_ap_vld;
reg filt_2_Q_0_7_050_out_ap_vld;
reg filt_2_Q_2_6_049_out_ap_vld;
reg filt_2_Q_1_6_048_out_ap_vld;
reg filt_2_Q_0_6_047_out_ap_vld;
reg filt_2_Q_2_5_046_out_ap_vld;
reg filt_2_Q_1_5_045_out_ap_vld;
reg filt_2_Q_0_5_044_out_ap_vld;
reg filt_2_Q_2_4_043_out_ap_vld;
reg filt_2_Q_1_4_042_out_ap_vld;
reg filt_2_Q_0_4_041_out_ap_vld;
reg filt_2_Q_2_3_040_out_ap_vld;
reg filt_2_Q_1_3_039_out_ap_vld;
reg filt_2_Q_0_3_038_out_ap_vld;
reg filt_2_Q_2_2_037_out_ap_vld;
reg filt_2_Q_1_2_036_out_ap_vld;
reg filt_2_Q_0_2_035_out_ap_vld;
reg filt_2_Q_2_1_034_out_ap_vld;
reg filt_2_Q_1_1_033_out_ap_vld;
reg filt_2_Q_0_1_032_out_ap_vld;
reg filt_2_Q_2_030_out_ap_vld;
reg filt_2_Q_1_028_out_ap_vld;
reg filt_2_Q_0_0_out_ap_vld;
reg filt_2_I_2_7_026_out_ap_vld;
reg filt_2_I_1_7_025_out_ap_vld;
reg filt_2_I_0_7_024_out_ap_vld;
reg filt_2_I_2_6_023_out_ap_vld;
reg filt_2_I_1_6_022_out_ap_vld;
reg filt_2_I_0_6_021_out_ap_vld;
reg filt_2_I_2_5_020_out_ap_vld;
reg filt_2_I_1_5_019_out_ap_vld;
reg filt_2_I_0_5_018_out_ap_vld;
reg filt_2_I_2_4_017_out_ap_vld;
reg filt_2_I_1_4_016_out_ap_vld;
reg filt_2_I_0_4_015_out_ap_vld;
reg filt_2_I_2_3_014_out_ap_vld;
reg filt_2_I_1_3_013_out_ap_vld;
reg filt_2_I_0_3_012_out_ap_vld;
reg filt_2_I_2_2_011_out_ap_vld;
reg filt_2_I_1_2_010_out_ap_vld;
reg filt_2_I_0_2_09_out_ap_vld;
reg filt_2_I_2_1_08_out_ap_vld;
reg filt_2_I_1_1_07_out_ap_vld;
reg filt_2_I_0_1_06_out_ap_vld;
reg filt_2_I_2_04_out_ap_vld;
reg filt_2_I_1_02_out_ap_vld;
reg filt_2_I_0_0_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln111_fu_1124_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln111_reg_2013;
wire   [2:0] lshr_ln4_fu_1130_p4;
reg   [2:0] lshr_ln4_reg_2017;
wire   [63:0] zext_ln111_fu_1140_p1;
reg   [63:0] zext_ln111_reg_2022;
reg   [1:0] trunc_ln5_reg_2048;
reg   [1:0] trunc_ln5_reg_2048_pp0_iter1_reg;
wire   [17:0] filt_2_I_1_32_fu_1169_p2;
reg   [17:0] filt_2_I_1_32_reg_2062;
wire   [17:0] filt_2_Q_1_32_fu_1200_p2;
reg   [17:0] filt_2_Q_1_32_reg_2209;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln113_fu_1180_p1;
reg   [5:0] i_4_fu_174;
wire   [5:0] add_ln111_fu_1158_p2;
wire    ap_loop_init;
reg   [5:0] ap_sig_allocacmp_i;
reg   [17:0] filt_2_I_1_fu_178;
reg   [17:0] filt_2_I_1_1_fu_182;
reg   [17:0] filt_2_I_1_2_fu_186;
reg   [17:0] filt_2_I_1_3_fu_190;
wire   [17:0] filt_2_I_1_33_fu_1206_p2;
reg   [17:0] filt_2_I_1_4_fu_194;
reg   [17:0] filt_2_I_1_5_fu_198;
reg   [17:0] filt_2_I_1_6_fu_202;
wire   [17:0] filt_2_I_1_34_fu_1212_p2;
reg   [17:0] filt_2_I_1_7_fu_206;
reg   [17:0] filt_2_I_1_8_fu_210;
reg   [17:0] filt_2_I_1_9_fu_214;
wire   [17:0] filt_2_I_1_35_fu_1218_p2;
reg   [17:0] filt_2_I_1_10_fu_218;
reg   [17:0] filt_2_I_1_11_fu_222;
reg   [17:0] filt_2_I_1_12_fu_226;
wire   [17:0] filt_2_I_1_36_fu_1224_p2;
reg   [17:0] filt_2_I_1_13_fu_230;
reg   [17:0] filt_2_I_1_14_fu_234;
reg   [17:0] filt_2_I_1_15_fu_238;
wire   [17:0] filt_2_I_1_37_fu_1230_p2;
reg   [17:0] filt_2_I_1_16_fu_242;
reg   [17:0] filt_2_I_1_17_fu_246;
reg   [17:0] filt_2_I_1_18_fu_250;
wire   [17:0] filt_2_I_1_38_fu_1236_p2;
reg   [17:0] filt_2_I_1_19_fu_254;
reg   [17:0] filt_2_I_1_20_fu_258;
reg   [17:0] filt_2_I_1_21_fu_262;
wire   [17:0] filt_2_I_1_39_fu_1242_p2;
reg   [17:0] filt_2_I_1_22_fu_266;
reg   [17:0] filt_2_I_1_23_fu_270;
reg   [17:0] filt_2_Q_1_fu_274;
reg   [17:0] filt_2_Q_1_1_fu_278;
reg   [17:0] filt_2_Q_1_2_fu_282;
reg   [17:0] filt_2_Q_1_3_fu_286;
wire   [17:0] filt_2_Q_1_34_fu_1254_p2;
reg   [17:0] filt_2_Q_1_4_fu_290;
reg   [17:0] filt_2_Q_1_5_fu_294;
reg   [17:0] filt_2_Q_1_6_fu_298;
wire   [17:0] filt_2_Q_1_36_fu_1266_p2;
reg   [17:0] filt_2_Q_1_7_fu_302;
reg   [17:0] filt_2_Q_1_8_fu_306;
reg   [17:0] filt_2_Q_1_9_fu_310;
wire   [17:0] filt_2_Q_1_38_fu_1278_p2;
reg   [17:0] filt_2_Q_1_10_fu_314;
reg   [17:0] filt_2_Q_1_11_fu_318;
reg   [17:0] filt_2_Q_1_12_fu_322;
wire   [17:0] filt_2_Q_1_33_fu_1248_p2;
reg   [17:0] filt_2_Q_1_13_fu_326;
reg   [17:0] filt_2_Q_1_14_fu_330;
reg   [17:0] filt_2_Q_1_15_fu_334;
wire   [17:0] filt_2_Q_1_35_fu_1260_p2;
reg   [17:0] filt_2_Q_1_16_fu_338;
reg   [17:0] filt_2_Q_1_17_fu_342;
reg   [17:0] filt_2_Q_1_18_fu_346;
wire   [17:0] filt_2_Q_1_37_fu_1272_p2;
reg   [17:0] filt_2_Q_1_19_fu_350;
reg   [17:0] filt_2_Q_1_20_fu_354;
reg   [17:0] filt_2_Q_1_21_fu_358;
wire   [17:0] filt_2_Q_1_39_fu_1284_p2;
reg   [17:0] filt_2_Q_1_22_fu_362;
reg   [17:0] filt_2_Q_1_23_fu_366;
wire    ap_block_pp0_stage0_01001;
wire   [2:0] or_ln113_fu_1175_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

receiver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            filt_2_I_1_fu_178 <= 18'd0;
        end else if (((trunc_ln5_reg_2048_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            filt_2_I_1_fu_178 <= filt_2_I_1_32_reg_2062;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            filt_2_Q_1_fu_274 <= 18'd0;
        end else if (((trunc_ln5_reg_2048_pp0_iter1_reg == 2'd0) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
            filt_2_Q_1_fu_274 <= filt_2_Q_1_32_reg_2209;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln111_fu_1124_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_4_fu_174 <= add_ln111_fu_1158_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_4_fu_174 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        filt_2_I_1_32_reg_2062 <= filt_2_I_1_32_fu_1169_p2;
        filt_2_Q_1_32_reg_2209 <= filt_2_Q_1_32_fu_1200_p2;
        icmp_ln111_reg_2013 <= icmp_ln111_fu_1124_p2;
        trunc_ln5_reg_2048_pp0_iter1_reg <= trunc_ln5_reg_2048;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln5_reg_2048_pp0_iter1_reg == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_2_I_1_10_fu_218 <= filt_2_I_1_35_fu_1218_p2;
        filt_2_I_1_13_fu_230 <= filt_2_I_1_36_fu_1224_p2;
        filt_2_I_1_16_fu_242 <= filt_2_I_1_37_fu_1230_p2;
        filt_2_I_1_19_fu_254 <= filt_2_I_1_38_fu_1236_p2;
        filt_2_I_1_1_fu_182 <= filt_2_I_1_32_reg_2062;
        filt_2_I_1_22_fu_266 <= filt_2_I_1_39_fu_1242_p2;
        filt_2_I_1_4_fu_194 <= filt_2_I_1_33_fu_1206_p2;
        filt_2_I_1_7_fu_206 <= filt_2_I_1_34_fu_1212_p2;
        filt_2_Q_1_10_fu_314 <= filt_2_Q_1_38_fu_1278_p2;
        filt_2_Q_1_13_fu_326 <= filt_2_Q_1_33_fu_1248_p2;
        filt_2_Q_1_16_fu_338 <= filt_2_Q_1_35_fu_1260_p2;
        filt_2_Q_1_19_fu_350 <= filt_2_Q_1_37_fu_1272_p2;
        filt_2_Q_1_1_fu_278 <= filt_2_Q_1_32_reg_2209;
        filt_2_Q_1_22_fu_362 <= filt_2_Q_1_39_fu_1284_p2;
        filt_2_Q_1_4_fu_290 <= filt_2_Q_1_34_fu_1254_p2;
        filt_2_Q_1_7_fu_302 <= filt_2_Q_1_36_fu_1266_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(trunc_ln5_reg_2048_pp0_iter1_reg == 2'd1) & ~(trunc_ln5_reg_2048_pp0_iter1_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_2_I_1_11_fu_222 <= filt_2_I_1_35_fu_1218_p2;
        filt_2_I_1_14_fu_234 <= filt_2_I_1_36_fu_1224_p2;
        filt_2_I_1_17_fu_246 <= filt_2_I_1_37_fu_1230_p2;
        filt_2_I_1_20_fu_258 <= filt_2_I_1_38_fu_1236_p2;
        filt_2_I_1_23_fu_270 <= filt_2_I_1_39_fu_1242_p2;
        filt_2_I_1_2_fu_186 <= filt_2_I_1_32_reg_2062;
        filt_2_I_1_5_fu_198 <= filt_2_I_1_33_fu_1206_p2;
        filt_2_I_1_8_fu_210 <= filt_2_I_1_34_fu_1212_p2;
        filt_2_Q_1_11_fu_318 <= filt_2_Q_1_38_fu_1278_p2;
        filt_2_Q_1_14_fu_330 <= filt_2_Q_1_33_fu_1248_p2;
        filt_2_Q_1_17_fu_342 <= filt_2_Q_1_35_fu_1260_p2;
        filt_2_Q_1_20_fu_354 <= filt_2_Q_1_37_fu_1272_p2;
        filt_2_Q_1_23_fu_366 <= filt_2_Q_1_39_fu_1284_p2;
        filt_2_Q_1_2_fu_282 <= filt_2_Q_1_32_reg_2209;
        filt_2_Q_1_5_fu_294 <= filt_2_Q_1_34_fu_1254_p2;
        filt_2_Q_1_8_fu_306 <= filt_2_Q_1_36_fu_1266_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln5_reg_2048_pp0_iter1_reg == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_2_I_1_12_fu_226 <= filt_2_I_1_36_fu_1224_p2;
        filt_2_I_1_15_fu_238 <= filt_2_I_1_37_fu_1230_p2;
        filt_2_I_1_18_fu_250 <= filt_2_I_1_38_fu_1236_p2;
        filt_2_I_1_21_fu_262 <= filt_2_I_1_39_fu_1242_p2;
        filt_2_I_1_3_fu_190 <= filt_2_I_1_33_fu_1206_p2;
        filt_2_I_1_6_fu_202 <= filt_2_I_1_34_fu_1212_p2;
        filt_2_I_1_9_fu_214 <= filt_2_I_1_35_fu_1218_p2;
        filt_2_Q_1_12_fu_322 <= filt_2_Q_1_33_fu_1248_p2;
        filt_2_Q_1_15_fu_334 <= filt_2_Q_1_35_fu_1260_p2;
        filt_2_Q_1_18_fu_346 <= filt_2_Q_1_37_fu_1272_p2;
        filt_2_Q_1_21_fu_358 <= filt_2_Q_1_39_fu_1284_p2;
        filt_2_Q_1_3_fu_286 <= filt_2_Q_1_34_fu_1254_p2;
        filt_2_Q_1_6_fu_298 <= filt_2_Q_1_36_fu_1266_p2;
        filt_2_Q_1_9_fu_310 <= filt_2_Q_1_38_fu_1278_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln111_fu_1124_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln4_reg_2017 <= {{ap_sig_allocacmp_i[5:3]}};
        trunc_ln5_reg_2048 <= {{ap_sig_allocacmp_i[5:4]}};
        zext_ln111_reg_2022[2 : 0] <= zext_ln111_fu_1140_p1[2 : 0];
    end
end

always @ (*) begin
    if (((icmp_ln111_fu_1124_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 6'd0;
    end else begin
        ap_sig_allocacmp_i = i_4_fu_174;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_1_ce0 = 1'b1;
    end else begin
        filt_1_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_1_ce1 = 1'b1;
    end else begin
        filt_1_I_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_2_ce0 = 1'b1;
    end else begin
        filt_1_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_2_ce1 = 1'b1;
    end else begin
        filt_1_I_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_3_ce0 = 1'b1;
    end else begin
        filt_1_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_3_ce1 = 1'b1;
    end else begin
        filt_1_I_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_4_ce0 = 1'b1;
    end else begin
        filt_1_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_4_ce1 = 1'b1;
    end else begin
        filt_1_I_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_5_ce0 = 1'b1;
    end else begin
        filt_1_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_5_ce1 = 1'b1;
    end else begin
        filt_1_I_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_6_ce0 = 1'b1;
    end else begin
        filt_1_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_6_ce1 = 1'b1;
    end else begin
        filt_1_I_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_7_ce0 = 1'b1;
    end else begin
        filt_1_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_7_ce1 = 1'b1;
    end else begin
        filt_1_I_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_ce0 = 1'b1;
    end else begin
        filt_1_I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_I_ce1 = 1'b1;
    end else begin
        filt_1_I_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_1_ce0 = 1'b1;
    end else begin
        filt_1_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_1_ce1 = 1'b1;
    end else begin
        filt_1_Q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_2_ce0 = 1'b1;
    end else begin
        filt_1_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_2_ce1 = 1'b1;
    end else begin
        filt_1_Q_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_3_ce0 = 1'b1;
    end else begin
        filt_1_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_3_ce1 = 1'b1;
    end else begin
        filt_1_Q_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_4_ce0 = 1'b1;
    end else begin
        filt_1_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_4_ce1 = 1'b1;
    end else begin
        filt_1_Q_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_5_ce0 = 1'b1;
    end else begin
        filt_1_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_5_ce1 = 1'b1;
    end else begin
        filt_1_Q_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_6_ce0 = 1'b1;
    end else begin
        filt_1_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_6_ce1 = 1'b1;
    end else begin
        filt_1_Q_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_7_ce0 = 1'b1;
    end else begin
        filt_1_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_7_ce1 = 1'b1;
    end else begin
        filt_1_Q_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_ce0 = 1'b1;
    end else begin
        filt_1_Q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_1_Q_ce1 = 1'b1;
    end else begin
        filt_1_Q_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_0_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_1_06_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_1_06_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_2_09_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_2_09_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_3_012_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_3_012_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_4_015_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_4_015_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_5_018_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_5_018_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_6_021_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_6_021_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_0_7_024_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_0_7_024_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_02_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_02_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_1_07_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_1_07_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_2_010_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_2_010_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_3_013_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_3_013_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_4_016_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_4_016_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_5_019_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_5_019_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_6_022_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_6_022_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_1_7_025_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_1_7_025_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_04_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_04_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_1_08_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_1_08_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_2_011_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_2_011_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_3_014_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_3_014_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_4_017_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_4_017_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_5_020_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_5_020_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_6_023_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_6_023_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_I_2_7_026_out_ap_vld = 1'b1;
    end else begin
        filt_2_I_2_7_026_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_0_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_0_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_1_032_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_1_032_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_2_035_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_2_035_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_3_038_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_3_038_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_4_041_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_4_041_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_5_044_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_5_044_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_6_047_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_6_047_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_0_7_050_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_0_7_050_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_028_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_028_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_1_033_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_1_033_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_2_036_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_2_036_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_3_039_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_3_039_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_4_042_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_4_042_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_5_045_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_5_045_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_6_048_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_6_048_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_1_7_051_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_1_7_051_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_030_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_030_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_1_034_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_1_034_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_2_037_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_2_037_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_3_040_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_3_040_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_4_043_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_4_043_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_5_046_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_5_046_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_6_049_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_6_049_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln111_reg_2013 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_2_Q_2_7_052_out_ap_vld = 1'b1;
    end else begin
        filt_2_Q_2_7_052_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln111_fu_1158_p2 = (ap_sig_allocacmp_i + 6'd16);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign filt_1_I_1_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_1_address1 = zext_ln111_fu_1140_p1;

assign filt_1_I_2_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_2_address1 = zext_ln111_reg_2022;

assign filt_1_I_3_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_3_address1 = zext_ln111_reg_2022;

assign filt_1_I_4_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_4_address1 = zext_ln111_reg_2022;

assign filt_1_I_5_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_5_address1 = zext_ln111_reg_2022;

assign filt_1_I_6_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_6_address1 = zext_ln111_reg_2022;

assign filt_1_I_7_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_7_address1 = zext_ln111_reg_2022;

assign filt_1_I_address0 = zext_ln113_fu_1180_p1;

assign filt_1_I_address1 = zext_ln111_fu_1140_p1;

assign filt_1_Q_1_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_1_address1 = zext_ln111_fu_1140_p1;

assign filt_1_Q_2_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_2_address1 = zext_ln111_reg_2022;

assign filt_1_Q_3_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_3_address1 = zext_ln111_reg_2022;

assign filt_1_Q_4_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_4_address1 = zext_ln111_reg_2022;

assign filt_1_Q_5_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_5_address1 = zext_ln111_reg_2022;

assign filt_1_Q_6_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_6_address1 = zext_ln111_reg_2022;

assign filt_1_Q_7_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_7_address1 = zext_ln111_reg_2022;

assign filt_1_Q_address0 = zext_ln113_fu_1180_p1;

assign filt_1_Q_address1 = zext_ln111_fu_1140_p1;

assign filt_2_I_0_0_out = filt_2_I_1_fu_178;

assign filt_2_I_0_1_06_out = filt_2_I_1_3_fu_190;

assign filt_2_I_0_2_09_out = filt_2_I_1_6_fu_202;

assign filt_2_I_0_3_012_out = filt_2_I_1_9_fu_214;

assign filt_2_I_0_4_015_out = filt_2_I_1_12_fu_226;

assign filt_2_I_0_5_018_out = filt_2_I_1_15_fu_238;

assign filt_2_I_0_6_021_out = filt_2_I_1_18_fu_250;

assign filt_2_I_0_7_024_out = filt_2_I_1_21_fu_262;

assign filt_2_I_1_02_out = filt_2_I_1_1_fu_182;

assign filt_2_I_1_1_07_out = filt_2_I_1_4_fu_194;

assign filt_2_I_1_2_010_out = filt_2_I_1_7_fu_206;

assign filt_2_I_1_32_fu_1169_p2 = (filt_1_I_1_q1 + filt_1_I_q1);

assign filt_2_I_1_33_fu_1206_p2 = (filt_1_I_3_q1 + filt_1_I_2_q1);

assign filt_2_I_1_34_fu_1212_p2 = (filt_1_I_5_q1 + filt_1_I_4_q1);

assign filt_2_I_1_35_fu_1218_p2 = (filt_1_I_7_q1 + filt_1_I_6_q1);

assign filt_2_I_1_36_fu_1224_p2 = (filt_1_I_1_q0 + filt_1_I_q0);

assign filt_2_I_1_37_fu_1230_p2 = (filt_1_I_3_q0 + filt_1_I_2_q0);

assign filt_2_I_1_38_fu_1236_p2 = (filt_1_I_5_q0 + filt_1_I_4_q0);

assign filt_2_I_1_39_fu_1242_p2 = (filt_1_I_7_q0 + filt_1_I_6_q0);

assign filt_2_I_1_3_013_out = filt_2_I_1_10_fu_218;

assign filt_2_I_1_4_016_out = filt_2_I_1_13_fu_230;

assign filt_2_I_1_5_019_out = filt_2_I_1_16_fu_242;

assign filt_2_I_1_6_022_out = filt_2_I_1_19_fu_254;

assign filt_2_I_1_7_025_out = filt_2_I_1_22_fu_266;

assign filt_2_I_2_04_out = filt_2_I_1_2_fu_186;

assign filt_2_I_2_1_08_out = filt_2_I_1_5_fu_198;

assign filt_2_I_2_2_011_out = filt_2_I_1_8_fu_210;

assign filt_2_I_2_3_014_out = filt_2_I_1_11_fu_222;

assign filt_2_I_2_4_017_out = filt_2_I_1_14_fu_234;

assign filt_2_I_2_5_020_out = filt_2_I_1_17_fu_246;

assign filt_2_I_2_6_023_out = filt_2_I_1_20_fu_258;

assign filt_2_I_2_7_026_out = filt_2_I_1_23_fu_270;

assign filt_2_Q_0_0_out = filt_2_Q_1_fu_274;

assign filt_2_Q_0_1_032_out = filt_2_Q_1_3_fu_286;

assign filt_2_Q_0_2_035_out = filt_2_Q_1_6_fu_298;

assign filt_2_Q_0_3_038_out = filt_2_Q_1_9_fu_310;

assign filt_2_Q_0_4_041_out = filt_2_Q_1_12_fu_322;

assign filt_2_Q_0_5_044_out = filt_2_Q_1_15_fu_334;

assign filt_2_Q_0_6_047_out = filt_2_Q_1_18_fu_346;

assign filt_2_Q_0_7_050_out = filt_2_Q_1_21_fu_358;

assign filt_2_Q_1_028_out = filt_2_Q_1_1_fu_278;

assign filt_2_Q_1_1_033_out = filt_2_Q_1_4_fu_290;

assign filt_2_Q_1_2_036_out = filt_2_Q_1_7_fu_302;

assign filt_2_Q_1_32_fu_1200_p2 = (filt_1_Q_1_q1 + filt_1_Q_q1);

assign filt_2_Q_1_33_fu_1248_p2 = (filt_1_Q_1_q0 + filt_1_Q_q0);

assign filt_2_Q_1_34_fu_1254_p2 = (filt_1_Q_3_q1 + filt_1_Q_2_q1);

assign filt_2_Q_1_35_fu_1260_p2 = (filt_1_Q_3_q0 + filt_1_Q_2_q0);

assign filt_2_Q_1_36_fu_1266_p2 = (filt_1_Q_5_q1 + filt_1_Q_4_q1);

assign filt_2_Q_1_37_fu_1272_p2 = (filt_1_Q_5_q0 + filt_1_Q_4_q0);

assign filt_2_Q_1_38_fu_1278_p2 = (filt_1_Q_7_q1 + filt_1_Q_6_q1);

assign filt_2_Q_1_39_fu_1284_p2 = (filt_1_Q_7_q0 + filt_1_Q_6_q0);

assign filt_2_Q_1_3_039_out = filt_2_Q_1_10_fu_314;

assign filt_2_Q_1_4_042_out = filt_2_Q_1_13_fu_326;

assign filt_2_Q_1_5_045_out = filt_2_Q_1_16_fu_338;

assign filt_2_Q_1_6_048_out = filt_2_Q_1_19_fu_350;

assign filt_2_Q_1_7_051_out = filt_2_Q_1_22_fu_362;

assign filt_2_Q_2_030_out = filt_2_Q_1_2_fu_282;

assign filt_2_Q_2_1_034_out = filt_2_Q_1_5_fu_294;

assign filt_2_Q_2_2_037_out = filt_2_Q_1_8_fu_306;

assign filt_2_Q_2_3_040_out = filt_2_Q_1_11_fu_318;

assign filt_2_Q_2_4_043_out = filt_2_Q_1_14_fu_330;

assign filt_2_Q_2_5_046_out = filt_2_Q_1_17_fu_342;

assign filt_2_Q_2_6_049_out = filt_2_Q_1_20_fu_354;

assign filt_2_Q_2_7_052_out = filt_2_Q_1_23_fu_366;

assign icmp_ln111_fu_1124_p2 = ((ap_sig_allocacmp_i == 6'd48) ? 1'b1 : 1'b0);

assign lshr_ln4_fu_1130_p4 = {{ap_sig_allocacmp_i[5:3]}};

assign or_ln113_fu_1175_p2 = (lshr_ln4_reg_2017 | 3'd1);

assign zext_ln111_fu_1140_p1 = lshr_ln4_fu_1130_p4;

assign zext_ln113_fu_1180_p1 = or_ln113_fu_1175_p2;

always @ (posedge ap_clk) begin
    zext_ln111_reg_2022[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //receiver_receiver_Pipeline_VITIS_LOOP_111_5
