// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module receiver_receiver_Pipeline_VITIS_LOOP_142_9 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        matched_I_1_address0,
        matched_I_1_ce0,
        matched_I_1_we0,
        matched_I_1_d0,
        matched_I_1_address1,
        matched_I_1_ce1,
        matched_I_1_q1,
        matched_I_2_address0,
        matched_I_2_ce0,
        matched_I_2_we0,
        matched_I_2_d0,
        matched_I_2_address1,
        matched_I_2_ce1,
        matched_I_2_q1,
        matched_I_3_address0,
        matched_I_3_ce0,
        matched_I_3_we0,
        matched_I_3_d0,
        matched_I_3_address1,
        matched_I_3_ce1,
        matched_I_3_q1,
        matched_I_4_address0,
        matched_I_4_ce0,
        matched_I_4_we0,
        matched_I_4_d0,
        matched_I_4_address1,
        matched_I_4_ce1,
        matched_I_4_q1,
        matched_I_5_address0,
        matched_I_5_ce0,
        matched_I_5_we0,
        matched_I_5_d0,
        matched_I_5_address1,
        matched_I_5_ce1,
        matched_I_5_q1,
        matched_I_6_address0,
        matched_I_6_ce0,
        matched_I_6_we0,
        matched_I_6_d0,
        matched_I_6_address1,
        matched_I_6_ce1,
        matched_I_6_q1,
        matched_I_7_address0,
        matched_I_7_ce0,
        matched_I_7_we0,
        matched_I_7_d0,
        matched_I_7_address1,
        matched_I_7_ce1,
        matched_I_7_q1,
        matched_I_8_address0,
        matched_I_8_ce0,
        matched_I_8_we0,
        matched_I_8_d0,
        matched_I_8_address1,
        matched_I_8_ce1,
        matched_I_8_q1,
        matched_I_9_address0,
        matched_I_9_ce0,
        matched_I_9_we0,
        matched_I_9_d0,
        matched_I_9_address1,
        matched_I_9_ce1,
        matched_I_9_q1,
        matched_I_10_address0,
        matched_I_10_ce0,
        matched_I_10_we0,
        matched_I_10_d0,
        matched_I_10_address1,
        matched_I_10_ce1,
        matched_I_10_q1,
        matched_I_11_address0,
        matched_I_11_ce0,
        matched_I_11_we0,
        matched_I_11_d0,
        matched_I_11_address1,
        matched_I_11_ce1,
        matched_I_11_q1,
        matched_I_0_address0,
        matched_I_0_ce0,
        matched_I_0_we0,
        matched_I_0_d0,
        matched_I_0_address1,
        matched_I_0_ce1,
        matched_I_0_q1,
        matched_Q_11_address0,
        matched_Q_11_ce0,
        matched_Q_11_we0,
        matched_Q_11_d0,
        matched_Q_11_address1,
        matched_Q_11_ce1,
        matched_Q_11_q1,
        matched_Q_1_address0,
        matched_Q_1_ce0,
        matched_Q_1_we0,
        matched_Q_1_d0,
        matched_Q_1_address1,
        matched_Q_1_ce1,
        matched_Q_1_q1,
        matched_Q_0_address0,
        matched_Q_0_ce0,
        matched_Q_0_we0,
        matched_Q_0_d0,
        matched_Q_0_address1,
        matched_Q_0_ce1,
        matched_Q_0_q1,
        matched_Q_2_address0,
        matched_Q_2_ce0,
        matched_Q_2_we0,
        matched_Q_2_d0,
        matched_Q_2_address1,
        matched_Q_2_ce1,
        matched_Q_2_q1,
        matched_Q_3_address0,
        matched_Q_3_ce0,
        matched_Q_3_we0,
        matched_Q_3_d0,
        matched_Q_3_address1,
        matched_Q_3_ce1,
        matched_Q_3_q1,
        matched_Q_4_address0,
        matched_Q_4_ce0,
        matched_Q_4_we0,
        matched_Q_4_d0,
        matched_Q_4_address1,
        matched_Q_4_ce1,
        matched_Q_4_q1,
        matched_Q_5_address0,
        matched_Q_5_ce0,
        matched_Q_5_we0,
        matched_Q_5_d0,
        matched_Q_5_address1,
        matched_Q_5_ce1,
        matched_Q_5_q1,
        matched_Q_6_address0,
        matched_Q_6_ce0,
        matched_Q_6_we0,
        matched_Q_6_d0,
        matched_Q_6_address1,
        matched_Q_6_ce1,
        matched_Q_6_q1,
        matched_Q_7_address0,
        matched_Q_7_ce0,
        matched_Q_7_we0,
        matched_Q_7_d0,
        matched_Q_7_address1,
        matched_Q_7_ce1,
        matched_Q_7_q1,
        matched_Q_8_address0,
        matched_Q_8_ce0,
        matched_Q_8_we0,
        matched_Q_8_d0,
        matched_Q_8_address1,
        matched_Q_8_ce1,
        matched_Q_8_q1,
        matched_Q_9_address0,
        matched_Q_9_ce0,
        matched_Q_9_we0,
        matched_Q_9_d0,
        matched_Q_9_address1,
        matched_Q_9_ce1,
        matched_Q_9_q1,
        matched_Q_10_address0,
        matched_Q_10_ce0,
        matched_Q_10_we0,
        matched_Q_10_d0,
        matched_Q_10_address1,
        matched_Q_10_ce1,
        matched_Q_10_q1,
        matched_I_12_address0,
        matched_I_12_ce0,
        matched_I_12_we0,
        matched_I_12_d0,
        matched_I_12_address1,
        matched_I_12_ce1,
        matched_I_12_q1,
        matched_I_13_address0,
        matched_I_13_ce0,
        matched_I_13_we0,
        matched_I_13_d0,
        matched_I_13_address1,
        matched_I_13_ce1,
        matched_I_13_q1,
        matched_I_14_address0,
        matched_I_14_ce0,
        matched_I_14_we0,
        matched_I_14_d0,
        matched_I_14_address1,
        matched_I_14_ce1,
        matched_I_14_q1,
        matched_I_15_address0,
        matched_I_15_ce0,
        matched_I_15_we0,
        matched_I_15_d0,
        matched_I_15_address1,
        matched_I_15_ce1,
        matched_I_15_q1,
        matched_Q_12_address0,
        matched_Q_12_ce0,
        matched_Q_12_we0,
        matched_Q_12_d0,
        matched_Q_12_address1,
        matched_Q_12_ce1,
        matched_Q_12_q1,
        matched_Q_13_address0,
        matched_Q_13_ce0,
        matched_Q_13_we0,
        matched_Q_13_d0,
        matched_Q_13_address1,
        matched_Q_13_ce1,
        matched_Q_13_q1,
        matched_Q_14_address0,
        matched_Q_14_ce0,
        matched_Q_14_we0,
        matched_Q_14_d0,
        matched_Q_14_address1,
        matched_Q_14_ce1,
        matched_Q_14_q1,
        matched_Q_15_address0,
        matched_Q_15_ce0,
        matched_Q_15_we0,
        matched_Q_15_d0,
        matched_Q_15_address1,
        matched_Q_15_ce1,
        matched_Q_15_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] matched_I_1_address0;
output   matched_I_1_ce0;
output   matched_I_1_we0;
output  [17:0] matched_I_1_d0;
output  [7:0] matched_I_1_address1;
output   matched_I_1_ce1;
input  [17:0] matched_I_1_q1;
output  [7:0] matched_I_2_address0;
output   matched_I_2_ce0;
output   matched_I_2_we0;
output  [17:0] matched_I_2_d0;
output  [7:0] matched_I_2_address1;
output   matched_I_2_ce1;
input  [17:0] matched_I_2_q1;
output  [7:0] matched_I_3_address0;
output   matched_I_3_ce0;
output   matched_I_3_we0;
output  [17:0] matched_I_3_d0;
output  [7:0] matched_I_3_address1;
output   matched_I_3_ce1;
input  [17:0] matched_I_3_q1;
output  [7:0] matched_I_4_address0;
output   matched_I_4_ce0;
output   matched_I_4_we0;
output  [17:0] matched_I_4_d0;
output  [7:0] matched_I_4_address1;
output   matched_I_4_ce1;
input  [17:0] matched_I_4_q1;
output  [7:0] matched_I_5_address0;
output   matched_I_5_ce0;
output   matched_I_5_we0;
output  [17:0] matched_I_5_d0;
output  [7:0] matched_I_5_address1;
output   matched_I_5_ce1;
input  [17:0] matched_I_5_q1;
output  [7:0] matched_I_6_address0;
output   matched_I_6_ce0;
output   matched_I_6_we0;
output  [17:0] matched_I_6_d0;
output  [7:0] matched_I_6_address1;
output   matched_I_6_ce1;
input  [17:0] matched_I_6_q1;
output  [7:0] matched_I_7_address0;
output   matched_I_7_ce0;
output   matched_I_7_we0;
output  [17:0] matched_I_7_d0;
output  [7:0] matched_I_7_address1;
output   matched_I_7_ce1;
input  [17:0] matched_I_7_q1;
output  [7:0] matched_I_8_address0;
output   matched_I_8_ce0;
output   matched_I_8_we0;
output  [17:0] matched_I_8_d0;
output  [7:0] matched_I_8_address1;
output   matched_I_8_ce1;
input  [17:0] matched_I_8_q1;
output  [7:0] matched_I_9_address0;
output   matched_I_9_ce0;
output   matched_I_9_we0;
output  [17:0] matched_I_9_d0;
output  [7:0] matched_I_9_address1;
output   matched_I_9_ce1;
input  [17:0] matched_I_9_q1;
output  [7:0] matched_I_10_address0;
output   matched_I_10_ce0;
output   matched_I_10_we0;
output  [17:0] matched_I_10_d0;
output  [7:0] matched_I_10_address1;
output   matched_I_10_ce1;
input  [17:0] matched_I_10_q1;
output  [7:0] matched_I_11_address0;
output   matched_I_11_ce0;
output   matched_I_11_we0;
output  [17:0] matched_I_11_d0;
output  [7:0] matched_I_11_address1;
output   matched_I_11_ce1;
input  [17:0] matched_I_11_q1;
output  [7:0] matched_I_0_address0;
output   matched_I_0_ce0;
output   matched_I_0_we0;
output  [17:0] matched_I_0_d0;
output  [7:0] matched_I_0_address1;
output   matched_I_0_ce1;
input  [17:0] matched_I_0_q1;
output  [7:0] matched_Q_11_address0;
output   matched_Q_11_ce0;
output   matched_Q_11_we0;
output  [17:0] matched_Q_11_d0;
output  [7:0] matched_Q_11_address1;
output   matched_Q_11_ce1;
input  [17:0] matched_Q_11_q1;
output  [7:0] matched_Q_1_address0;
output   matched_Q_1_ce0;
output   matched_Q_1_we0;
output  [17:0] matched_Q_1_d0;
output  [7:0] matched_Q_1_address1;
output   matched_Q_1_ce1;
input  [17:0] matched_Q_1_q1;
output  [7:0] matched_Q_0_address0;
output   matched_Q_0_ce0;
output   matched_Q_0_we0;
output  [17:0] matched_Q_0_d0;
output  [7:0] matched_Q_0_address1;
output   matched_Q_0_ce1;
input  [17:0] matched_Q_0_q1;
output  [7:0] matched_Q_2_address0;
output   matched_Q_2_ce0;
output   matched_Q_2_we0;
output  [17:0] matched_Q_2_d0;
output  [7:0] matched_Q_2_address1;
output   matched_Q_2_ce1;
input  [17:0] matched_Q_2_q1;
output  [7:0] matched_Q_3_address0;
output   matched_Q_3_ce0;
output   matched_Q_3_we0;
output  [17:0] matched_Q_3_d0;
output  [7:0] matched_Q_3_address1;
output   matched_Q_3_ce1;
input  [17:0] matched_Q_3_q1;
output  [7:0] matched_Q_4_address0;
output   matched_Q_4_ce0;
output   matched_Q_4_we0;
output  [17:0] matched_Q_4_d0;
output  [7:0] matched_Q_4_address1;
output   matched_Q_4_ce1;
input  [17:0] matched_Q_4_q1;
output  [7:0] matched_Q_5_address0;
output   matched_Q_5_ce0;
output   matched_Q_5_we0;
output  [17:0] matched_Q_5_d0;
output  [7:0] matched_Q_5_address1;
output   matched_Q_5_ce1;
input  [17:0] matched_Q_5_q1;
output  [7:0] matched_Q_6_address0;
output   matched_Q_6_ce0;
output   matched_Q_6_we0;
output  [17:0] matched_Q_6_d0;
output  [7:0] matched_Q_6_address1;
output   matched_Q_6_ce1;
input  [17:0] matched_Q_6_q1;
output  [7:0] matched_Q_7_address0;
output   matched_Q_7_ce0;
output   matched_Q_7_we0;
output  [17:0] matched_Q_7_d0;
output  [7:0] matched_Q_7_address1;
output   matched_Q_7_ce1;
input  [17:0] matched_Q_7_q1;
output  [7:0] matched_Q_8_address0;
output   matched_Q_8_ce0;
output   matched_Q_8_we0;
output  [17:0] matched_Q_8_d0;
output  [7:0] matched_Q_8_address1;
output   matched_Q_8_ce1;
input  [17:0] matched_Q_8_q1;
output  [7:0] matched_Q_9_address0;
output   matched_Q_9_ce0;
output   matched_Q_9_we0;
output  [17:0] matched_Q_9_d0;
output  [7:0] matched_Q_9_address1;
output   matched_Q_9_ce1;
input  [17:0] matched_Q_9_q1;
output  [7:0] matched_Q_10_address0;
output   matched_Q_10_ce0;
output   matched_Q_10_we0;
output  [17:0] matched_Q_10_d0;
output  [7:0] matched_Q_10_address1;
output   matched_Q_10_ce1;
input  [17:0] matched_Q_10_q1;
output  [7:0] matched_I_12_address0;
output   matched_I_12_ce0;
output   matched_I_12_we0;
output  [17:0] matched_I_12_d0;
output  [7:0] matched_I_12_address1;
output   matched_I_12_ce1;
input  [17:0] matched_I_12_q1;
output  [7:0] matched_I_13_address0;
output   matched_I_13_ce0;
output   matched_I_13_we0;
output  [17:0] matched_I_13_d0;
output  [7:0] matched_I_13_address1;
output   matched_I_13_ce1;
input  [17:0] matched_I_13_q1;
output  [7:0] matched_I_14_address0;
output   matched_I_14_ce0;
output   matched_I_14_we0;
output  [17:0] matched_I_14_d0;
output  [7:0] matched_I_14_address1;
output   matched_I_14_ce1;
input  [17:0] matched_I_14_q1;
output  [7:0] matched_I_15_address0;
output   matched_I_15_ce0;
output   matched_I_15_we0;
output  [17:0] matched_I_15_d0;
output  [7:0] matched_I_15_address1;
output   matched_I_15_ce1;
input  [17:0] matched_I_15_q1;
output  [7:0] matched_Q_12_address0;
output   matched_Q_12_ce0;
output   matched_Q_12_we0;
output  [17:0] matched_Q_12_d0;
output  [7:0] matched_Q_12_address1;
output   matched_Q_12_ce1;
input  [17:0] matched_Q_12_q1;
output  [7:0] matched_Q_13_address0;
output   matched_Q_13_ce0;
output   matched_Q_13_we0;
output  [17:0] matched_Q_13_d0;
output  [7:0] matched_Q_13_address1;
output   matched_Q_13_ce1;
input  [17:0] matched_Q_13_q1;
output  [7:0] matched_Q_14_address0;
output   matched_Q_14_ce0;
output   matched_Q_14_we0;
output  [17:0] matched_Q_14_d0;
output  [7:0] matched_Q_14_address1;
output   matched_Q_14_ce1;
input  [17:0] matched_Q_14_q1;
output  [7:0] matched_Q_15_address0;
output   matched_Q_15_ce0;
output   matched_Q_15_we0;
output  [17:0] matched_Q_15_d0;
output  [7:0] matched_Q_15_address1;
output   matched_Q_15_ce1;
input  [17:0] matched_Q_15_q1;

reg ap_idle;
reg matched_I_1_ce0;
reg matched_I_1_we0;
reg matched_I_1_ce1;
reg matched_I_2_ce0;
reg matched_I_2_we0;
reg matched_I_2_ce1;
reg matched_I_3_ce0;
reg matched_I_3_we0;
reg matched_I_3_ce1;
reg matched_I_4_ce0;
reg matched_I_4_we0;
reg matched_I_4_ce1;
reg matched_I_5_ce0;
reg matched_I_5_we0;
reg matched_I_5_ce1;
reg matched_I_6_ce0;
reg matched_I_6_we0;
reg matched_I_6_ce1;
reg matched_I_7_ce0;
reg matched_I_7_we0;
reg matched_I_7_ce1;
reg matched_I_8_ce0;
reg matched_I_8_we0;
reg matched_I_8_ce1;
reg matched_I_9_ce0;
reg matched_I_9_we0;
reg matched_I_9_ce1;
reg matched_I_10_ce0;
reg matched_I_10_we0;
reg matched_I_10_ce1;
reg matched_I_11_ce0;
reg matched_I_11_we0;
reg matched_I_11_ce1;
reg matched_I_0_ce0;
reg matched_I_0_we0;
reg matched_I_0_ce1;
reg matched_Q_11_ce0;
reg matched_Q_11_we0;
reg matched_Q_11_ce1;
reg matched_Q_1_ce0;
reg matched_Q_1_we0;
reg matched_Q_1_ce1;
reg matched_Q_0_ce0;
reg matched_Q_0_we0;
reg matched_Q_0_ce1;
reg matched_Q_2_ce0;
reg matched_Q_2_we0;
reg matched_Q_2_ce1;
reg matched_Q_3_ce0;
reg matched_Q_3_we0;
reg matched_Q_3_ce1;
reg matched_Q_4_ce0;
reg matched_Q_4_we0;
reg matched_Q_4_ce1;
reg matched_Q_5_ce0;
reg matched_Q_5_we0;
reg matched_Q_5_ce1;
reg matched_Q_6_ce0;
reg matched_Q_6_we0;
reg matched_Q_6_ce1;
reg matched_Q_7_ce0;
reg matched_Q_7_we0;
reg matched_Q_7_ce1;
reg matched_Q_8_ce0;
reg matched_Q_8_we0;
reg matched_Q_8_ce1;
reg matched_Q_9_ce0;
reg matched_Q_9_we0;
reg matched_Q_9_ce1;
reg matched_Q_10_ce0;
reg matched_Q_10_we0;
reg matched_Q_10_ce1;
reg matched_I_12_ce0;
reg matched_I_12_we0;
reg matched_I_12_ce1;
reg matched_I_13_ce0;
reg matched_I_13_we0;
reg matched_I_13_ce1;
reg matched_I_14_ce0;
reg matched_I_14_we0;
reg matched_I_14_ce1;
reg matched_I_15_ce0;
reg matched_I_15_we0;
reg matched_I_15_ce1;
reg matched_Q_12_ce0;
reg matched_Q_12_we0;
reg matched_Q_12_ce1;
reg matched_Q_13_ce0;
reg matched_Q_13_we0;
reg matched_Q_13_ce1;
reg matched_Q_14_ce0;
reg matched_Q_14_we0;
reg matched_Q_14_ce1;
reg matched_Q_15_ce0;
reg matched_Q_15_we0;
reg matched_Q_15_ce1;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln142_fu_722_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln142_fu_682_p1;
reg   [63:0] zext_ln142_reg_758;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] zext_ln142_reg_758_pp0_iter1_reg;
reg   [7:0] matched_I_1_addr_reg_764;
reg   [7:0] matched_I_1_addr_reg_764_pp0_iter1_reg;
reg   [7:0] matched_Q_1_addr_reg_770;
reg   [7:0] matched_Q_1_addr_reg_770_pp0_iter1_reg;
reg   [7:0] matched_I_2_addr_reg_776;
reg   [7:0] matched_I_2_addr_reg_776_pp0_iter1_reg;
reg   [7:0] matched_Q_2_addr_reg_782;
reg   [7:0] matched_Q_2_addr_reg_782_pp0_iter1_reg;
reg   [7:0] matched_I_3_addr_reg_788;
reg   [7:0] matched_I_3_addr_reg_788_pp0_iter1_reg;
reg   [7:0] matched_Q_3_addr_reg_794;
reg   [7:0] matched_Q_3_addr_reg_794_pp0_iter1_reg;
reg   [7:0] matched_I_4_addr_reg_800;
reg   [7:0] matched_I_4_addr_reg_800_pp0_iter1_reg;
reg   [7:0] matched_Q_4_addr_reg_806;
reg   [7:0] matched_Q_4_addr_reg_806_pp0_iter1_reg;
reg   [7:0] matched_I_5_addr_reg_812;
reg   [7:0] matched_I_5_addr_reg_812_pp0_iter1_reg;
reg   [7:0] matched_Q_5_addr_reg_818;
reg   [7:0] matched_Q_5_addr_reg_818_pp0_iter1_reg;
reg   [7:0] matched_I_6_addr_reg_824;
reg   [7:0] matched_I_6_addr_reg_824_pp0_iter1_reg;
reg   [7:0] matched_Q_6_addr_reg_830;
reg   [7:0] matched_Q_6_addr_reg_830_pp0_iter1_reg;
reg   [7:0] matched_I_7_addr_reg_836;
reg   [7:0] matched_I_7_addr_reg_836_pp0_iter1_reg;
reg   [7:0] matched_Q_7_addr_reg_842;
reg   [7:0] matched_Q_7_addr_reg_842_pp0_iter1_reg;
reg   [7:0] matched_I_8_addr_reg_848;
reg   [7:0] matched_I_8_addr_reg_848_pp0_iter1_reg;
reg   [7:0] matched_Q_8_addr_reg_854;
reg   [7:0] matched_Q_8_addr_reg_854_pp0_iter1_reg;
reg   [7:0] matched_I_9_addr_reg_860;
reg   [7:0] matched_I_9_addr_reg_860_pp0_iter1_reg;
reg   [7:0] matched_Q_9_addr_reg_866;
reg   [7:0] matched_Q_9_addr_reg_866_pp0_iter1_reg;
reg   [7:0] matched_I_10_addr_reg_872;
reg   [7:0] matched_I_10_addr_reg_872_pp0_iter1_reg;
reg   [7:0] matched_Q_10_addr_reg_878;
reg   [7:0] matched_Q_10_addr_reg_878_pp0_iter1_reg;
reg   [7:0] matched_I_11_addr_reg_884;
reg   [7:0] matched_I_11_addr_reg_884_pp0_iter1_reg;
reg   [7:0] matched_Q_11_addr_reg_890;
reg   [7:0] matched_Q_11_addr_reg_890_pp0_iter1_reg;
reg   [0:0] icmp_ln142_reg_896;
reg   [0:0] icmp_ln142_reg_896_pp0_iter1_reg;
reg   [7:0] matched_I_12_addr_reg_900;
reg   [7:0] matched_I_12_addr_reg_900_pp0_iter1_reg;
reg   [7:0] matched_Q_12_addr_reg_906;
reg   [7:0] matched_Q_12_addr_reg_906_pp0_iter1_reg;
reg   [7:0] matched_I_13_addr_reg_912;
reg   [7:0] matched_I_13_addr_reg_912_pp0_iter1_reg;
reg   [7:0] matched_Q_13_addr_reg_918;
reg   [7:0] matched_Q_13_addr_reg_918_pp0_iter1_reg;
reg   [7:0] matched_I_14_addr_reg_924;
reg   [7:0] matched_I_14_addr_reg_924_pp0_iter1_reg;
reg   [7:0] matched_Q_14_addr_reg_930;
reg   [7:0] matched_Q_14_addr_reg_930_pp0_iter1_reg;
reg   [7:0] matched_I_15_addr_reg_936;
reg   [7:0] matched_I_15_addr_reg_936_pp0_iter1_reg;
reg   [7:0] matched_Q_15_addr_reg_942;
reg   [7:0] matched_Q_15_addr_reg_942_pp0_iter1_reg;
reg   [17:0] matched_I_1_load_reg_958;
reg   [17:0] matched_I_2_load_reg_963;
reg   [17:0] matched_I_3_load_reg_968;
reg   [17:0] matched_I_4_load_reg_973;
reg   [17:0] matched_I_5_load_reg_978;
reg   [17:0] matched_I_6_load_reg_983;
reg   [17:0] matched_I_7_load_reg_988;
reg   [17:0] matched_I_8_load_reg_993;
reg   [17:0] matched_I_9_load_reg_998;
reg   [17:0] matched_I_10_load_reg_1003;
reg   [17:0] matched_I_11_load_reg_1008;
reg   [17:0] matched_Q_11_load_reg_1013;
reg   [17:0] matched_Q_1_load_reg_1018;
reg   [17:0] matched_Q_2_load_reg_1023;
reg   [17:0] matched_Q_3_load_reg_1028;
reg   [17:0] matched_Q_4_load_reg_1033;
reg   [17:0] matched_Q_5_load_reg_1038;
reg   [17:0] matched_Q_6_load_reg_1043;
reg   [17:0] matched_Q_7_load_reg_1048;
reg   [17:0] matched_Q_8_load_reg_1053;
reg   [17:0] matched_Q_9_load_reg_1058;
reg   [17:0] matched_Q_10_load_reg_1063;
reg   [17:0] matched_I_12_load_reg_1068;
reg   [17:0] matched_I_13_load_reg_1073;
reg   [17:0] matched_I_14_load_reg_1078;
reg   [17:0] matched_I_15_load_reg_1083;
reg   [17:0] matched_I_0_load_reg_1088;
reg   [17:0] matched_Q_0_load_reg_1093;
reg   [17:0] matched_Q_12_load_reg_1098;
reg   [17:0] matched_Q_13_load_reg_1103;
reg   [17:0] matched_Q_14_load_reg_1108;
reg   [17:0] matched_Q_15_load_reg_1113;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln144_fu_740_p1;
reg   [11:0] i_8_fu_100;
wire   [11:0] add_ln144_fu_728_p2;
wire    ap_loop_init;
reg   [11:0] ap_sig_allocacmp_i;
wire   [7:0] lshr_ln7_fu_672_p4;
wire   [11:0] or_ln144_fu_716_p2;
wire   [7:0] add_ln144_1_fu_734_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

receiver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln142_fu_722_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_8_fu_100 <= add_ln144_fu_728_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_8_fu_100 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln142_reg_896 <= icmp_ln142_fu_722_p2;
        icmp_ln142_reg_896_pp0_iter1_reg <= icmp_ln142_reg_896;
        matched_I_10_addr_reg_872 <= zext_ln142_fu_682_p1;
        matched_I_10_addr_reg_872_pp0_iter1_reg <= matched_I_10_addr_reg_872;
        matched_I_11_addr_reg_884 <= zext_ln142_fu_682_p1;
        matched_I_11_addr_reg_884_pp0_iter1_reg <= matched_I_11_addr_reg_884;
        matched_I_12_addr_reg_900_pp0_iter1_reg <= matched_I_12_addr_reg_900;
        matched_I_13_addr_reg_912_pp0_iter1_reg <= matched_I_13_addr_reg_912;
        matched_I_14_addr_reg_924_pp0_iter1_reg <= matched_I_14_addr_reg_924;
        matched_I_15_addr_reg_936_pp0_iter1_reg <= matched_I_15_addr_reg_936;
        matched_I_1_addr_reg_764 <= zext_ln142_fu_682_p1;
        matched_I_1_addr_reg_764_pp0_iter1_reg <= matched_I_1_addr_reg_764;
        matched_I_2_addr_reg_776 <= zext_ln142_fu_682_p1;
        matched_I_2_addr_reg_776_pp0_iter1_reg <= matched_I_2_addr_reg_776;
        matched_I_3_addr_reg_788 <= zext_ln142_fu_682_p1;
        matched_I_3_addr_reg_788_pp0_iter1_reg <= matched_I_3_addr_reg_788;
        matched_I_4_addr_reg_800 <= zext_ln142_fu_682_p1;
        matched_I_4_addr_reg_800_pp0_iter1_reg <= matched_I_4_addr_reg_800;
        matched_I_5_addr_reg_812 <= zext_ln142_fu_682_p1;
        matched_I_5_addr_reg_812_pp0_iter1_reg <= matched_I_5_addr_reg_812;
        matched_I_6_addr_reg_824 <= zext_ln142_fu_682_p1;
        matched_I_6_addr_reg_824_pp0_iter1_reg <= matched_I_6_addr_reg_824;
        matched_I_7_addr_reg_836 <= zext_ln142_fu_682_p1;
        matched_I_7_addr_reg_836_pp0_iter1_reg <= matched_I_7_addr_reg_836;
        matched_I_8_addr_reg_848 <= zext_ln142_fu_682_p1;
        matched_I_8_addr_reg_848_pp0_iter1_reg <= matched_I_8_addr_reg_848;
        matched_I_9_addr_reg_860 <= zext_ln142_fu_682_p1;
        matched_I_9_addr_reg_860_pp0_iter1_reg <= matched_I_9_addr_reg_860;
        matched_Q_10_addr_reg_878 <= zext_ln142_fu_682_p1;
        matched_Q_10_addr_reg_878_pp0_iter1_reg <= matched_Q_10_addr_reg_878;
        matched_Q_11_addr_reg_890 <= zext_ln142_fu_682_p1;
        matched_Q_11_addr_reg_890_pp0_iter1_reg <= matched_Q_11_addr_reg_890;
        matched_Q_12_addr_reg_906_pp0_iter1_reg <= matched_Q_12_addr_reg_906;
        matched_Q_13_addr_reg_918_pp0_iter1_reg <= matched_Q_13_addr_reg_918;
        matched_Q_14_addr_reg_930_pp0_iter1_reg <= matched_Q_14_addr_reg_930;
        matched_Q_15_addr_reg_942_pp0_iter1_reg <= matched_Q_15_addr_reg_942;
        matched_Q_1_addr_reg_770 <= zext_ln142_fu_682_p1;
        matched_Q_1_addr_reg_770_pp0_iter1_reg <= matched_Q_1_addr_reg_770;
        matched_Q_2_addr_reg_782 <= zext_ln142_fu_682_p1;
        matched_Q_2_addr_reg_782_pp0_iter1_reg <= matched_Q_2_addr_reg_782;
        matched_Q_3_addr_reg_794 <= zext_ln142_fu_682_p1;
        matched_Q_3_addr_reg_794_pp0_iter1_reg <= matched_Q_3_addr_reg_794;
        matched_Q_4_addr_reg_806 <= zext_ln142_fu_682_p1;
        matched_Q_4_addr_reg_806_pp0_iter1_reg <= matched_Q_4_addr_reg_806;
        matched_Q_5_addr_reg_818 <= zext_ln142_fu_682_p1;
        matched_Q_5_addr_reg_818_pp0_iter1_reg <= matched_Q_5_addr_reg_818;
        matched_Q_6_addr_reg_830 <= zext_ln142_fu_682_p1;
        matched_Q_6_addr_reg_830_pp0_iter1_reg <= matched_Q_6_addr_reg_830;
        matched_Q_7_addr_reg_842 <= zext_ln142_fu_682_p1;
        matched_Q_7_addr_reg_842_pp0_iter1_reg <= matched_Q_7_addr_reg_842;
        matched_Q_8_addr_reg_854 <= zext_ln142_fu_682_p1;
        matched_Q_8_addr_reg_854_pp0_iter1_reg <= matched_Q_8_addr_reg_854;
        matched_Q_9_addr_reg_866 <= zext_ln142_fu_682_p1;
        matched_Q_9_addr_reg_866_pp0_iter1_reg <= matched_Q_9_addr_reg_866;
        zext_ln142_reg_758[7 : 0] <= zext_ln142_fu_682_p1[7 : 0];
        zext_ln142_reg_758_pp0_iter1_reg[7 : 0] <= zext_ln142_reg_758[7 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln142_reg_896 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_0_load_reg_1088 <= matched_I_0_q1;
        matched_I_12_load_reg_1068 <= matched_I_12_q1;
        matched_I_13_load_reg_1073 <= matched_I_13_q1;
        matched_I_14_load_reg_1078 <= matched_I_14_q1;
        matched_I_15_load_reg_1083 <= matched_I_15_q1;
        matched_Q_0_load_reg_1093 <= matched_Q_0_q1;
        matched_Q_12_load_reg_1098 <= matched_Q_12_q1;
        matched_Q_13_load_reg_1103 <= matched_Q_13_q1;
        matched_Q_14_load_reg_1108 <= matched_Q_14_q1;
        matched_Q_15_load_reg_1113 <= matched_Q_15_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_10_load_reg_1003 <= matched_I_10_q1;
        matched_I_11_load_reg_1008 <= matched_I_11_q1;
        matched_I_1_load_reg_958 <= matched_I_1_q1;
        matched_I_2_load_reg_963 <= matched_I_2_q1;
        matched_I_3_load_reg_968 <= matched_I_3_q1;
        matched_I_4_load_reg_973 <= matched_I_4_q1;
        matched_I_5_load_reg_978 <= matched_I_5_q1;
        matched_I_6_load_reg_983 <= matched_I_6_q1;
        matched_I_7_load_reg_988 <= matched_I_7_q1;
        matched_I_8_load_reg_993 <= matched_I_8_q1;
        matched_I_9_load_reg_998 <= matched_I_9_q1;
        matched_Q_10_load_reg_1063 <= matched_Q_10_q1;
        matched_Q_11_load_reg_1013 <= matched_Q_11_q1;
        matched_Q_1_load_reg_1018 <= matched_Q_1_q1;
        matched_Q_2_load_reg_1023 <= matched_Q_2_q1;
        matched_Q_3_load_reg_1028 <= matched_Q_3_q1;
        matched_Q_4_load_reg_1033 <= matched_Q_4_q1;
        matched_Q_5_load_reg_1038 <= matched_Q_5_q1;
        matched_Q_6_load_reg_1043 <= matched_Q_6_q1;
        matched_Q_7_load_reg_1048 <= matched_Q_7_q1;
        matched_Q_8_load_reg_1053 <= matched_Q_8_q1;
        matched_Q_9_load_reg_1058 <= matched_Q_9_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln142_fu_722_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_12_addr_reg_900 <= zext_ln142_fu_682_p1;
        matched_I_13_addr_reg_912 <= zext_ln142_fu_682_p1;
        matched_I_14_addr_reg_924 <= zext_ln142_fu_682_p1;
        matched_I_15_addr_reg_936 <= zext_ln142_fu_682_p1;
        matched_Q_12_addr_reg_906 <= zext_ln142_fu_682_p1;
        matched_Q_13_addr_reg_918 <= zext_ln142_fu_682_p1;
        matched_Q_14_addr_reg_930 <= zext_ln142_fu_682_p1;
        matched_Q_15_addr_reg_942 <= zext_ln142_fu_682_p1;
    end
end

always @ (*) begin
    if (((icmp_ln142_fu_722_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter2_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 12'd0;
    end else begin
        ap_sig_allocacmp_i = i_8_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_0_ce0 = 1'b1;
    end else begin
        matched_I_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_0_ce1 = 1'b1;
    end else begin
        matched_I_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_0_we0 = 1'b1;
    end else begin
        matched_I_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_10_ce0 = 1'b1;
    end else begin
        matched_I_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_10_ce1 = 1'b1;
    end else begin
        matched_I_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_10_we0 = 1'b1;
    end else begin
        matched_I_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_11_ce0 = 1'b1;
    end else begin
        matched_I_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_11_ce1 = 1'b1;
    end else begin
        matched_I_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_11_we0 = 1'b1;
    end else begin
        matched_I_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_12_ce0 = 1'b1;
    end else begin
        matched_I_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_12_ce1 = 1'b1;
    end else begin
        matched_I_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_12_we0 = 1'b1;
    end else begin
        matched_I_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_13_ce0 = 1'b1;
    end else begin
        matched_I_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_13_ce1 = 1'b1;
    end else begin
        matched_I_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_13_we0 = 1'b1;
    end else begin
        matched_I_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_14_ce0 = 1'b1;
    end else begin
        matched_I_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_14_ce1 = 1'b1;
    end else begin
        matched_I_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_14_we0 = 1'b1;
    end else begin
        matched_I_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_15_ce0 = 1'b1;
    end else begin
        matched_I_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_15_ce1 = 1'b1;
    end else begin
        matched_I_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_15_we0 = 1'b1;
    end else begin
        matched_I_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_1_ce0 = 1'b1;
    end else begin
        matched_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_1_ce1 = 1'b1;
    end else begin
        matched_I_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_1_we0 = 1'b1;
    end else begin
        matched_I_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_2_ce0 = 1'b1;
    end else begin
        matched_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_2_ce1 = 1'b1;
    end else begin
        matched_I_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_2_we0 = 1'b1;
    end else begin
        matched_I_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_3_ce0 = 1'b1;
    end else begin
        matched_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_3_ce1 = 1'b1;
    end else begin
        matched_I_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_3_we0 = 1'b1;
    end else begin
        matched_I_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_4_ce0 = 1'b1;
    end else begin
        matched_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_4_ce1 = 1'b1;
    end else begin
        matched_I_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_4_we0 = 1'b1;
    end else begin
        matched_I_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_5_ce0 = 1'b1;
    end else begin
        matched_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_5_ce1 = 1'b1;
    end else begin
        matched_I_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_5_we0 = 1'b1;
    end else begin
        matched_I_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_6_ce0 = 1'b1;
    end else begin
        matched_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_6_ce1 = 1'b1;
    end else begin
        matched_I_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_6_we0 = 1'b1;
    end else begin
        matched_I_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_7_ce0 = 1'b1;
    end else begin
        matched_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_7_ce1 = 1'b1;
    end else begin
        matched_I_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_7_we0 = 1'b1;
    end else begin
        matched_I_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_8_ce0 = 1'b1;
    end else begin
        matched_I_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_8_ce1 = 1'b1;
    end else begin
        matched_I_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_8_we0 = 1'b1;
    end else begin
        matched_I_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_9_ce0 = 1'b1;
    end else begin
        matched_I_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_I_9_ce1 = 1'b1;
    end else begin
        matched_I_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_I_9_we0 = 1'b1;
    end else begin
        matched_I_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_0_ce0 = 1'b1;
    end else begin
        matched_Q_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_0_ce1 = 1'b1;
    end else begin
        matched_Q_0_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_0_we0 = 1'b1;
    end else begin
        matched_Q_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_10_ce0 = 1'b1;
    end else begin
        matched_Q_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_10_ce1 = 1'b1;
    end else begin
        matched_Q_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_10_we0 = 1'b1;
    end else begin
        matched_Q_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_11_ce0 = 1'b1;
    end else begin
        matched_Q_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_11_ce1 = 1'b1;
    end else begin
        matched_Q_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_11_we0 = 1'b1;
    end else begin
        matched_Q_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_12_ce0 = 1'b1;
    end else begin
        matched_Q_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_12_ce1 = 1'b1;
    end else begin
        matched_Q_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_12_we0 = 1'b1;
    end else begin
        matched_Q_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_13_ce0 = 1'b1;
    end else begin
        matched_Q_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_13_ce1 = 1'b1;
    end else begin
        matched_Q_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_13_we0 = 1'b1;
    end else begin
        matched_Q_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_14_ce0 = 1'b1;
    end else begin
        matched_Q_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_14_ce1 = 1'b1;
    end else begin
        matched_Q_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_14_we0 = 1'b1;
    end else begin
        matched_Q_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_15_ce0 = 1'b1;
    end else begin
        matched_Q_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_15_ce1 = 1'b1;
    end else begin
        matched_Q_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln142_reg_896_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_15_we0 = 1'b1;
    end else begin
        matched_Q_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_1_ce0 = 1'b1;
    end else begin
        matched_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_1_ce1 = 1'b1;
    end else begin
        matched_Q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_1_we0 = 1'b1;
    end else begin
        matched_Q_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_2_ce0 = 1'b1;
    end else begin
        matched_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_2_ce1 = 1'b1;
    end else begin
        matched_Q_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_2_we0 = 1'b1;
    end else begin
        matched_Q_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_3_ce0 = 1'b1;
    end else begin
        matched_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_3_ce1 = 1'b1;
    end else begin
        matched_Q_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_3_we0 = 1'b1;
    end else begin
        matched_Q_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_4_ce0 = 1'b1;
    end else begin
        matched_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_4_ce1 = 1'b1;
    end else begin
        matched_Q_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_4_we0 = 1'b1;
    end else begin
        matched_Q_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_5_ce0 = 1'b1;
    end else begin
        matched_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_5_ce1 = 1'b1;
    end else begin
        matched_Q_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_5_we0 = 1'b1;
    end else begin
        matched_Q_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_6_ce0 = 1'b1;
    end else begin
        matched_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_6_ce1 = 1'b1;
    end else begin
        matched_Q_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_6_we0 = 1'b1;
    end else begin
        matched_Q_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_7_ce0 = 1'b1;
    end else begin
        matched_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_7_ce1 = 1'b1;
    end else begin
        matched_Q_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_7_we0 = 1'b1;
    end else begin
        matched_Q_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_8_ce0 = 1'b1;
    end else begin
        matched_Q_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_8_ce1 = 1'b1;
    end else begin
        matched_Q_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_8_we0 = 1'b1;
    end else begin
        matched_Q_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_9_ce0 = 1'b1;
    end else begin
        matched_Q_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        matched_Q_9_ce1 = 1'b1;
    end else begin
        matched_Q_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        matched_Q_9_we0 = 1'b1;
    end else begin
        matched_Q_9_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln144_1_fu_734_p2 = (lshr_ln7_fu_672_p4 + 8'd1);

assign add_ln144_fu_728_p2 = (ap_sig_allocacmp_i + 12'd16);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln142_fu_722_p2 = ((or_ln144_fu_716_p2 < 12'd3915) ? 1'b1 : 1'b0);

assign lshr_ln7_fu_672_p4 = {{ap_sig_allocacmp_i[11:4]}};

assign matched_I_0_address0 = zext_ln142_reg_758_pp0_iter1_reg;

assign matched_I_0_address1 = zext_ln144_fu_740_p1;

assign matched_I_0_d0 = matched_I_1_load_reg_958;

assign matched_I_10_address0 = matched_I_10_addr_reg_872_pp0_iter1_reg;

assign matched_I_10_address1 = zext_ln142_fu_682_p1;

assign matched_I_10_d0 = matched_I_11_load_reg_1008;

assign matched_I_11_address0 = matched_I_11_addr_reg_884_pp0_iter1_reg;

assign matched_I_11_address1 = zext_ln142_fu_682_p1;

assign matched_I_11_d0 = matched_I_12_load_reg_1068;

assign matched_I_12_address0 = matched_I_12_addr_reg_900_pp0_iter1_reg;

assign matched_I_12_address1 = zext_ln142_fu_682_p1;

assign matched_I_12_d0 = matched_I_13_load_reg_1073;

assign matched_I_13_address0 = matched_I_13_addr_reg_912_pp0_iter1_reg;

assign matched_I_13_address1 = zext_ln142_fu_682_p1;

assign matched_I_13_d0 = matched_I_14_load_reg_1078;

assign matched_I_14_address0 = matched_I_14_addr_reg_924_pp0_iter1_reg;

assign matched_I_14_address1 = zext_ln142_fu_682_p1;

assign matched_I_14_d0 = matched_I_15_load_reg_1083;

assign matched_I_15_address0 = matched_I_15_addr_reg_936_pp0_iter1_reg;

assign matched_I_15_address1 = zext_ln142_fu_682_p1;

assign matched_I_15_d0 = matched_I_0_load_reg_1088;

assign matched_I_1_address0 = matched_I_1_addr_reg_764_pp0_iter1_reg;

assign matched_I_1_address1 = zext_ln142_fu_682_p1;

assign matched_I_1_d0 = matched_I_2_load_reg_963;

assign matched_I_2_address0 = matched_I_2_addr_reg_776_pp0_iter1_reg;

assign matched_I_2_address1 = zext_ln142_fu_682_p1;

assign matched_I_2_d0 = matched_I_3_load_reg_968;

assign matched_I_3_address0 = matched_I_3_addr_reg_788_pp0_iter1_reg;

assign matched_I_3_address1 = zext_ln142_fu_682_p1;

assign matched_I_3_d0 = matched_I_4_load_reg_973;

assign matched_I_4_address0 = matched_I_4_addr_reg_800_pp0_iter1_reg;

assign matched_I_4_address1 = zext_ln142_fu_682_p1;

assign matched_I_4_d0 = matched_I_5_load_reg_978;

assign matched_I_5_address0 = matched_I_5_addr_reg_812_pp0_iter1_reg;

assign matched_I_5_address1 = zext_ln142_fu_682_p1;

assign matched_I_5_d0 = matched_I_6_load_reg_983;

assign matched_I_6_address0 = matched_I_6_addr_reg_824_pp0_iter1_reg;

assign matched_I_6_address1 = zext_ln142_fu_682_p1;

assign matched_I_6_d0 = matched_I_7_load_reg_988;

assign matched_I_7_address0 = matched_I_7_addr_reg_836_pp0_iter1_reg;

assign matched_I_7_address1 = zext_ln142_fu_682_p1;

assign matched_I_7_d0 = matched_I_8_load_reg_993;

assign matched_I_8_address0 = matched_I_8_addr_reg_848_pp0_iter1_reg;

assign matched_I_8_address1 = zext_ln142_fu_682_p1;

assign matched_I_8_d0 = matched_I_9_load_reg_998;

assign matched_I_9_address0 = matched_I_9_addr_reg_860_pp0_iter1_reg;

assign matched_I_9_address1 = zext_ln142_fu_682_p1;

assign matched_I_9_d0 = matched_I_10_load_reg_1003;

assign matched_Q_0_address0 = zext_ln142_reg_758_pp0_iter1_reg;

assign matched_Q_0_address1 = zext_ln144_fu_740_p1;

assign matched_Q_0_d0 = matched_Q_1_load_reg_1018;

assign matched_Q_10_address0 = matched_Q_10_addr_reg_878_pp0_iter1_reg;

assign matched_Q_10_address1 = zext_ln142_fu_682_p1;

assign matched_Q_10_d0 = matched_Q_11_load_reg_1013;

assign matched_Q_11_address0 = matched_Q_11_addr_reg_890_pp0_iter1_reg;

assign matched_Q_11_address1 = zext_ln142_fu_682_p1;

assign matched_Q_11_d0 = matched_Q_12_load_reg_1098;

assign matched_Q_12_address0 = matched_Q_12_addr_reg_906_pp0_iter1_reg;

assign matched_Q_12_address1 = zext_ln142_fu_682_p1;

assign matched_Q_12_d0 = matched_Q_13_load_reg_1103;

assign matched_Q_13_address0 = matched_Q_13_addr_reg_918_pp0_iter1_reg;

assign matched_Q_13_address1 = zext_ln142_fu_682_p1;

assign matched_Q_13_d0 = matched_Q_14_load_reg_1108;

assign matched_Q_14_address0 = matched_Q_14_addr_reg_930_pp0_iter1_reg;

assign matched_Q_14_address1 = zext_ln142_fu_682_p1;

assign matched_Q_14_d0 = matched_Q_15_load_reg_1113;

assign matched_Q_15_address0 = matched_Q_15_addr_reg_942_pp0_iter1_reg;

assign matched_Q_15_address1 = zext_ln142_fu_682_p1;

assign matched_Q_15_d0 = matched_Q_0_load_reg_1093;

assign matched_Q_1_address0 = matched_Q_1_addr_reg_770_pp0_iter1_reg;

assign matched_Q_1_address1 = zext_ln142_fu_682_p1;

assign matched_Q_1_d0 = matched_Q_2_load_reg_1023;

assign matched_Q_2_address0 = matched_Q_2_addr_reg_782_pp0_iter1_reg;

assign matched_Q_2_address1 = zext_ln142_fu_682_p1;

assign matched_Q_2_d0 = matched_Q_3_load_reg_1028;

assign matched_Q_3_address0 = matched_Q_3_addr_reg_794_pp0_iter1_reg;

assign matched_Q_3_address1 = zext_ln142_fu_682_p1;

assign matched_Q_3_d0 = matched_Q_4_load_reg_1033;

assign matched_Q_4_address0 = matched_Q_4_addr_reg_806_pp0_iter1_reg;

assign matched_Q_4_address1 = zext_ln142_fu_682_p1;

assign matched_Q_4_d0 = matched_Q_5_load_reg_1038;

assign matched_Q_5_address0 = matched_Q_5_addr_reg_818_pp0_iter1_reg;

assign matched_Q_5_address1 = zext_ln142_fu_682_p1;

assign matched_Q_5_d0 = matched_Q_6_load_reg_1043;

assign matched_Q_6_address0 = matched_Q_6_addr_reg_830_pp0_iter1_reg;

assign matched_Q_6_address1 = zext_ln142_fu_682_p1;

assign matched_Q_6_d0 = matched_Q_7_load_reg_1048;

assign matched_Q_7_address0 = matched_Q_7_addr_reg_842_pp0_iter1_reg;

assign matched_Q_7_address1 = zext_ln142_fu_682_p1;

assign matched_Q_7_d0 = matched_Q_8_load_reg_1053;

assign matched_Q_8_address0 = matched_Q_8_addr_reg_854_pp0_iter1_reg;

assign matched_Q_8_address1 = zext_ln142_fu_682_p1;

assign matched_Q_8_d0 = matched_Q_9_load_reg_1058;

assign matched_Q_9_address0 = matched_Q_9_addr_reg_866_pp0_iter1_reg;

assign matched_Q_9_address1 = zext_ln142_fu_682_p1;

assign matched_Q_9_d0 = matched_Q_10_load_reg_1063;

assign or_ln144_fu_716_p2 = (ap_sig_allocacmp_i | 12'd11);

assign zext_ln142_fu_682_p1 = lshr_ln7_fu_672_p4;

assign zext_ln144_fu_740_p1 = add_ln144_1_fu_734_p2;

always @ (posedge ap_clk) begin
    zext_ln142_reg_758[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
    zext_ln142_reg_758_pp0_iter1_reg[63:8] <= 56'b00000000000000000000000000000000000000000000000000000000;
end

endmodule //receiver_receiver_Pipeline_VITIS_LOOP_142_9
