// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module receiver_receiver_Pipeline_VITIS_LOOP_84_4 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        filt_I_address0,
        filt_I_ce0,
        filt_I_q0,
        filt_I_address1,
        filt_I_ce1,
        filt_I_q1,
        filt_I_1_address0,
        filt_I_1_ce0,
        filt_I_1_q0,
        filt_I_1_address1,
        filt_I_1_ce1,
        filt_I_1_q1,
        filt_1_I_address0,
        filt_1_I_ce0,
        filt_1_I_we0,
        filt_1_I_d0,
        filt_Q_address0,
        filt_Q_ce0,
        filt_Q_q0,
        filt_Q_address1,
        filt_Q_ce1,
        filt_Q_q1,
        filt_Q_1_address0,
        filt_Q_1_ce0,
        filt_Q_1_q0,
        filt_Q_1_address1,
        filt_Q_1_ce1,
        filt_Q_1_q1,
        filt_1_Q_address0,
        filt_1_Q_ce0,
        filt_1_Q_we0,
        filt_1_Q_d0,
        filt_I_2_address0,
        filt_I_2_ce0,
        filt_I_2_q0,
        filt_I_2_address1,
        filt_I_2_ce1,
        filt_I_2_q1,
        filt_I_3_address0,
        filt_I_3_ce0,
        filt_I_3_q0,
        filt_I_3_address1,
        filt_I_3_ce1,
        filt_I_3_q1,
        filt_1_I_1_address0,
        filt_1_I_1_ce0,
        filt_1_I_1_we0,
        filt_1_I_1_d0,
        filt_Q_2_address0,
        filt_Q_2_ce0,
        filt_Q_2_q0,
        filt_Q_2_address1,
        filt_Q_2_ce1,
        filt_Q_2_q1,
        filt_Q_3_address0,
        filt_Q_3_ce0,
        filt_Q_3_q0,
        filt_Q_3_address1,
        filt_Q_3_ce1,
        filt_Q_3_q1,
        filt_1_Q_1_address0,
        filt_1_Q_1_ce0,
        filt_1_Q_1_we0,
        filt_1_Q_1_d0,
        filt_I_4_address0,
        filt_I_4_ce0,
        filt_I_4_q0,
        filt_I_4_address1,
        filt_I_4_ce1,
        filt_I_4_q1,
        filt_I_5_address0,
        filt_I_5_ce0,
        filt_I_5_q0,
        filt_I_5_address1,
        filt_I_5_ce1,
        filt_I_5_q1,
        filt_1_I_2_address0,
        filt_1_I_2_ce0,
        filt_1_I_2_we0,
        filt_1_I_2_d0,
        filt_Q_4_address0,
        filt_Q_4_ce0,
        filt_Q_4_q0,
        filt_Q_4_address1,
        filt_Q_4_ce1,
        filt_Q_4_q1,
        filt_Q_5_address0,
        filt_Q_5_ce0,
        filt_Q_5_q0,
        filt_Q_5_address1,
        filt_Q_5_ce1,
        filt_Q_5_q1,
        filt_1_Q_2_address0,
        filt_1_Q_2_ce0,
        filt_1_Q_2_we0,
        filt_1_Q_2_d0,
        filt_I_6_address0,
        filt_I_6_ce0,
        filt_I_6_q0,
        filt_I_6_address1,
        filt_I_6_ce1,
        filt_I_6_q1,
        filt_I_7_address0,
        filt_I_7_ce0,
        filt_I_7_q0,
        filt_I_7_address1,
        filt_I_7_ce1,
        filt_I_7_q1,
        filt_1_I_3_address0,
        filt_1_I_3_ce0,
        filt_1_I_3_we0,
        filt_1_I_3_d0,
        filt_Q_6_address0,
        filt_Q_6_ce0,
        filt_Q_6_q0,
        filt_Q_6_address1,
        filt_Q_6_ce1,
        filt_Q_6_q1,
        filt_Q_7_address0,
        filt_Q_7_ce0,
        filt_Q_7_q0,
        filt_Q_7_address1,
        filt_Q_7_ce1,
        filt_Q_7_q1,
        filt_1_Q_3_address0,
        filt_1_Q_3_ce0,
        filt_1_Q_3_we0,
        filt_1_Q_3_d0,
        filt_1_I_4_address0,
        filt_1_I_4_ce0,
        filt_1_I_4_we0,
        filt_1_I_4_d0,
        filt_1_Q_4_address0,
        filt_1_Q_4_ce0,
        filt_1_Q_4_we0,
        filt_1_Q_4_d0,
        filt_1_I_5_address0,
        filt_1_I_5_ce0,
        filt_1_I_5_we0,
        filt_1_I_5_d0,
        filt_1_Q_5_address0,
        filt_1_Q_5_ce0,
        filt_1_Q_5_we0,
        filt_1_Q_5_d0,
        filt_1_I_6_address0,
        filt_1_I_6_ce0,
        filt_1_I_6_we0,
        filt_1_I_6_d0,
        filt_1_Q_6_address0,
        filt_1_Q_6_ce0,
        filt_1_Q_6_we0,
        filt_1_Q_6_d0,
        filt_1_I_7_address0,
        filt_1_I_7_ce0,
        filt_1_I_7_we0,
        filt_1_I_7_d0,
        filt_1_Q_7_address0,
        filt_1_Q_7_ce0,
        filt_1_Q_7_we0,
        filt_1_Q_7_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [4:0] filt_I_address0;
output   filt_I_ce0;
input  [16:0] filt_I_q0;
output  [4:0] filt_I_address1;
output   filt_I_ce1;
input  [16:0] filt_I_q1;
output  [4:0] filt_I_1_address0;
output   filt_I_1_ce0;
input  [16:0] filt_I_1_q0;
output  [4:0] filt_I_1_address1;
output   filt_I_1_ce1;
input  [16:0] filt_I_1_q1;
output  [3:0] filt_1_I_address0;
output   filt_1_I_ce0;
output   filt_1_I_we0;
output  [17:0] filt_1_I_d0;
output  [4:0] filt_Q_address0;
output   filt_Q_ce0;
input  [16:0] filt_Q_q0;
output  [4:0] filt_Q_address1;
output   filt_Q_ce1;
input  [16:0] filt_Q_q1;
output  [4:0] filt_Q_1_address0;
output   filt_Q_1_ce0;
input  [16:0] filt_Q_1_q0;
output  [4:0] filt_Q_1_address1;
output   filt_Q_1_ce1;
input  [16:0] filt_Q_1_q1;
output  [3:0] filt_1_Q_address0;
output   filt_1_Q_ce0;
output   filt_1_Q_we0;
output  [17:0] filt_1_Q_d0;
output  [4:0] filt_I_2_address0;
output   filt_I_2_ce0;
input  [16:0] filt_I_2_q0;
output  [4:0] filt_I_2_address1;
output   filt_I_2_ce1;
input  [16:0] filt_I_2_q1;
output  [4:0] filt_I_3_address0;
output   filt_I_3_ce0;
input  [16:0] filt_I_3_q0;
output  [4:0] filt_I_3_address1;
output   filt_I_3_ce1;
input  [16:0] filt_I_3_q1;
output  [3:0] filt_1_I_1_address0;
output   filt_1_I_1_ce0;
output   filt_1_I_1_we0;
output  [17:0] filt_1_I_1_d0;
output  [4:0] filt_Q_2_address0;
output   filt_Q_2_ce0;
input  [16:0] filt_Q_2_q0;
output  [4:0] filt_Q_2_address1;
output   filt_Q_2_ce1;
input  [16:0] filt_Q_2_q1;
output  [4:0] filt_Q_3_address0;
output   filt_Q_3_ce0;
input  [16:0] filt_Q_3_q0;
output  [4:0] filt_Q_3_address1;
output   filt_Q_3_ce1;
input  [16:0] filt_Q_3_q1;
output  [3:0] filt_1_Q_1_address0;
output   filt_1_Q_1_ce0;
output   filt_1_Q_1_we0;
output  [17:0] filt_1_Q_1_d0;
output  [4:0] filt_I_4_address0;
output   filt_I_4_ce0;
input  [16:0] filt_I_4_q0;
output  [4:0] filt_I_4_address1;
output   filt_I_4_ce1;
input  [16:0] filt_I_4_q1;
output  [4:0] filt_I_5_address0;
output   filt_I_5_ce0;
input  [16:0] filt_I_5_q0;
output  [4:0] filt_I_5_address1;
output   filt_I_5_ce1;
input  [16:0] filt_I_5_q1;
output  [3:0] filt_1_I_2_address0;
output   filt_1_I_2_ce0;
output   filt_1_I_2_we0;
output  [17:0] filt_1_I_2_d0;
output  [4:0] filt_Q_4_address0;
output   filt_Q_4_ce0;
input  [16:0] filt_Q_4_q0;
output  [4:0] filt_Q_4_address1;
output   filt_Q_4_ce1;
input  [16:0] filt_Q_4_q1;
output  [4:0] filt_Q_5_address0;
output   filt_Q_5_ce0;
input  [16:0] filt_Q_5_q0;
output  [4:0] filt_Q_5_address1;
output   filt_Q_5_ce1;
input  [16:0] filt_Q_5_q1;
output  [3:0] filt_1_Q_2_address0;
output   filt_1_Q_2_ce0;
output   filt_1_Q_2_we0;
output  [17:0] filt_1_Q_2_d0;
output  [4:0] filt_I_6_address0;
output   filt_I_6_ce0;
input  [16:0] filt_I_6_q0;
output  [4:0] filt_I_6_address1;
output   filt_I_6_ce1;
input  [16:0] filt_I_6_q1;
output  [4:0] filt_I_7_address0;
output   filt_I_7_ce0;
input  [16:0] filt_I_7_q0;
output  [4:0] filt_I_7_address1;
output   filt_I_7_ce1;
input  [16:0] filt_I_7_q1;
output  [3:0] filt_1_I_3_address0;
output   filt_1_I_3_ce0;
output   filt_1_I_3_we0;
output  [17:0] filt_1_I_3_d0;
output  [4:0] filt_Q_6_address0;
output   filt_Q_6_ce0;
input  [16:0] filt_Q_6_q0;
output  [4:0] filt_Q_6_address1;
output   filt_Q_6_ce1;
input  [16:0] filt_Q_6_q1;
output  [4:0] filt_Q_7_address0;
output   filt_Q_7_ce0;
input  [16:0] filt_Q_7_q0;
output  [4:0] filt_Q_7_address1;
output   filt_Q_7_ce1;
input  [16:0] filt_Q_7_q1;
output  [3:0] filt_1_Q_3_address0;
output   filt_1_Q_3_ce0;
output   filt_1_Q_3_we0;
output  [17:0] filt_1_Q_3_d0;
output  [3:0] filt_1_I_4_address0;
output   filt_1_I_4_ce0;
output   filt_1_I_4_we0;
output  [17:0] filt_1_I_4_d0;
output  [3:0] filt_1_Q_4_address0;
output   filt_1_Q_4_ce0;
output   filt_1_Q_4_we0;
output  [17:0] filt_1_Q_4_d0;
output  [3:0] filt_1_I_5_address0;
output   filt_1_I_5_ce0;
output   filt_1_I_5_we0;
output  [17:0] filt_1_I_5_d0;
output  [3:0] filt_1_Q_5_address0;
output   filt_1_Q_5_ce0;
output   filt_1_Q_5_we0;
output  [17:0] filt_1_Q_5_d0;
output  [3:0] filt_1_I_6_address0;
output   filt_1_I_6_ce0;
output   filt_1_I_6_we0;
output  [17:0] filt_1_I_6_d0;
output  [3:0] filt_1_Q_6_address0;
output   filt_1_Q_6_ce0;
output   filt_1_Q_6_we0;
output  [17:0] filt_1_Q_6_d0;
output  [3:0] filt_1_I_7_address0;
output   filt_1_I_7_ce0;
output   filt_1_I_7_we0;
output  [17:0] filt_1_I_7_d0;
output  [3:0] filt_1_Q_7_address0;
output   filt_1_Q_7_ce0;
output   filt_1_Q_7_we0;
output  [17:0] filt_1_Q_7_d0;

reg ap_idle;
reg filt_I_ce0;
reg filt_I_ce1;
reg filt_I_1_ce0;
reg filt_I_1_ce1;
reg filt_1_I_ce0;
reg filt_1_I_we0;
reg filt_Q_ce0;
reg filt_Q_ce1;
reg filt_Q_1_ce0;
reg filt_Q_1_ce1;
reg filt_1_Q_ce0;
reg filt_1_Q_we0;
reg filt_I_2_ce0;
reg filt_I_2_ce1;
reg filt_I_3_ce0;
reg filt_I_3_ce1;
reg filt_1_I_1_ce0;
reg filt_1_I_1_we0;
reg filt_Q_2_ce0;
reg filt_Q_2_ce1;
reg filt_Q_3_ce0;
reg filt_Q_3_ce1;
reg filt_1_Q_1_ce0;
reg filt_1_Q_1_we0;
reg filt_I_4_ce0;
reg filt_I_4_ce1;
reg filt_I_5_ce0;
reg filt_I_5_ce1;
reg filt_1_I_2_ce0;
reg filt_1_I_2_we0;
reg filt_Q_4_ce0;
reg filt_Q_4_ce1;
reg filt_Q_5_ce0;
reg filt_Q_5_ce1;
reg filt_1_Q_2_ce0;
reg filt_1_Q_2_we0;
reg filt_I_6_ce0;
reg filt_I_6_ce1;
reg filt_I_7_ce0;
reg filt_I_7_ce1;
reg filt_1_I_3_ce0;
reg filt_1_I_3_we0;
reg filt_Q_6_ce0;
reg filt_Q_6_ce1;
reg filt_Q_7_ce0;
reg filt_Q_7_ce1;
reg filt_1_Q_3_ce0;
reg filt_1_Q_3_we0;
reg filt_1_I_4_ce0;
reg filt_1_I_4_we0;
reg filt_1_Q_4_ce0;
reg filt_1_Q_4_we0;
reg filt_1_I_5_ce0;
reg filt_1_I_5_we0;
reg filt_1_Q_5_ce0;
reg filt_1_Q_5_we0;
reg filt_1_I_6_ce0;
reg filt_1_I_6_we0;
reg filt_1_Q_6_ce0;
reg filt_1_Q_6_we0;
reg filt_1_I_7_ce0;
reg filt_1_I_7_we0;
reg filt_1_Q_7_ce0;
reg filt_1_Q_7_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln84_fu_722_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [3:0] lshr_ln5_reg_1069;
reg   [3:0] lshr_ln5_reg_1069_pp0_iter1_reg;
wire   [17:0] add_ln86_fu_813_p2;
reg   [17:0] add_ln86_reg_1224;
wire   [17:0] add_ln86_1_fu_827_p2;
reg   [17:0] add_ln86_1_reg_1229;
wire   [17:0] add_ln86_2_fu_841_p2;
reg   [17:0] add_ln86_2_reg_1234;
wire   [17:0] add_ln86_3_fu_855_p2;
reg   [17:0] add_ln86_3_reg_1239;
wire   [17:0] add_ln86_4_fu_869_p2;
reg   [17:0] add_ln86_4_reg_1244;
wire   [17:0] add_ln86_5_fu_883_p2;
reg   [17:0] add_ln86_5_reg_1249;
wire   [17:0] add_ln86_6_fu_897_p2;
reg   [17:0] add_ln86_6_reg_1254;
wire   [17:0] add_ln86_7_fu_911_p2;
reg   [17:0] add_ln86_7_reg_1259;
wire   [17:0] add_ln87_fu_929_p2;
reg   [17:0] add_ln87_reg_1264;
wire   [17:0] add_ln87_1_fu_939_p2;
reg   [17:0] add_ln87_1_reg_1269;
wire   [17:0] add_ln87_2_fu_957_p2;
reg   [17:0] add_ln87_2_reg_1274;
wire   [17:0] add_ln87_3_fu_967_p2;
reg   [17:0] add_ln87_3_reg_1279;
wire   [17:0] add_ln87_4_fu_985_p2;
reg   [17:0] add_ln87_4_reg_1284;
wire   [17:0] add_ln87_5_fu_995_p2;
reg   [17:0] add_ln87_5_reg_1289;
wire   [17:0] add_ln87_6_fu_1013_p2;
reg   [17:0] add_ln87_6_reg_1294;
wire   [17:0] add_ln87_7_fu_1023_p2;
reg   [17:0] add_ln87_7_reg_1299;
wire   [63:0] zext_ln84_fu_738_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln86_1_fu_774_p1;
wire   [63:0] zext_ln86_fu_1029_p1;
reg   [7:0] i_fu_102;
wire   [7:0] add_ln84_fu_794_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_2;
wire   [4:0] lshr_ln4_fu_728_p4;
wire   [4:0] or_ln86_fu_768_p2;
wire  signed [17:0] sext_ln86_1_fu_809_p1;
wire  signed [17:0] sext_ln86_fu_805_p1;
wire  signed [17:0] sext_ln86_3_fu_823_p1;
wire  signed [17:0] sext_ln86_2_fu_819_p1;
wire  signed [17:0] sext_ln86_5_fu_837_p1;
wire  signed [17:0] sext_ln86_4_fu_833_p1;
wire  signed [17:0] sext_ln86_7_fu_851_p1;
wire  signed [17:0] sext_ln86_6_fu_847_p1;
wire  signed [17:0] sext_ln86_9_fu_865_p1;
wire  signed [17:0] sext_ln86_8_fu_861_p1;
wire  signed [17:0] sext_ln86_11_fu_879_p1;
wire  signed [17:0] sext_ln86_10_fu_875_p1;
wire  signed [17:0] sext_ln86_13_fu_893_p1;
wire  signed [17:0] sext_ln86_12_fu_889_p1;
wire  signed [17:0] sext_ln86_15_fu_907_p1;
wire  signed [17:0] sext_ln86_14_fu_903_p1;
wire  signed [17:0] sext_ln87_2_fu_925_p1;
wire  signed [17:0] sext_ln87_fu_917_p1;
wire  signed [17:0] sext_ln87_3_fu_935_p1;
wire  signed [17:0] sext_ln87_1_fu_921_p1;
wire  signed [17:0] sext_ln87_6_fu_953_p1;
wire  signed [17:0] sext_ln87_4_fu_945_p1;
wire  signed [17:0] sext_ln87_7_fu_963_p1;
wire  signed [17:0] sext_ln87_5_fu_949_p1;
wire  signed [17:0] sext_ln87_10_fu_981_p1;
wire  signed [17:0] sext_ln87_8_fu_973_p1;
wire  signed [17:0] sext_ln87_11_fu_991_p1;
wire  signed [17:0] sext_ln87_9_fu_977_p1;
wire  signed [17:0] sext_ln87_14_fu_1009_p1;
wire  signed [17:0] sext_ln87_12_fu_1001_p1;
wire  signed [17:0] sext_ln87_15_fu_1019_p1;
wire  signed [17:0] sext_ln87_13_fu_1005_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

receiver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln84_fu_722_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_102 <= add_ln84_fu_794_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_102 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln86_1_reg_1229 <= add_ln86_1_fu_827_p2;
        add_ln86_2_reg_1234 <= add_ln86_2_fu_841_p2;
        add_ln86_3_reg_1239 <= add_ln86_3_fu_855_p2;
        add_ln86_4_reg_1244 <= add_ln86_4_fu_869_p2;
        add_ln86_5_reg_1249 <= add_ln86_5_fu_883_p2;
        add_ln86_6_reg_1254 <= add_ln86_6_fu_897_p2;
        add_ln86_7_reg_1259 <= add_ln86_7_fu_911_p2;
        add_ln86_reg_1224 <= add_ln86_fu_813_p2;
        add_ln87_1_reg_1269 <= add_ln87_1_fu_939_p2;
        add_ln87_2_reg_1274 <= add_ln87_2_fu_957_p2;
        add_ln87_3_reg_1279 <= add_ln87_3_fu_967_p2;
        add_ln87_4_reg_1284 <= add_ln87_4_fu_985_p2;
        add_ln87_5_reg_1289 <= add_ln87_5_fu_995_p2;
        add_ln87_6_reg_1294 <= add_ln87_6_fu_1013_p2;
        add_ln87_7_reg_1299 <= add_ln87_7_fu_1023_p2;
        add_ln87_reg_1264 <= add_ln87_fu_929_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        lshr_ln5_reg_1069_pp0_iter1_reg <= lshr_ln5_reg_1069;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln84_fu_722_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        lshr_ln5_reg_1069 <= {{ap_sig_allocacmp_i_2[7:4]}};
    end
end

always @ (*) begin
    if (((icmp_ln84_fu_722_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_102;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_1_ce0 = 1'b1;
    end else begin
        filt_1_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_1_we0 = 1'b1;
    end else begin
        filt_1_I_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_2_ce0 = 1'b1;
    end else begin
        filt_1_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_2_we0 = 1'b1;
    end else begin
        filt_1_I_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_3_ce0 = 1'b1;
    end else begin
        filt_1_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_3_we0 = 1'b1;
    end else begin
        filt_1_I_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_4_ce0 = 1'b1;
    end else begin
        filt_1_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_4_we0 = 1'b1;
    end else begin
        filt_1_I_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_5_ce0 = 1'b1;
    end else begin
        filt_1_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_5_we0 = 1'b1;
    end else begin
        filt_1_I_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_6_ce0 = 1'b1;
    end else begin
        filt_1_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_6_we0 = 1'b1;
    end else begin
        filt_1_I_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_7_ce0 = 1'b1;
    end else begin
        filt_1_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_7_we0 = 1'b1;
    end else begin
        filt_1_I_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_ce0 = 1'b1;
    end else begin
        filt_1_I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_I_we0 = 1'b1;
    end else begin
        filt_1_I_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_1_ce0 = 1'b1;
    end else begin
        filt_1_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_1_we0 = 1'b1;
    end else begin
        filt_1_Q_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_2_ce0 = 1'b1;
    end else begin
        filt_1_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_2_we0 = 1'b1;
    end else begin
        filt_1_Q_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_3_ce0 = 1'b1;
    end else begin
        filt_1_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_3_we0 = 1'b1;
    end else begin
        filt_1_Q_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_4_ce0 = 1'b1;
    end else begin
        filt_1_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_4_we0 = 1'b1;
    end else begin
        filt_1_Q_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_5_ce0 = 1'b1;
    end else begin
        filt_1_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_5_we0 = 1'b1;
    end else begin
        filt_1_Q_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_6_ce0 = 1'b1;
    end else begin
        filt_1_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_6_we0 = 1'b1;
    end else begin
        filt_1_Q_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_7_ce0 = 1'b1;
    end else begin
        filt_1_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_7_we0 = 1'b1;
    end else begin
        filt_1_Q_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_ce0 = 1'b1;
    end else begin
        filt_1_Q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        filt_1_Q_we0 = 1'b1;
    end else begin
        filt_1_Q_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_1_ce0 = 1'b1;
    end else begin
        filt_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_1_ce1 = 1'b1;
    end else begin
        filt_I_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_2_ce0 = 1'b1;
    end else begin
        filt_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_2_ce1 = 1'b1;
    end else begin
        filt_I_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_3_ce0 = 1'b1;
    end else begin
        filt_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_3_ce1 = 1'b1;
    end else begin
        filt_I_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_4_ce0 = 1'b1;
    end else begin
        filt_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_4_ce1 = 1'b1;
    end else begin
        filt_I_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_5_ce0 = 1'b1;
    end else begin
        filt_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_5_ce1 = 1'b1;
    end else begin
        filt_I_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_6_ce0 = 1'b1;
    end else begin
        filt_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_6_ce1 = 1'b1;
    end else begin
        filt_I_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_7_ce0 = 1'b1;
    end else begin
        filt_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_7_ce1 = 1'b1;
    end else begin
        filt_I_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_ce0 = 1'b1;
    end else begin
        filt_I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_I_ce1 = 1'b1;
    end else begin
        filt_I_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_1_ce0 = 1'b1;
    end else begin
        filt_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_1_ce1 = 1'b1;
    end else begin
        filt_Q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_2_ce0 = 1'b1;
    end else begin
        filt_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_2_ce1 = 1'b1;
    end else begin
        filt_Q_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_3_ce0 = 1'b1;
    end else begin
        filt_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_3_ce1 = 1'b1;
    end else begin
        filt_Q_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_4_ce0 = 1'b1;
    end else begin
        filt_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_4_ce1 = 1'b1;
    end else begin
        filt_Q_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_5_ce0 = 1'b1;
    end else begin
        filt_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_5_ce1 = 1'b1;
    end else begin
        filt_Q_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_6_ce0 = 1'b1;
    end else begin
        filt_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_6_ce1 = 1'b1;
    end else begin
        filt_Q_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_7_ce0 = 1'b1;
    end else begin
        filt_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_7_ce1 = 1'b1;
    end else begin
        filt_Q_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_ce0 = 1'b1;
    end else begin
        filt_Q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        filt_Q_ce1 = 1'b1;
    end else begin
        filt_Q_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln84_fu_794_p2 = (ap_sig_allocacmp_i_2 + 8'd16);

assign add_ln86_1_fu_827_p2 = ($signed(sext_ln86_3_fu_823_p1) + $signed(sext_ln86_2_fu_819_p1));

assign add_ln86_2_fu_841_p2 = ($signed(sext_ln86_5_fu_837_p1) + $signed(sext_ln86_4_fu_833_p1));

assign add_ln86_3_fu_855_p2 = ($signed(sext_ln86_7_fu_851_p1) + $signed(sext_ln86_6_fu_847_p1));

assign add_ln86_4_fu_869_p2 = ($signed(sext_ln86_9_fu_865_p1) + $signed(sext_ln86_8_fu_861_p1));

assign add_ln86_5_fu_883_p2 = ($signed(sext_ln86_11_fu_879_p1) + $signed(sext_ln86_10_fu_875_p1));

assign add_ln86_6_fu_897_p2 = ($signed(sext_ln86_13_fu_893_p1) + $signed(sext_ln86_12_fu_889_p1));

assign add_ln86_7_fu_911_p2 = ($signed(sext_ln86_15_fu_907_p1) + $signed(sext_ln86_14_fu_903_p1));

assign add_ln86_fu_813_p2 = ($signed(sext_ln86_1_fu_809_p1) + $signed(sext_ln86_fu_805_p1));

assign add_ln87_1_fu_939_p2 = ($signed(sext_ln87_3_fu_935_p1) + $signed(sext_ln87_1_fu_921_p1));

assign add_ln87_2_fu_957_p2 = ($signed(sext_ln87_6_fu_953_p1) + $signed(sext_ln87_4_fu_945_p1));

assign add_ln87_3_fu_967_p2 = ($signed(sext_ln87_7_fu_963_p1) + $signed(sext_ln87_5_fu_949_p1));

assign add_ln87_4_fu_985_p2 = ($signed(sext_ln87_10_fu_981_p1) + $signed(sext_ln87_8_fu_973_p1));

assign add_ln87_5_fu_995_p2 = ($signed(sext_ln87_11_fu_991_p1) + $signed(sext_ln87_9_fu_977_p1));

assign add_ln87_6_fu_1013_p2 = ($signed(sext_ln87_14_fu_1009_p1) + $signed(sext_ln87_12_fu_1001_p1));

assign add_ln87_7_fu_1023_p2 = ($signed(sext_ln87_15_fu_1019_p1) + $signed(sext_ln87_13_fu_1005_p1));

assign add_ln87_fu_929_p2 = ($signed(sext_ln87_2_fu_925_p1) + $signed(sext_ln87_fu_917_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign filt_1_I_1_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_1_d0 = add_ln86_1_reg_1229;

assign filt_1_I_2_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_2_d0 = add_ln86_2_reg_1234;

assign filt_1_I_3_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_3_d0 = add_ln86_3_reg_1239;

assign filt_1_I_4_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_4_d0 = add_ln86_4_reg_1244;

assign filt_1_I_5_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_5_d0 = add_ln86_5_reg_1249;

assign filt_1_I_6_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_6_d0 = add_ln86_6_reg_1254;

assign filt_1_I_7_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_7_d0 = add_ln86_7_reg_1259;

assign filt_1_I_address0 = zext_ln86_fu_1029_p1;

assign filt_1_I_d0 = add_ln86_reg_1224;

assign filt_1_Q_1_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_1_d0 = add_ln87_2_reg_1274;

assign filt_1_Q_2_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_2_d0 = add_ln87_4_reg_1284;

assign filt_1_Q_3_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_3_d0 = add_ln87_6_reg_1294;

assign filt_1_Q_4_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_4_d0 = add_ln87_1_reg_1269;

assign filt_1_Q_5_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_5_d0 = add_ln87_3_reg_1279;

assign filt_1_Q_6_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_6_d0 = add_ln87_5_reg_1289;

assign filt_1_Q_7_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_7_d0 = add_ln87_7_reg_1299;

assign filt_1_Q_address0 = zext_ln86_fu_1029_p1;

assign filt_1_Q_d0 = add_ln87_reg_1264;

assign filt_I_1_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_1_address1 = zext_ln84_fu_738_p1;

assign filt_I_2_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_2_address1 = zext_ln84_fu_738_p1;

assign filt_I_3_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_3_address1 = zext_ln84_fu_738_p1;

assign filt_I_4_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_4_address1 = zext_ln84_fu_738_p1;

assign filt_I_5_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_5_address1 = zext_ln84_fu_738_p1;

assign filt_I_6_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_6_address1 = zext_ln84_fu_738_p1;

assign filt_I_7_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_7_address1 = zext_ln84_fu_738_p1;

assign filt_I_address0 = zext_ln86_1_fu_774_p1;

assign filt_I_address1 = zext_ln84_fu_738_p1;

assign filt_Q_1_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_1_address1 = zext_ln84_fu_738_p1;

assign filt_Q_2_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_2_address1 = zext_ln84_fu_738_p1;

assign filt_Q_3_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_3_address1 = zext_ln84_fu_738_p1;

assign filt_Q_4_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_4_address1 = zext_ln84_fu_738_p1;

assign filt_Q_5_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_5_address1 = zext_ln84_fu_738_p1;

assign filt_Q_6_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_6_address1 = zext_ln84_fu_738_p1;

assign filt_Q_7_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_7_address1 = zext_ln84_fu_738_p1;

assign filt_Q_address0 = zext_ln86_1_fu_774_p1;

assign filt_Q_address1 = zext_ln84_fu_738_p1;

assign icmp_ln84_fu_722_p2 = ((ap_sig_allocacmp_i_2 < 8'd192) ? 1'b1 : 1'b0);

assign lshr_ln4_fu_728_p4 = {{ap_sig_allocacmp_i_2[7:3]}};

assign or_ln86_fu_768_p2 = (lshr_ln4_fu_728_p4 | 5'd1);

assign sext_ln86_10_fu_875_p1 = $signed(filt_I_2_q0);

assign sext_ln86_11_fu_879_p1 = $signed(filt_I_3_q0);

assign sext_ln86_12_fu_889_p1 = $signed(filt_I_4_q0);

assign sext_ln86_13_fu_893_p1 = $signed(filt_I_5_q0);

assign sext_ln86_14_fu_903_p1 = $signed(filt_I_6_q0);

assign sext_ln86_15_fu_907_p1 = $signed(filt_I_7_q0);

assign sext_ln86_1_fu_809_p1 = $signed(filt_I_1_q1);

assign sext_ln86_2_fu_819_p1 = $signed(filt_I_2_q1);

assign sext_ln86_3_fu_823_p1 = $signed(filt_I_3_q1);

assign sext_ln86_4_fu_833_p1 = $signed(filt_I_4_q1);

assign sext_ln86_5_fu_837_p1 = $signed(filt_I_5_q1);

assign sext_ln86_6_fu_847_p1 = $signed(filt_I_6_q1);

assign sext_ln86_7_fu_851_p1 = $signed(filt_I_7_q1);

assign sext_ln86_8_fu_861_p1 = $signed(filt_I_q0);

assign sext_ln86_9_fu_865_p1 = $signed(filt_I_1_q0);

assign sext_ln86_fu_805_p1 = $signed(filt_I_q1);

assign sext_ln87_10_fu_981_p1 = $signed(filt_Q_5_q1);

assign sext_ln87_11_fu_991_p1 = $signed(filt_Q_5_q0);

assign sext_ln87_12_fu_1001_p1 = $signed(filt_Q_6_q1);

assign sext_ln87_13_fu_1005_p1 = $signed(filt_Q_6_q0);

assign sext_ln87_14_fu_1009_p1 = $signed(filt_Q_7_q1);

assign sext_ln87_15_fu_1019_p1 = $signed(filt_Q_7_q0);

assign sext_ln87_1_fu_921_p1 = $signed(filt_Q_q0);

assign sext_ln87_2_fu_925_p1 = $signed(filt_Q_1_q1);

assign sext_ln87_3_fu_935_p1 = $signed(filt_Q_1_q0);

assign sext_ln87_4_fu_945_p1 = $signed(filt_Q_2_q1);

assign sext_ln87_5_fu_949_p1 = $signed(filt_Q_2_q0);

assign sext_ln87_6_fu_953_p1 = $signed(filt_Q_3_q1);

assign sext_ln87_7_fu_963_p1 = $signed(filt_Q_3_q0);

assign sext_ln87_8_fu_973_p1 = $signed(filt_Q_4_q1);

assign sext_ln87_9_fu_977_p1 = $signed(filt_Q_4_q0);

assign sext_ln87_fu_917_p1 = $signed(filt_Q_q1);

assign zext_ln84_fu_738_p1 = lshr_ln4_fu_728_p4;

assign zext_ln86_1_fu_774_p1 = or_ln86_fu_768_p2;

assign zext_ln86_fu_1029_p1 = lshr_ln5_reg_1069_pp0_iter1_reg;

endmodule //receiver_receiver_Pipeline_VITIS_LOOP_84_4
