// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module receiver_receiver_Pipeline_VITIS_LOOP_181_12 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        arr_1_I_address0,
        arr_1_I_ce0,
        arr_1_I_q0,
        arr_1_I_address1,
        arr_1_I_ce1,
        arr_1_I_q1,
        arr_1_I_1_address0,
        arr_1_I_1_ce0,
        arr_1_I_1_q0,
        arr_1_I_1_address1,
        arr_1_I_1_ce1,
        arr_1_I_1_q1,
        arr_2_I_address0,
        arr_2_I_ce0,
        arr_2_I_we0,
        arr_2_I_d0,
        arr_1_Q_address0,
        arr_1_Q_ce0,
        arr_1_Q_q0,
        arr_1_Q_address1,
        arr_1_Q_ce1,
        arr_1_Q_q1,
        arr_1_Q_1_address0,
        arr_1_Q_1_ce0,
        arr_1_Q_1_q0,
        arr_1_Q_1_address1,
        arr_1_Q_1_ce1,
        arr_1_Q_1_q1,
        arr_2_Q_address0,
        arr_2_Q_ce0,
        arr_2_Q_we0,
        arr_2_Q_d0,
        arr_1_I_2_address0,
        arr_1_I_2_ce0,
        arr_1_I_2_q0,
        arr_1_I_2_address1,
        arr_1_I_2_ce1,
        arr_1_I_2_q1,
        arr_1_I_3_address0,
        arr_1_I_3_ce0,
        arr_1_I_3_q0,
        arr_1_I_3_address1,
        arr_1_I_3_ce1,
        arr_1_I_3_q1,
        arr_2_I_1_address0,
        arr_2_I_1_ce0,
        arr_2_I_1_we0,
        arr_2_I_1_d0,
        arr_1_Q_2_address0,
        arr_1_Q_2_ce0,
        arr_1_Q_2_q0,
        arr_1_Q_2_address1,
        arr_1_Q_2_ce1,
        arr_1_Q_2_q1,
        arr_1_Q_3_address0,
        arr_1_Q_3_ce0,
        arr_1_Q_3_q0,
        arr_1_Q_3_address1,
        arr_1_Q_3_ce1,
        arr_1_Q_3_q1,
        arr_2_Q_1_address0,
        arr_2_Q_1_ce0,
        arr_2_Q_1_we0,
        arr_2_Q_1_d0,
        arr_1_I_4_address0,
        arr_1_I_4_ce0,
        arr_1_I_4_q0,
        arr_1_I_4_address1,
        arr_1_I_4_ce1,
        arr_1_I_4_q1,
        arr_1_I_5_address0,
        arr_1_I_5_ce0,
        arr_1_I_5_q0,
        arr_1_I_5_address1,
        arr_1_I_5_ce1,
        arr_1_I_5_q1,
        arr_2_I_2_address0,
        arr_2_I_2_ce0,
        arr_2_I_2_we0,
        arr_2_I_2_d0,
        arr_1_Q_4_address0,
        arr_1_Q_4_ce0,
        arr_1_Q_4_q0,
        arr_1_Q_4_address1,
        arr_1_Q_4_ce1,
        arr_1_Q_4_q1,
        arr_1_Q_5_address0,
        arr_1_Q_5_ce0,
        arr_1_Q_5_q0,
        arr_1_Q_5_address1,
        arr_1_Q_5_ce1,
        arr_1_Q_5_q1,
        arr_2_Q_2_address0,
        arr_2_Q_2_ce0,
        arr_2_Q_2_we0,
        arr_2_Q_2_d0,
        arr_1_I_6_address0,
        arr_1_I_6_ce0,
        arr_1_I_6_q0,
        arr_1_I_6_address1,
        arr_1_I_6_ce1,
        arr_1_I_6_q1,
        arr_1_I_7_address0,
        arr_1_I_7_ce0,
        arr_1_I_7_q0,
        arr_1_I_7_address1,
        arr_1_I_7_ce1,
        arr_1_I_7_q1,
        arr_2_I_3_address0,
        arr_2_I_3_ce0,
        arr_2_I_3_we0,
        arr_2_I_3_d0,
        arr_1_Q_6_address0,
        arr_1_Q_6_ce0,
        arr_1_Q_6_q0,
        arr_1_Q_6_address1,
        arr_1_Q_6_ce1,
        arr_1_Q_6_q1,
        arr_1_Q_7_address0,
        arr_1_Q_7_ce0,
        arr_1_Q_7_q0,
        arr_1_Q_7_address1,
        arr_1_Q_7_ce1,
        arr_1_Q_7_q1,
        arr_2_Q_3_address0,
        arr_2_Q_3_ce0,
        arr_2_Q_3_we0,
        arr_2_Q_3_d0,
        arr_1_I_8_address0,
        arr_1_I_8_ce0,
        arr_1_I_8_q0,
        arr_1_I_8_address1,
        arr_1_I_8_ce1,
        arr_1_I_8_q1,
        arr_1_I_9_address0,
        arr_1_I_9_ce0,
        arr_1_I_9_q0,
        arr_1_I_9_address1,
        arr_1_I_9_ce1,
        arr_1_I_9_q1,
        arr_2_I_4_address0,
        arr_2_I_4_ce0,
        arr_2_I_4_we0,
        arr_2_I_4_d0,
        arr_1_Q_8_address0,
        arr_1_Q_8_ce0,
        arr_1_Q_8_q0,
        arr_1_Q_8_address1,
        arr_1_Q_8_ce1,
        arr_1_Q_8_q1,
        arr_1_Q_9_address0,
        arr_1_Q_9_ce0,
        arr_1_Q_9_q0,
        arr_1_Q_9_address1,
        arr_1_Q_9_ce1,
        arr_1_Q_9_q1,
        arr_2_Q_4_address0,
        arr_2_Q_4_ce0,
        arr_2_Q_4_we0,
        arr_2_Q_4_d0,
        arr_1_I_10_address0,
        arr_1_I_10_ce0,
        arr_1_I_10_q0,
        arr_1_I_10_address1,
        arr_1_I_10_ce1,
        arr_1_I_10_q1,
        arr_1_I_11_address0,
        arr_1_I_11_ce0,
        arr_1_I_11_q0,
        arr_1_I_11_address1,
        arr_1_I_11_ce1,
        arr_1_I_11_q1,
        arr_2_I_5_address0,
        arr_2_I_5_ce0,
        arr_2_I_5_we0,
        arr_2_I_5_d0,
        arr_1_Q_10_address0,
        arr_1_Q_10_ce0,
        arr_1_Q_10_q0,
        arr_1_Q_10_address1,
        arr_1_Q_10_ce1,
        arr_1_Q_10_q1,
        arr_1_Q_11_address0,
        arr_1_Q_11_ce0,
        arr_1_Q_11_q0,
        arr_1_Q_11_address1,
        arr_1_Q_11_ce1,
        arr_1_Q_11_q1,
        arr_2_Q_5_address0,
        arr_2_Q_5_ce0,
        arr_2_Q_5_we0,
        arr_2_Q_5_d0,
        arr_1_I_12_address0,
        arr_1_I_12_ce0,
        arr_1_I_12_q0,
        arr_1_I_12_address1,
        arr_1_I_12_ce1,
        arr_1_I_12_q1,
        arr_1_I_13_address0,
        arr_1_I_13_ce0,
        arr_1_I_13_q0,
        arr_1_I_13_address1,
        arr_1_I_13_ce1,
        arr_1_I_13_q1,
        arr_2_I_6_address0,
        arr_2_I_6_ce0,
        arr_2_I_6_we0,
        arr_2_I_6_d0,
        arr_1_Q_12_address0,
        arr_1_Q_12_ce0,
        arr_1_Q_12_q0,
        arr_1_Q_12_address1,
        arr_1_Q_12_ce1,
        arr_1_Q_12_q1,
        arr_1_Q_13_address0,
        arr_1_Q_13_ce0,
        arr_1_Q_13_q0,
        arr_1_Q_13_address1,
        arr_1_Q_13_ce1,
        arr_1_Q_13_q1,
        arr_2_Q_6_address0,
        arr_2_Q_6_ce0,
        arr_2_Q_6_we0,
        arr_2_Q_6_d0,
        arr_1_I_14_address0,
        arr_1_I_14_ce0,
        arr_1_I_14_q0,
        arr_1_I_14_address1,
        arr_1_I_14_ce1,
        arr_1_I_14_q1,
        arr_1_I_15_address0,
        arr_1_I_15_ce0,
        arr_1_I_15_q0,
        arr_1_I_15_address1,
        arr_1_I_15_ce1,
        arr_1_I_15_q1,
        arr_2_I_7_address0,
        arr_2_I_7_ce0,
        arr_2_I_7_we0,
        arr_2_I_7_d0,
        arr_1_Q_14_address0,
        arr_1_Q_14_ce0,
        arr_1_Q_14_q0,
        arr_1_Q_14_address1,
        arr_1_Q_14_ce1,
        arr_1_Q_14_q1,
        arr_1_Q_15_address0,
        arr_1_Q_15_ce0,
        arr_1_Q_15_q0,
        arr_1_Q_15_address1,
        arr_1_Q_15_ce1,
        arr_1_Q_15_q1,
        arr_2_Q_7_address0,
        arr_2_Q_7_ce0,
        arr_2_Q_7_we0,
        arr_2_Q_7_d0,
        arr_2_I_8_address0,
        arr_2_I_8_ce0,
        arr_2_I_8_we0,
        arr_2_I_8_d0,
        arr_2_Q_8_address0,
        arr_2_Q_8_ce0,
        arr_2_Q_8_we0,
        arr_2_Q_8_d0,
        arr_2_I_9_address0,
        arr_2_I_9_ce0,
        arr_2_I_9_we0,
        arr_2_I_9_d0,
        arr_2_Q_9_address0,
        arr_2_Q_9_ce0,
        arr_2_Q_9_we0,
        arr_2_Q_9_d0,
        arr_2_I_10_address0,
        arr_2_I_10_ce0,
        arr_2_I_10_we0,
        arr_2_I_10_d0,
        arr_2_Q_10_address0,
        arr_2_Q_10_ce0,
        arr_2_Q_10_we0,
        arr_2_Q_10_d0,
        arr_2_I_11_address0,
        arr_2_I_11_ce0,
        arr_2_I_11_we0,
        arr_2_I_11_d0,
        arr_2_Q_11_address0,
        arr_2_Q_11_ce0,
        arr_2_Q_11_we0,
        arr_2_Q_11_d0,
        arr_2_I_12_address0,
        arr_2_I_12_ce0,
        arr_2_I_12_we0,
        arr_2_I_12_d0,
        arr_2_Q_12_address0,
        arr_2_Q_12_ce0,
        arr_2_Q_12_we0,
        arr_2_Q_12_d0,
        arr_2_I_13_address0,
        arr_2_I_13_ce0,
        arr_2_I_13_we0,
        arr_2_I_13_d0,
        arr_2_Q_13_address0,
        arr_2_Q_13_ce0,
        arr_2_Q_13_we0,
        arr_2_Q_13_d0,
        arr_2_I_14_address0,
        arr_2_I_14_ce0,
        arr_2_I_14_we0,
        arr_2_I_14_d0,
        arr_2_Q_14_address0,
        arr_2_Q_14_ce0,
        arr_2_Q_14_we0,
        arr_2_Q_14_d0,
        arr_2_I_15_address0,
        arr_2_I_15_ce0,
        arr_2_I_15_we0,
        arr_2_I_15_d0,
        arr_2_Q_15_address0,
        arr_2_Q_15_ce0,
        arr_2_Q_15_we0,
        arr_2_Q_15_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [5:0] arr_1_I_address0;
output   arr_1_I_ce0;
input  [17:0] arr_1_I_q0;
output  [5:0] arr_1_I_address1;
output   arr_1_I_ce1;
input  [17:0] arr_1_I_q1;
output  [5:0] arr_1_I_1_address0;
output   arr_1_I_1_ce0;
input  [17:0] arr_1_I_1_q0;
output  [5:0] arr_1_I_1_address1;
output   arr_1_I_1_ce1;
input  [17:0] arr_1_I_1_q1;
output  [4:0] arr_2_I_address0;
output   arr_2_I_ce0;
output   arr_2_I_we0;
output  [24:0] arr_2_I_d0;
output  [5:0] arr_1_Q_address0;
output   arr_1_Q_ce0;
input  [17:0] arr_1_Q_q0;
output  [5:0] arr_1_Q_address1;
output   arr_1_Q_ce1;
input  [17:0] arr_1_Q_q1;
output  [5:0] arr_1_Q_1_address0;
output   arr_1_Q_1_ce0;
input  [17:0] arr_1_Q_1_q0;
output  [5:0] arr_1_Q_1_address1;
output   arr_1_Q_1_ce1;
input  [17:0] arr_1_Q_1_q1;
output  [4:0] arr_2_Q_address0;
output   arr_2_Q_ce0;
output   arr_2_Q_we0;
output  [24:0] arr_2_Q_d0;
output  [5:0] arr_1_I_2_address0;
output   arr_1_I_2_ce0;
input  [17:0] arr_1_I_2_q0;
output  [5:0] arr_1_I_2_address1;
output   arr_1_I_2_ce1;
input  [17:0] arr_1_I_2_q1;
output  [5:0] arr_1_I_3_address0;
output   arr_1_I_3_ce0;
input  [17:0] arr_1_I_3_q0;
output  [5:0] arr_1_I_3_address1;
output   arr_1_I_3_ce1;
input  [17:0] arr_1_I_3_q1;
output  [4:0] arr_2_I_1_address0;
output   arr_2_I_1_ce0;
output   arr_2_I_1_we0;
output  [24:0] arr_2_I_1_d0;
output  [5:0] arr_1_Q_2_address0;
output   arr_1_Q_2_ce0;
input  [17:0] arr_1_Q_2_q0;
output  [5:0] arr_1_Q_2_address1;
output   arr_1_Q_2_ce1;
input  [17:0] arr_1_Q_2_q1;
output  [5:0] arr_1_Q_3_address0;
output   arr_1_Q_3_ce0;
input  [17:0] arr_1_Q_3_q0;
output  [5:0] arr_1_Q_3_address1;
output   arr_1_Q_3_ce1;
input  [17:0] arr_1_Q_3_q1;
output  [4:0] arr_2_Q_1_address0;
output   arr_2_Q_1_ce0;
output   arr_2_Q_1_we0;
output  [24:0] arr_2_Q_1_d0;
output  [5:0] arr_1_I_4_address0;
output   arr_1_I_4_ce0;
input  [17:0] arr_1_I_4_q0;
output  [5:0] arr_1_I_4_address1;
output   arr_1_I_4_ce1;
input  [17:0] arr_1_I_4_q1;
output  [5:0] arr_1_I_5_address0;
output   arr_1_I_5_ce0;
input  [17:0] arr_1_I_5_q0;
output  [5:0] arr_1_I_5_address1;
output   arr_1_I_5_ce1;
input  [17:0] arr_1_I_5_q1;
output  [4:0] arr_2_I_2_address0;
output   arr_2_I_2_ce0;
output   arr_2_I_2_we0;
output  [24:0] arr_2_I_2_d0;
output  [5:0] arr_1_Q_4_address0;
output   arr_1_Q_4_ce0;
input  [17:0] arr_1_Q_4_q0;
output  [5:0] arr_1_Q_4_address1;
output   arr_1_Q_4_ce1;
input  [17:0] arr_1_Q_4_q1;
output  [5:0] arr_1_Q_5_address0;
output   arr_1_Q_5_ce0;
input  [17:0] arr_1_Q_5_q0;
output  [5:0] arr_1_Q_5_address1;
output   arr_1_Q_5_ce1;
input  [17:0] arr_1_Q_5_q1;
output  [4:0] arr_2_Q_2_address0;
output   arr_2_Q_2_ce0;
output   arr_2_Q_2_we0;
output  [24:0] arr_2_Q_2_d0;
output  [5:0] arr_1_I_6_address0;
output   arr_1_I_6_ce0;
input  [17:0] arr_1_I_6_q0;
output  [5:0] arr_1_I_6_address1;
output   arr_1_I_6_ce1;
input  [17:0] arr_1_I_6_q1;
output  [5:0] arr_1_I_7_address0;
output   arr_1_I_7_ce0;
input  [17:0] arr_1_I_7_q0;
output  [5:0] arr_1_I_7_address1;
output   arr_1_I_7_ce1;
input  [17:0] arr_1_I_7_q1;
output  [4:0] arr_2_I_3_address0;
output   arr_2_I_3_ce0;
output   arr_2_I_3_we0;
output  [24:0] arr_2_I_3_d0;
output  [5:0] arr_1_Q_6_address0;
output   arr_1_Q_6_ce0;
input  [17:0] arr_1_Q_6_q0;
output  [5:0] arr_1_Q_6_address1;
output   arr_1_Q_6_ce1;
input  [17:0] arr_1_Q_6_q1;
output  [5:0] arr_1_Q_7_address0;
output   arr_1_Q_7_ce0;
input  [17:0] arr_1_Q_7_q0;
output  [5:0] arr_1_Q_7_address1;
output   arr_1_Q_7_ce1;
input  [17:0] arr_1_Q_7_q1;
output  [4:0] arr_2_Q_3_address0;
output   arr_2_Q_3_ce0;
output   arr_2_Q_3_we0;
output  [24:0] arr_2_Q_3_d0;
output  [5:0] arr_1_I_8_address0;
output   arr_1_I_8_ce0;
input  [17:0] arr_1_I_8_q0;
output  [5:0] arr_1_I_8_address1;
output   arr_1_I_8_ce1;
input  [17:0] arr_1_I_8_q1;
output  [5:0] arr_1_I_9_address0;
output   arr_1_I_9_ce0;
input  [17:0] arr_1_I_9_q0;
output  [5:0] arr_1_I_9_address1;
output   arr_1_I_9_ce1;
input  [17:0] arr_1_I_9_q1;
output  [4:0] arr_2_I_4_address0;
output   arr_2_I_4_ce0;
output   arr_2_I_4_we0;
output  [24:0] arr_2_I_4_d0;
output  [5:0] arr_1_Q_8_address0;
output   arr_1_Q_8_ce0;
input  [17:0] arr_1_Q_8_q0;
output  [5:0] arr_1_Q_8_address1;
output   arr_1_Q_8_ce1;
input  [17:0] arr_1_Q_8_q1;
output  [5:0] arr_1_Q_9_address0;
output   arr_1_Q_9_ce0;
input  [17:0] arr_1_Q_9_q0;
output  [5:0] arr_1_Q_9_address1;
output   arr_1_Q_9_ce1;
input  [17:0] arr_1_Q_9_q1;
output  [4:0] arr_2_Q_4_address0;
output   arr_2_Q_4_ce0;
output   arr_2_Q_4_we0;
output  [24:0] arr_2_Q_4_d0;
output  [5:0] arr_1_I_10_address0;
output   arr_1_I_10_ce0;
input  [17:0] arr_1_I_10_q0;
output  [5:0] arr_1_I_10_address1;
output   arr_1_I_10_ce1;
input  [17:0] arr_1_I_10_q1;
output  [5:0] arr_1_I_11_address0;
output   arr_1_I_11_ce0;
input  [17:0] arr_1_I_11_q0;
output  [5:0] arr_1_I_11_address1;
output   arr_1_I_11_ce1;
input  [17:0] arr_1_I_11_q1;
output  [4:0] arr_2_I_5_address0;
output   arr_2_I_5_ce0;
output   arr_2_I_5_we0;
output  [24:0] arr_2_I_5_d0;
output  [5:0] arr_1_Q_10_address0;
output   arr_1_Q_10_ce0;
input  [17:0] arr_1_Q_10_q0;
output  [5:0] arr_1_Q_10_address1;
output   arr_1_Q_10_ce1;
input  [17:0] arr_1_Q_10_q1;
output  [5:0] arr_1_Q_11_address0;
output   arr_1_Q_11_ce0;
input  [17:0] arr_1_Q_11_q0;
output  [5:0] arr_1_Q_11_address1;
output   arr_1_Q_11_ce1;
input  [17:0] arr_1_Q_11_q1;
output  [4:0] arr_2_Q_5_address0;
output   arr_2_Q_5_ce0;
output   arr_2_Q_5_we0;
output  [24:0] arr_2_Q_5_d0;
output  [5:0] arr_1_I_12_address0;
output   arr_1_I_12_ce0;
input  [17:0] arr_1_I_12_q0;
output  [5:0] arr_1_I_12_address1;
output   arr_1_I_12_ce1;
input  [17:0] arr_1_I_12_q1;
output  [5:0] arr_1_I_13_address0;
output   arr_1_I_13_ce0;
input  [17:0] arr_1_I_13_q0;
output  [5:0] arr_1_I_13_address1;
output   arr_1_I_13_ce1;
input  [17:0] arr_1_I_13_q1;
output  [4:0] arr_2_I_6_address0;
output   arr_2_I_6_ce0;
output   arr_2_I_6_we0;
output  [24:0] arr_2_I_6_d0;
output  [5:0] arr_1_Q_12_address0;
output   arr_1_Q_12_ce0;
input  [17:0] arr_1_Q_12_q0;
output  [5:0] arr_1_Q_12_address1;
output   arr_1_Q_12_ce1;
input  [17:0] arr_1_Q_12_q1;
output  [5:0] arr_1_Q_13_address0;
output   arr_1_Q_13_ce0;
input  [17:0] arr_1_Q_13_q0;
output  [5:0] arr_1_Q_13_address1;
output   arr_1_Q_13_ce1;
input  [17:0] arr_1_Q_13_q1;
output  [4:0] arr_2_Q_6_address0;
output   arr_2_Q_6_ce0;
output   arr_2_Q_6_we0;
output  [24:0] arr_2_Q_6_d0;
output  [5:0] arr_1_I_14_address0;
output   arr_1_I_14_ce0;
input  [17:0] arr_1_I_14_q0;
output  [5:0] arr_1_I_14_address1;
output   arr_1_I_14_ce1;
input  [17:0] arr_1_I_14_q1;
output  [5:0] arr_1_I_15_address0;
output   arr_1_I_15_ce0;
input  [17:0] arr_1_I_15_q0;
output  [5:0] arr_1_I_15_address1;
output   arr_1_I_15_ce1;
input  [17:0] arr_1_I_15_q1;
output  [4:0] arr_2_I_7_address0;
output   arr_2_I_7_ce0;
output   arr_2_I_7_we0;
output  [24:0] arr_2_I_7_d0;
output  [5:0] arr_1_Q_14_address0;
output   arr_1_Q_14_ce0;
input  [17:0] arr_1_Q_14_q0;
output  [5:0] arr_1_Q_14_address1;
output   arr_1_Q_14_ce1;
input  [17:0] arr_1_Q_14_q1;
output  [5:0] arr_1_Q_15_address0;
output   arr_1_Q_15_ce0;
input  [17:0] arr_1_Q_15_q0;
output  [5:0] arr_1_Q_15_address1;
output   arr_1_Q_15_ce1;
input  [17:0] arr_1_Q_15_q1;
output  [4:0] arr_2_Q_7_address0;
output   arr_2_Q_7_ce0;
output   arr_2_Q_7_we0;
output  [24:0] arr_2_Q_7_d0;
output  [4:0] arr_2_I_8_address0;
output   arr_2_I_8_ce0;
output   arr_2_I_8_we0;
output  [24:0] arr_2_I_8_d0;
output  [4:0] arr_2_Q_8_address0;
output   arr_2_Q_8_ce0;
output   arr_2_Q_8_we0;
output  [24:0] arr_2_Q_8_d0;
output  [4:0] arr_2_I_9_address0;
output   arr_2_I_9_ce0;
output   arr_2_I_9_we0;
output  [24:0] arr_2_I_9_d0;
output  [4:0] arr_2_Q_9_address0;
output   arr_2_Q_9_ce0;
output   arr_2_Q_9_we0;
output  [24:0] arr_2_Q_9_d0;
output  [4:0] arr_2_I_10_address0;
output   arr_2_I_10_ce0;
output   arr_2_I_10_we0;
output  [24:0] arr_2_I_10_d0;
output  [4:0] arr_2_Q_10_address0;
output   arr_2_Q_10_ce0;
output   arr_2_Q_10_we0;
output  [24:0] arr_2_Q_10_d0;
output  [4:0] arr_2_I_11_address0;
output   arr_2_I_11_ce0;
output   arr_2_I_11_we0;
output  [24:0] arr_2_I_11_d0;
output  [4:0] arr_2_Q_11_address0;
output   arr_2_Q_11_ce0;
output   arr_2_Q_11_we0;
output  [24:0] arr_2_Q_11_d0;
output  [4:0] arr_2_I_12_address0;
output   arr_2_I_12_ce0;
output   arr_2_I_12_we0;
output  [24:0] arr_2_I_12_d0;
output  [4:0] arr_2_Q_12_address0;
output   arr_2_Q_12_ce0;
output   arr_2_Q_12_we0;
output  [24:0] arr_2_Q_12_d0;
output  [4:0] arr_2_I_13_address0;
output   arr_2_I_13_ce0;
output   arr_2_I_13_we0;
output  [24:0] arr_2_I_13_d0;
output  [4:0] arr_2_Q_13_address0;
output   arr_2_Q_13_ce0;
output   arr_2_Q_13_we0;
output  [24:0] arr_2_Q_13_d0;
output  [4:0] arr_2_I_14_address0;
output   arr_2_I_14_ce0;
output   arr_2_I_14_we0;
output  [24:0] arr_2_I_14_d0;
output  [4:0] arr_2_Q_14_address0;
output   arr_2_Q_14_ce0;
output   arr_2_Q_14_we0;
output  [24:0] arr_2_Q_14_d0;
output  [4:0] arr_2_I_15_address0;
output   arr_2_I_15_ce0;
output   arr_2_I_15_we0;
output  [24:0] arr_2_I_15_d0;
output  [4:0] arr_2_Q_15_address0;
output   arr_2_Q_15_ce0;
output   arr_2_Q_15_we0;
output  [24:0] arr_2_Q_15_d0;

reg ap_idle;
reg arr_1_I_ce0;
reg arr_1_I_ce1;
reg arr_1_I_1_ce0;
reg arr_1_I_1_ce1;
reg arr_2_I_ce0;
reg arr_2_I_we0;
reg arr_1_Q_ce0;
reg arr_1_Q_ce1;
reg arr_1_Q_1_ce0;
reg arr_1_Q_1_ce1;
reg arr_2_Q_ce0;
reg arr_2_Q_we0;
reg arr_1_I_2_ce0;
reg arr_1_I_2_ce1;
reg arr_1_I_3_ce0;
reg arr_1_I_3_ce1;
reg arr_2_I_1_ce0;
reg arr_2_I_1_we0;
reg arr_1_Q_2_ce0;
reg arr_1_Q_2_ce1;
reg arr_1_Q_3_ce0;
reg arr_1_Q_3_ce1;
reg arr_2_Q_1_ce0;
reg arr_2_Q_1_we0;
reg arr_1_I_4_ce0;
reg arr_1_I_4_ce1;
reg arr_1_I_5_ce0;
reg arr_1_I_5_ce1;
reg arr_2_I_2_ce0;
reg arr_2_I_2_we0;
reg arr_1_Q_4_ce0;
reg arr_1_Q_4_ce1;
reg arr_1_Q_5_ce0;
reg arr_1_Q_5_ce1;
reg arr_2_Q_2_ce0;
reg arr_2_Q_2_we0;
reg arr_1_I_6_ce0;
reg arr_1_I_6_ce1;
reg arr_1_I_7_ce0;
reg arr_1_I_7_ce1;
reg arr_2_I_3_ce0;
reg arr_2_I_3_we0;
reg arr_1_Q_6_ce0;
reg arr_1_Q_6_ce1;
reg arr_1_Q_7_ce0;
reg arr_1_Q_7_ce1;
reg arr_2_Q_3_ce0;
reg arr_2_Q_3_we0;
reg arr_1_I_8_ce0;
reg arr_1_I_8_ce1;
reg arr_1_I_9_ce0;
reg arr_1_I_9_ce1;
reg arr_2_I_4_ce0;
reg arr_2_I_4_we0;
reg arr_1_Q_8_ce0;
reg arr_1_Q_8_ce1;
reg arr_1_Q_9_ce0;
reg arr_1_Q_9_ce1;
reg arr_2_Q_4_ce0;
reg arr_2_Q_4_we0;
reg arr_1_I_10_ce0;
reg arr_1_I_10_ce1;
reg arr_1_I_11_ce0;
reg arr_1_I_11_ce1;
reg arr_2_I_5_ce0;
reg arr_2_I_5_we0;
reg arr_1_Q_10_ce0;
reg arr_1_Q_10_ce1;
reg arr_1_Q_11_ce0;
reg arr_1_Q_11_ce1;
reg arr_2_Q_5_ce0;
reg arr_2_Q_5_we0;
reg arr_1_I_12_ce0;
reg arr_1_I_12_ce1;
reg arr_1_I_13_ce0;
reg arr_1_I_13_ce1;
reg arr_2_I_6_ce0;
reg arr_2_I_6_we0;
reg arr_1_Q_12_ce0;
reg arr_1_Q_12_ce1;
reg arr_1_Q_13_ce0;
reg arr_1_Q_13_ce1;
reg arr_2_Q_6_ce0;
reg arr_2_Q_6_we0;
reg arr_1_I_14_ce0;
reg arr_1_I_14_ce1;
reg arr_1_I_15_ce0;
reg arr_1_I_15_ce1;
reg arr_2_I_7_ce0;
reg arr_2_I_7_we0;
reg arr_1_Q_14_ce0;
reg arr_1_Q_14_ce1;
reg arr_1_Q_15_ce0;
reg arr_1_Q_15_ce1;
reg arr_2_Q_7_ce0;
reg arr_2_Q_7_we0;
reg arr_2_I_8_ce0;
reg arr_2_I_8_we0;
reg arr_2_Q_8_ce0;
reg arr_2_Q_8_we0;
reg arr_2_I_9_ce0;
reg arr_2_I_9_we0;
reg arr_2_Q_9_ce0;
reg arr_2_Q_9_we0;
reg arr_2_I_10_ce0;
reg arr_2_I_10_we0;
reg arr_2_Q_10_ce0;
reg arr_2_Q_10_we0;
reg arr_2_I_11_ce0;
reg arr_2_I_11_we0;
reg arr_2_Q_11_ce0;
reg arr_2_Q_11_we0;
reg arr_2_I_12_ce0;
reg arr_2_I_12_we0;
reg arr_2_Q_12_ce0;
reg arr_2_Q_12_we0;
reg arr_2_I_13_ce0;
reg arr_2_I_13_we0;
reg arr_2_Q_13_ce0;
reg arr_2_Q_13_we0;
reg arr_2_I_14_ce0;
reg arr_2_I_14_we0;
reg arr_2_Q_14_ce0;
reg arr_2_Q_14_we0;
reg arr_2_I_15_ce0;
reg arr_2_I_15_we0;
reg arr_2_Q_15_ce0;
reg arr_2_Q_15_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln181_fu_1462_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] lshr_ln3_reg_2277;
reg   [4:0] lshr_ln3_reg_2277_pp0_iter1_reg;
reg   [0:0] icmp_ln181_reg_2432;
reg   [0:0] icmp_ln181_reg_2432_pp0_iter1_reg;
wire   [18:0] add_ln183_fu_1529_p2;
reg   [18:0] add_ln183_reg_2596;
wire   [18:0] add_ln183_1_fu_1543_p2;
reg   [18:0] add_ln183_1_reg_2601;
wire   [18:0] add_ln183_2_fu_1557_p2;
reg   [18:0] add_ln183_2_reg_2606;
wire   [18:0] add_ln183_3_fu_1571_p2;
reg   [18:0] add_ln183_3_reg_2611;
wire   [18:0] add_ln183_4_fu_1585_p2;
reg   [18:0] add_ln183_4_reg_2616;
wire   [18:0] add_ln183_5_fu_1599_p2;
reg   [18:0] add_ln183_5_reg_2621;
wire   [18:0] add_ln183_6_fu_1613_p2;
reg   [18:0] add_ln183_6_reg_2626;
wire   [18:0] add_ln183_7_fu_1627_p2;
reg   [18:0] add_ln183_7_reg_2631;
wire   [18:0] add_ln184_fu_1641_p2;
reg   [18:0] add_ln184_reg_2636;
wire   [18:0] add_ln184_1_fu_1655_p2;
reg   [18:0] add_ln184_1_reg_2641;
wire   [18:0] add_ln184_2_fu_1669_p2;
reg   [18:0] add_ln184_2_reg_2646;
wire   [18:0] add_ln184_3_fu_1683_p2;
reg   [18:0] add_ln184_3_reg_2651;
wire   [18:0] add_ln184_4_fu_1697_p2;
reg   [18:0] add_ln184_4_reg_2656;
wire   [18:0] add_ln184_5_fu_1711_p2;
reg   [18:0] add_ln184_5_reg_2661;
wire   [18:0] add_ln184_6_fu_1725_p2;
reg   [18:0] add_ln184_6_reg_2666;
wire   [18:0] add_ln184_7_fu_1739_p2;
reg   [18:0] add_ln184_7_reg_2671;
wire   [18:0] add_ln183_8_fu_1753_p2;
reg   [18:0] add_ln183_8_reg_2676;
wire   [18:0] add_ln183_9_fu_1767_p2;
reg   [18:0] add_ln183_9_reg_2681;
wire   [18:0] add_ln183_10_fu_1781_p2;
reg   [18:0] add_ln183_10_reg_2686;
wire   [18:0] add_ln183_11_fu_1795_p2;
reg   [18:0] add_ln183_11_reg_2691;
wire   [18:0] add_ln183_12_fu_1809_p2;
reg   [18:0] add_ln183_12_reg_2696;
wire   [18:0] add_ln183_13_fu_1823_p2;
reg   [18:0] add_ln183_13_reg_2701;
wire   [18:0] add_ln183_14_fu_1837_p2;
reg   [18:0] add_ln183_14_reg_2706;
wire   [18:0] add_ln183_15_fu_1851_p2;
reg   [18:0] add_ln183_15_reg_2711;
wire   [18:0] add_ln184_8_fu_1865_p2;
reg   [18:0] add_ln184_8_reg_2716;
wire   [18:0] add_ln184_9_fu_1879_p2;
reg   [18:0] add_ln184_9_reg_2721;
wire   [18:0] add_ln184_10_fu_1893_p2;
reg   [18:0] add_ln184_10_reg_2726;
wire   [18:0] add_ln184_11_fu_1907_p2;
reg   [18:0] add_ln184_11_reg_2731;
wire   [18:0] add_ln184_12_fu_1921_p2;
reg   [18:0] add_ln184_12_reg_2736;
wire   [18:0] add_ln184_13_fu_1935_p2;
reg   [18:0] add_ln184_13_reg_2741;
wire   [18:0] add_ln184_14_fu_1949_p2;
reg   [18:0] add_ln184_14_reg_2746;
wire   [18:0] add_ln184_15_fu_1963_p2;
reg   [18:0] add_ln184_15_reg_2751;
wire   [63:0] zext_ln181_fu_1410_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln181_1_fu_1474_p1;
wire   [63:0] zext_ln183_fu_1977_p1;
reg   [9:0] i_11_fu_172;
wire   [9:0] add_ln181_fu_1510_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i;
wire   [5:0] lshr_ln_fu_1400_p4;
wire   [9:0] or_ln181_fu_1456_p2;
wire   [5:0] or_ln181_1_fu_1468_p2;
wire  signed [18:0] sext_ln183_1_fu_1525_p1;
wire  signed [18:0] sext_ln183_fu_1521_p1;
wire  signed [18:0] sext_ln183_3_fu_1539_p1;
wire  signed [18:0] sext_ln183_2_fu_1535_p1;
wire  signed [18:0] sext_ln183_5_fu_1553_p1;
wire  signed [18:0] sext_ln183_4_fu_1549_p1;
wire  signed [18:0] sext_ln183_7_fu_1567_p1;
wire  signed [18:0] sext_ln183_6_fu_1563_p1;
wire  signed [18:0] sext_ln183_9_fu_1581_p1;
wire  signed [18:0] sext_ln183_8_fu_1577_p1;
wire  signed [18:0] sext_ln183_11_fu_1595_p1;
wire  signed [18:0] sext_ln183_10_fu_1591_p1;
wire  signed [18:0] sext_ln183_13_fu_1609_p1;
wire  signed [18:0] sext_ln183_12_fu_1605_p1;
wire  signed [18:0] sext_ln183_15_fu_1623_p1;
wire  signed [18:0] sext_ln183_14_fu_1619_p1;
wire  signed [18:0] sext_ln184_1_fu_1637_p1;
wire  signed [18:0] sext_ln184_fu_1633_p1;
wire  signed [18:0] sext_ln184_3_fu_1651_p1;
wire  signed [18:0] sext_ln184_2_fu_1647_p1;
wire  signed [18:0] sext_ln184_5_fu_1665_p1;
wire  signed [18:0] sext_ln184_4_fu_1661_p1;
wire  signed [18:0] sext_ln184_7_fu_1679_p1;
wire  signed [18:0] sext_ln184_6_fu_1675_p1;
wire  signed [18:0] sext_ln184_9_fu_1693_p1;
wire  signed [18:0] sext_ln184_8_fu_1689_p1;
wire  signed [18:0] sext_ln184_11_fu_1707_p1;
wire  signed [18:0] sext_ln184_10_fu_1703_p1;
wire  signed [18:0] sext_ln184_13_fu_1721_p1;
wire  signed [18:0] sext_ln184_12_fu_1717_p1;
wire  signed [18:0] sext_ln184_15_fu_1735_p1;
wire  signed [18:0] sext_ln184_14_fu_1731_p1;
wire  signed [18:0] sext_ln183_17_fu_1749_p1;
wire  signed [18:0] sext_ln183_16_fu_1745_p1;
wire  signed [18:0] sext_ln183_19_fu_1763_p1;
wire  signed [18:0] sext_ln183_18_fu_1759_p1;
wire  signed [18:0] sext_ln183_21_fu_1777_p1;
wire  signed [18:0] sext_ln183_20_fu_1773_p1;
wire  signed [18:0] sext_ln183_23_fu_1791_p1;
wire  signed [18:0] sext_ln183_22_fu_1787_p1;
wire  signed [18:0] sext_ln183_25_fu_1805_p1;
wire  signed [18:0] sext_ln183_24_fu_1801_p1;
wire  signed [18:0] sext_ln183_27_fu_1819_p1;
wire  signed [18:0] sext_ln183_26_fu_1815_p1;
wire  signed [18:0] sext_ln183_29_fu_1833_p1;
wire  signed [18:0] sext_ln183_28_fu_1829_p1;
wire  signed [18:0] sext_ln183_31_fu_1847_p1;
wire  signed [18:0] sext_ln183_30_fu_1843_p1;
wire  signed [18:0] sext_ln184_17_fu_1861_p1;
wire  signed [18:0] sext_ln184_16_fu_1857_p1;
wire  signed [18:0] sext_ln184_19_fu_1875_p1;
wire  signed [18:0] sext_ln184_18_fu_1871_p1;
wire  signed [18:0] sext_ln184_21_fu_1889_p1;
wire  signed [18:0] sext_ln184_20_fu_1885_p1;
wire  signed [18:0] sext_ln184_23_fu_1903_p1;
wire  signed [18:0] sext_ln184_22_fu_1899_p1;
wire  signed [18:0] sext_ln184_25_fu_1917_p1;
wire  signed [18:0] sext_ln184_24_fu_1913_p1;
wire  signed [18:0] sext_ln184_27_fu_1931_p1;
wire  signed [18:0] sext_ln184_26_fu_1927_p1;
wire  signed [18:0] sext_ln184_29_fu_1945_p1;
wire  signed [18:0] sext_ln184_28_fu_1941_p1;
wire  signed [18:0] sext_ln184_31_fu_1959_p1;
wire  signed [18:0] sext_ln184_30_fu_1955_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_done_reg = 1'b0;
end

receiver_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter1_reg == 1'b0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln181_fu_1462_p2 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_11_fu_172 <= add_ln181_fu_1510_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_11_fu_172 <= 10'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln181_reg_2432 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln183_10_reg_2686 <= add_ln183_10_fu_1781_p2;
        add_ln183_11_reg_2691 <= add_ln183_11_fu_1795_p2;
        add_ln183_12_reg_2696 <= add_ln183_12_fu_1809_p2;
        add_ln183_13_reg_2701 <= add_ln183_13_fu_1823_p2;
        add_ln183_14_reg_2706 <= add_ln183_14_fu_1837_p2;
        add_ln183_15_reg_2711 <= add_ln183_15_fu_1851_p2;
        add_ln183_8_reg_2676 <= add_ln183_8_fu_1753_p2;
        add_ln183_9_reg_2681 <= add_ln183_9_fu_1767_p2;
        add_ln184_10_reg_2726 <= add_ln184_10_fu_1893_p2;
        add_ln184_11_reg_2731 <= add_ln184_11_fu_1907_p2;
        add_ln184_12_reg_2736 <= add_ln184_12_fu_1921_p2;
        add_ln184_13_reg_2741 <= add_ln184_13_fu_1935_p2;
        add_ln184_14_reg_2746 <= add_ln184_14_fu_1949_p2;
        add_ln184_15_reg_2751 <= add_ln184_15_fu_1963_p2;
        add_ln184_8_reg_2716 <= add_ln184_8_fu_1865_p2;
        add_ln184_9_reg_2721 <= add_ln184_9_fu_1879_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln183_1_reg_2601 <= add_ln183_1_fu_1543_p2;
        add_ln183_2_reg_2606 <= add_ln183_2_fu_1557_p2;
        add_ln183_3_reg_2611 <= add_ln183_3_fu_1571_p2;
        add_ln183_4_reg_2616 <= add_ln183_4_fu_1585_p2;
        add_ln183_5_reg_2621 <= add_ln183_5_fu_1599_p2;
        add_ln183_6_reg_2626 <= add_ln183_6_fu_1613_p2;
        add_ln183_7_reg_2631 <= add_ln183_7_fu_1627_p2;
        add_ln183_reg_2596 <= add_ln183_fu_1529_p2;
        add_ln184_1_reg_2641 <= add_ln184_1_fu_1655_p2;
        add_ln184_2_reg_2646 <= add_ln184_2_fu_1669_p2;
        add_ln184_3_reg_2651 <= add_ln184_3_fu_1683_p2;
        add_ln184_4_reg_2656 <= add_ln184_4_fu_1697_p2;
        add_ln184_5_reg_2661 <= add_ln184_5_fu_1711_p2;
        add_ln184_6_reg_2666 <= add_ln184_6_fu_1725_p2;
        add_ln184_7_reg_2671 <= add_ln184_7_fu_1739_p2;
        add_ln184_reg_2636 <= add_ln184_fu_1641_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        icmp_ln181_reg_2432 <= icmp_ln181_fu_1462_p2;
        icmp_ln181_reg_2432_pp0_iter1_reg <= icmp_ln181_reg_2432;
        lshr_ln3_reg_2277 <= {{ap_sig_allocacmp_i[9:5]}};
        lshr_ln3_reg_2277_pp0_iter1_reg <= lshr_ln3_reg_2277;
    end
end

always @ (*) begin
    if (((icmp_ln181_fu_1462_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter2_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i = 10'd0;
    end else begin
        ap_sig_allocacmp_i = i_11_fu_172;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_10_ce0 = 1'b1;
    end else begin
        arr_1_I_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_10_ce1 = 1'b1;
    end else begin
        arr_1_I_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_11_ce0 = 1'b1;
    end else begin
        arr_1_I_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_11_ce1 = 1'b1;
    end else begin
        arr_1_I_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_12_ce0 = 1'b1;
    end else begin
        arr_1_I_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_12_ce1 = 1'b1;
    end else begin
        arr_1_I_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_13_ce0 = 1'b1;
    end else begin
        arr_1_I_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_13_ce1 = 1'b1;
    end else begin
        arr_1_I_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_14_ce0 = 1'b1;
    end else begin
        arr_1_I_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_14_ce1 = 1'b1;
    end else begin
        arr_1_I_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_15_ce0 = 1'b1;
    end else begin
        arr_1_I_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_15_ce1 = 1'b1;
    end else begin
        arr_1_I_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_1_ce0 = 1'b1;
    end else begin
        arr_1_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_1_ce1 = 1'b1;
    end else begin
        arr_1_I_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_2_ce0 = 1'b1;
    end else begin
        arr_1_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_2_ce1 = 1'b1;
    end else begin
        arr_1_I_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_3_ce0 = 1'b1;
    end else begin
        arr_1_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_3_ce1 = 1'b1;
    end else begin
        arr_1_I_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_4_ce0 = 1'b1;
    end else begin
        arr_1_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_4_ce1 = 1'b1;
    end else begin
        arr_1_I_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_5_ce0 = 1'b1;
    end else begin
        arr_1_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_5_ce1 = 1'b1;
    end else begin
        arr_1_I_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_6_ce0 = 1'b1;
    end else begin
        arr_1_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_6_ce1 = 1'b1;
    end else begin
        arr_1_I_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_7_ce0 = 1'b1;
    end else begin
        arr_1_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_7_ce1 = 1'b1;
    end else begin
        arr_1_I_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_8_ce0 = 1'b1;
    end else begin
        arr_1_I_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_8_ce1 = 1'b1;
    end else begin
        arr_1_I_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_9_ce0 = 1'b1;
    end else begin
        arr_1_I_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_9_ce1 = 1'b1;
    end else begin
        arr_1_I_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_ce0 = 1'b1;
    end else begin
        arr_1_I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_I_ce1 = 1'b1;
    end else begin
        arr_1_I_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_10_ce0 = 1'b1;
    end else begin
        arr_1_Q_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_10_ce1 = 1'b1;
    end else begin
        arr_1_Q_10_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_11_ce0 = 1'b1;
    end else begin
        arr_1_Q_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_11_ce1 = 1'b1;
    end else begin
        arr_1_Q_11_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_12_ce0 = 1'b1;
    end else begin
        arr_1_Q_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_12_ce1 = 1'b1;
    end else begin
        arr_1_Q_12_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_13_ce0 = 1'b1;
    end else begin
        arr_1_Q_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_13_ce1 = 1'b1;
    end else begin
        arr_1_Q_13_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_14_ce0 = 1'b1;
    end else begin
        arr_1_Q_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_14_ce1 = 1'b1;
    end else begin
        arr_1_Q_14_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_15_ce0 = 1'b1;
    end else begin
        arr_1_Q_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_15_ce1 = 1'b1;
    end else begin
        arr_1_Q_15_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_1_ce0 = 1'b1;
    end else begin
        arr_1_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_1_ce1 = 1'b1;
    end else begin
        arr_1_Q_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_2_ce0 = 1'b1;
    end else begin
        arr_1_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_2_ce1 = 1'b1;
    end else begin
        arr_1_Q_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_3_ce0 = 1'b1;
    end else begin
        arr_1_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_3_ce1 = 1'b1;
    end else begin
        arr_1_Q_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_4_ce0 = 1'b1;
    end else begin
        arr_1_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_4_ce1 = 1'b1;
    end else begin
        arr_1_Q_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_5_ce0 = 1'b1;
    end else begin
        arr_1_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_5_ce1 = 1'b1;
    end else begin
        arr_1_Q_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_6_ce0 = 1'b1;
    end else begin
        arr_1_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_6_ce1 = 1'b1;
    end else begin
        arr_1_Q_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_7_ce0 = 1'b1;
    end else begin
        arr_1_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_7_ce1 = 1'b1;
    end else begin
        arr_1_Q_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_8_ce0 = 1'b1;
    end else begin
        arr_1_Q_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_8_ce1 = 1'b1;
    end else begin
        arr_1_Q_8_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_9_ce0 = 1'b1;
    end else begin
        arr_1_Q_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_9_ce1 = 1'b1;
    end else begin
        arr_1_Q_9_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_ce0 = 1'b1;
    end else begin
        arr_1_Q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        arr_1_Q_ce1 = 1'b1;
    end else begin
        arr_1_Q_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_10_ce0 = 1'b1;
    end else begin
        arr_2_I_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_10_we0 = 1'b1;
    end else begin
        arr_2_I_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_11_ce0 = 1'b1;
    end else begin
        arr_2_I_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_11_we0 = 1'b1;
    end else begin
        arr_2_I_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_12_ce0 = 1'b1;
    end else begin
        arr_2_I_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_12_we0 = 1'b1;
    end else begin
        arr_2_I_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_13_ce0 = 1'b1;
    end else begin
        arr_2_I_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_13_we0 = 1'b1;
    end else begin
        arr_2_I_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_14_ce0 = 1'b1;
    end else begin
        arr_2_I_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_14_we0 = 1'b1;
    end else begin
        arr_2_I_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_15_ce0 = 1'b1;
    end else begin
        arr_2_I_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_15_we0 = 1'b1;
    end else begin
        arr_2_I_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_1_ce0 = 1'b1;
    end else begin
        arr_2_I_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_1_we0 = 1'b1;
    end else begin
        arr_2_I_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_2_ce0 = 1'b1;
    end else begin
        arr_2_I_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_2_we0 = 1'b1;
    end else begin
        arr_2_I_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_3_ce0 = 1'b1;
    end else begin
        arr_2_I_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_3_we0 = 1'b1;
    end else begin
        arr_2_I_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_4_ce0 = 1'b1;
    end else begin
        arr_2_I_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_4_we0 = 1'b1;
    end else begin
        arr_2_I_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_5_ce0 = 1'b1;
    end else begin
        arr_2_I_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_5_we0 = 1'b1;
    end else begin
        arr_2_I_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_6_ce0 = 1'b1;
    end else begin
        arr_2_I_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_6_we0 = 1'b1;
    end else begin
        arr_2_I_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_7_ce0 = 1'b1;
    end else begin
        arr_2_I_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_7_we0 = 1'b1;
    end else begin
        arr_2_I_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_8_ce0 = 1'b1;
    end else begin
        arr_2_I_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_8_we0 = 1'b1;
    end else begin
        arr_2_I_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_9_ce0 = 1'b1;
    end else begin
        arr_2_I_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_9_we0 = 1'b1;
    end else begin
        arr_2_I_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_ce0 = 1'b1;
    end else begin
        arr_2_I_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_I_we0 = 1'b1;
    end else begin
        arr_2_I_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_10_ce0 = 1'b1;
    end else begin
        arr_2_Q_10_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_10_we0 = 1'b1;
    end else begin
        arr_2_Q_10_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_11_ce0 = 1'b1;
    end else begin
        arr_2_Q_11_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_11_we0 = 1'b1;
    end else begin
        arr_2_Q_11_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_12_ce0 = 1'b1;
    end else begin
        arr_2_Q_12_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_12_we0 = 1'b1;
    end else begin
        arr_2_Q_12_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_13_ce0 = 1'b1;
    end else begin
        arr_2_Q_13_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_13_we0 = 1'b1;
    end else begin
        arr_2_Q_13_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_14_ce0 = 1'b1;
    end else begin
        arr_2_Q_14_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_14_we0 = 1'b1;
    end else begin
        arr_2_Q_14_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_15_ce0 = 1'b1;
    end else begin
        arr_2_Q_15_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_15_we0 = 1'b1;
    end else begin
        arr_2_Q_15_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_1_ce0 = 1'b1;
    end else begin
        arr_2_Q_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_1_we0 = 1'b1;
    end else begin
        arr_2_Q_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_2_ce0 = 1'b1;
    end else begin
        arr_2_Q_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_2_we0 = 1'b1;
    end else begin
        arr_2_Q_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_3_ce0 = 1'b1;
    end else begin
        arr_2_Q_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_3_we0 = 1'b1;
    end else begin
        arr_2_Q_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_4_ce0 = 1'b1;
    end else begin
        arr_2_Q_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_4_we0 = 1'b1;
    end else begin
        arr_2_Q_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_5_ce0 = 1'b1;
    end else begin
        arr_2_Q_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_5_we0 = 1'b1;
    end else begin
        arr_2_Q_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_6_ce0 = 1'b1;
    end else begin
        arr_2_Q_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_6_we0 = 1'b1;
    end else begin
        arr_2_Q_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_7_ce0 = 1'b1;
    end else begin
        arr_2_Q_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_7_we0 = 1'b1;
    end else begin
        arr_2_Q_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_8_ce0 = 1'b1;
    end else begin
        arr_2_Q_8_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_8_we0 = 1'b1;
    end else begin
        arr_2_Q_8_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_9_ce0 = 1'b1;
    end else begin
        arr_2_Q_9_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln181_reg_2432_pp0_iter1_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_9_we0 = 1'b1;
    end else begin
        arr_2_Q_9_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_ce0 = 1'b1;
    end else begin
        arr_2_Q_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        arr_2_Q_we0 = 1'b1;
    end else begin
        arr_2_Q_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln181_fu_1510_p2 = (ap_sig_allocacmp_i + 10'd32);

assign add_ln183_10_fu_1781_p2 = ($signed(sext_ln183_21_fu_1777_p1) + $signed(sext_ln183_20_fu_1773_p1));

assign add_ln183_11_fu_1795_p2 = ($signed(sext_ln183_23_fu_1791_p1) + $signed(sext_ln183_22_fu_1787_p1));

assign add_ln183_12_fu_1809_p2 = ($signed(sext_ln183_25_fu_1805_p1) + $signed(sext_ln183_24_fu_1801_p1));

assign add_ln183_13_fu_1823_p2 = ($signed(sext_ln183_27_fu_1819_p1) + $signed(sext_ln183_26_fu_1815_p1));

assign add_ln183_14_fu_1837_p2 = ($signed(sext_ln183_29_fu_1833_p1) + $signed(sext_ln183_28_fu_1829_p1));

assign add_ln183_15_fu_1851_p2 = ($signed(sext_ln183_31_fu_1847_p1) + $signed(sext_ln183_30_fu_1843_p1));

assign add_ln183_1_fu_1543_p2 = ($signed(sext_ln183_3_fu_1539_p1) + $signed(sext_ln183_2_fu_1535_p1));

assign add_ln183_2_fu_1557_p2 = ($signed(sext_ln183_5_fu_1553_p1) + $signed(sext_ln183_4_fu_1549_p1));

assign add_ln183_3_fu_1571_p2 = ($signed(sext_ln183_7_fu_1567_p1) + $signed(sext_ln183_6_fu_1563_p1));

assign add_ln183_4_fu_1585_p2 = ($signed(sext_ln183_9_fu_1581_p1) + $signed(sext_ln183_8_fu_1577_p1));

assign add_ln183_5_fu_1599_p2 = ($signed(sext_ln183_11_fu_1595_p1) + $signed(sext_ln183_10_fu_1591_p1));

assign add_ln183_6_fu_1613_p2 = ($signed(sext_ln183_13_fu_1609_p1) + $signed(sext_ln183_12_fu_1605_p1));

assign add_ln183_7_fu_1627_p2 = ($signed(sext_ln183_15_fu_1623_p1) + $signed(sext_ln183_14_fu_1619_p1));

assign add_ln183_8_fu_1753_p2 = ($signed(sext_ln183_17_fu_1749_p1) + $signed(sext_ln183_16_fu_1745_p1));

assign add_ln183_9_fu_1767_p2 = ($signed(sext_ln183_19_fu_1763_p1) + $signed(sext_ln183_18_fu_1759_p1));

assign add_ln183_fu_1529_p2 = ($signed(sext_ln183_1_fu_1525_p1) + $signed(sext_ln183_fu_1521_p1));

assign add_ln184_10_fu_1893_p2 = ($signed(sext_ln184_21_fu_1889_p1) + $signed(sext_ln184_20_fu_1885_p1));

assign add_ln184_11_fu_1907_p2 = ($signed(sext_ln184_23_fu_1903_p1) + $signed(sext_ln184_22_fu_1899_p1));

assign add_ln184_12_fu_1921_p2 = ($signed(sext_ln184_25_fu_1917_p1) + $signed(sext_ln184_24_fu_1913_p1));

assign add_ln184_13_fu_1935_p2 = ($signed(sext_ln184_27_fu_1931_p1) + $signed(sext_ln184_26_fu_1927_p1));

assign add_ln184_14_fu_1949_p2 = ($signed(sext_ln184_29_fu_1945_p1) + $signed(sext_ln184_28_fu_1941_p1));

assign add_ln184_15_fu_1963_p2 = ($signed(sext_ln184_31_fu_1959_p1) + $signed(sext_ln184_30_fu_1955_p1));

assign add_ln184_1_fu_1655_p2 = ($signed(sext_ln184_3_fu_1651_p1) + $signed(sext_ln184_2_fu_1647_p1));

assign add_ln184_2_fu_1669_p2 = ($signed(sext_ln184_5_fu_1665_p1) + $signed(sext_ln184_4_fu_1661_p1));

assign add_ln184_3_fu_1683_p2 = ($signed(sext_ln184_7_fu_1679_p1) + $signed(sext_ln184_6_fu_1675_p1));

assign add_ln184_4_fu_1697_p2 = ($signed(sext_ln184_9_fu_1693_p1) + $signed(sext_ln184_8_fu_1689_p1));

assign add_ln184_5_fu_1711_p2 = ($signed(sext_ln184_11_fu_1707_p1) + $signed(sext_ln184_10_fu_1703_p1));

assign add_ln184_6_fu_1725_p2 = ($signed(sext_ln184_13_fu_1721_p1) + $signed(sext_ln184_12_fu_1717_p1));

assign add_ln184_7_fu_1739_p2 = ($signed(sext_ln184_15_fu_1735_p1) + $signed(sext_ln184_14_fu_1731_p1));

assign add_ln184_8_fu_1865_p2 = ($signed(sext_ln184_17_fu_1861_p1) + $signed(sext_ln184_16_fu_1857_p1));

assign add_ln184_9_fu_1879_p2 = ($signed(sext_ln184_19_fu_1875_p1) + $signed(sext_ln184_18_fu_1871_p1));

assign add_ln184_fu_1641_p2 = ($signed(sext_ln184_1_fu_1637_p1) + $signed(sext_ln184_fu_1633_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign arr_1_I_10_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_10_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_11_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_11_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_12_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_12_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_13_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_13_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_14_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_14_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_15_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_15_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_1_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_1_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_2_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_2_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_3_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_3_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_4_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_4_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_5_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_5_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_6_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_6_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_7_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_7_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_8_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_8_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_9_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_9_address1 = zext_ln181_fu_1410_p1;

assign arr_1_I_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_I_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_10_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_10_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_11_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_11_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_12_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_12_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_13_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_13_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_14_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_14_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_15_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_15_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_1_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_1_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_2_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_2_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_3_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_3_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_4_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_4_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_5_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_5_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_6_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_6_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_7_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_7_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_8_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_8_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_9_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_9_address1 = zext_ln181_fu_1410_p1;

assign arr_1_Q_address0 = zext_ln181_1_fu_1474_p1;

assign arr_1_Q_address1 = zext_ln181_fu_1410_p1;

assign arr_2_I_10_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_10_d0 = {{add_ln183_10_reg_2686}, {6'd0}};

assign arr_2_I_11_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_11_d0 = {{add_ln183_11_reg_2691}, {6'd0}};

assign arr_2_I_12_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_12_d0 = {{add_ln183_12_reg_2696}, {6'd0}};

assign arr_2_I_13_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_13_d0 = {{add_ln183_13_reg_2701}, {6'd0}};

assign arr_2_I_14_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_14_d0 = {{add_ln183_14_reg_2706}, {6'd0}};

assign arr_2_I_15_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_15_d0 = {{add_ln183_15_reg_2711}, {6'd0}};

assign arr_2_I_1_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_1_d0 = {{add_ln183_1_reg_2601}, {6'd0}};

assign arr_2_I_2_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_2_d0 = {{add_ln183_2_reg_2606}, {6'd0}};

assign arr_2_I_3_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_3_d0 = {{add_ln183_3_reg_2611}, {6'd0}};

assign arr_2_I_4_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_4_d0 = {{add_ln183_4_reg_2616}, {6'd0}};

assign arr_2_I_5_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_5_d0 = {{add_ln183_5_reg_2621}, {6'd0}};

assign arr_2_I_6_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_6_d0 = {{add_ln183_6_reg_2626}, {6'd0}};

assign arr_2_I_7_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_7_d0 = {{add_ln183_7_reg_2631}, {6'd0}};

assign arr_2_I_8_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_8_d0 = {{add_ln183_8_reg_2676}, {6'd0}};

assign arr_2_I_9_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_9_d0 = {{add_ln183_9_reg_2681}, {6'd0}};

assign arr_2_I_address0 = zext_ln183_fu_1977_p1;

assign arr_2_I_d0 = {{add_ln183_reg_2596}, {6'd0}};

assign arr_2_Q_10_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_10_d0 = {{add_ln184_10_reg_2726}, {6'd0}};

assign arr_2_Q_11_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_11_d0 = {{add_ln184_11_reg_2731}, {6'd0}};

assign arr_2_Q_12_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_12_d0 = {{add_ln184_12_reg_2736}, {6'd0}};

assign arr_2_Q_13_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_13_d0 = {{add_ln184_13_reg_2741}, {6'd0}};

assign arr_2_Q_14_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_14_d0 = {{add_ln184_14_reg_2746}, {6'd0}};

assign arr_2_Q_15_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_15_d0 = {{add_ln184_15_reg_2751}, {6'd0}};

assign arr_2_Q_1_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_1_d0 = {{add_ln184_1_reg_2641}, {6'd0}};

assign arr_2_Q_2_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_2_d0 = {{add_ln184_2_reg_2646}, {6'd0}};

assign arr_2_Q_3_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_3_d0 = {{add_ln184_3_reg_2651}, {6'd0}};

assign arr_2_Q_4_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_4_d0 = {{add_ln184_4_reg_2656}, {6'd0}};

assign arr_2_Q_5_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_5_d0 = {{add_ln184_5_reg_2661}, {6'd0}};

assign arr_2_Q_6_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_6_d0 = {{add_ln184_6_reg_2666}, {6'd0}};

assign arr_2_Q_7_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_7_d0 = {{add_ln184_7_reg_2671}, {6'd0}};

assign arr_2_Q_8_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_8_d0 = {{add_ln184_8_reg_2716}, {6'd0}};

assign arr_2_Q_9_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_9_d0 = {{add_ln184_9_reg_2721}, {6'd0}};

assign arr_2_Q_address0 = zext_ln183_fu_1977_p1;

assign arr_2_Q_d0 = {{add_ln184_reg_2636}, {6'd0}};

assign icmp_ln181_fu_1462_p2 = ((or_ln181_fu_1456_p2 < 10'd560) ? 1'b1 : 1'b0);

assign lshr_ln_fu_1400_p4 = {{ap_sig_allocacmp_i[9:4]}};

assign or_ln181_1_fu_1468_p2 = (lshr_ln_fu_1400_p4 | 6'd1);

assign or_ln181_fu_1456_p2 = (ap_sig_allocacmp_i | 10'd16);

assign sext_ln183_10_fu_1591_p1 = $signed(arr_1_I_10_q1);

assign sext_ln183_11_fu_1595_p1 = $signed(arr_1_I_11_q1);

assign sext_ln183_12_fu_1605_p1 = $signed(arr_1_I_12_q1);

assign sext_ln183_13_fu_1609_p1 = $signed(arr_1_I_13_q1);

assign sext_ln183_14_fu_1619_p1 = $signed(arr_1_I_14_q1);

assign sext_ln183_15_fu_1623_p1 = $signed(arr_1_I_15_q1);

assign sext_ln183_16_fu_1745_p1 = $signed(arr_1_I_q0);

assign sext_ln183_17_fu_1749_p1 = $signed(arr_1_I_1_q0);

assign sext_ln183_18_fu_1759_p1 = $signed(arr_1_I_2_q0);

assign sext_ln183_19_fu_1763_p1 = $signed(arr_1_I_3_q0);

assign sext_ln183_1_fu_1525_p1 = $signed(arr_1_I_1_q1);

assign sext_ln183_20_fu_1773_p1 = $signed(arr_1_I_4_q0);

assign sext_ln183_21_fu_1777_p1 = $signed(arr_1_I_5_q0);

assign sext_ln183_22_fu_1787_p1 = $signed(arr_1_I_6_q0);

assign sext_ln183_23_fu_1791_p1 = $signed(arr_1_I_7_q0);

assign sext_ln183_24_fu_1801_p1 = $signed(arr_1_I_8_q0);

assign sext_ln183_25_fu_1805_p1 = $signed(arr_1_I_9_q0);

assign sext_ln183_26_fu_1815_p1 = $signed(arr_1_I_10_q0);

assign sext_ln183_27_fu_1819_p1 = $signed(arr_1_I_11_q0);

assign sext_ln183_28_fu_1829_p1 = $signed(arr_1_I_12_q0);

assign sext_ln183_29_fu_1833_p1 = $signed(arr_1_I_13_q0);

assign sext_ln183_2_fu_1535_p1 = $signed(arr_1_I_2_q1);

assign sext_ln183_30_fu_1843_p1 = $signed(arr_1_I_14_q0);

assign sext_ln183_31_fu_1847_p1 = $signed(arr_1_I_15_q0);

assign sext_ln183_3_fu_1539_p1 = $signed(arr_1_I_3_q1);

assign sext_ln183_4_fu_1549_p1 = $signed(arr_1_I_4_q1);

assign sext_ln183_5_fu_1553_p1 = $signed(arr_1_I_5_q1);

assign sext_ln183_6_fu_1563_p1 = $signed(arr_1_I_6_q1);

assign sext_ln183_7_fu_1567_p1 = $signed(arr_1_I_7_q1);

assign sext_ln183_8_fu_1577_p1 = $signed(arr_1_I_8_q1);

assign sext_ln183_9_fu_1581_p1 = $signed(arr_1_I_9_q1);

assign sext_ln183_fu_1521_p1 = $signed(arr_1_I_q1);

assign sext_ln184_10_fu_1703_p1 = $signed(arr_1_Q_10_q1);

assign sext_ln184_11_fu_1707_p1 = $signed(arr_1_Q_11_q1);

assign sext_ln184_12_fu_1717_p1 = $signed(arr_1_Q_12_q1);

assign sext_ln184_13_fu_1721_p1 = $signed(arr_1_Q_13_q1);

assign sext_ln184_14_fu_1731_p1 = $signed(arr_1_Q_14_q1);

assign sext_ln184_15_fu_1735_p1 = $signed(arr_1_Q_15_q1);

assign sext_ln184_16_fu_1857_p1 = $signed(arr_1_Q_q0);

assign sext_ln184_17_fu_1861_p1 = $signed(arr_1_Q_1_q0);

assign sext_ln184_18_fu_1871_p1 = $signed(arr_1_Q_2_q0);

assign sext_ln184_19_fu_1875_p1 = $signed(arr_1_Q_3_q0);

assign sext_ln184_1_fu_1637_p1 = $signed(arr_1_Q_1_q1);

assign sext_ln184_20_fu_1885_p1 = $signed(arr_1_Q_4_q0);

assign sext_ln184_21_fu_1889_p1 = $signed(arr_1_Q_5_q0);

assign sext_ln184_22_fu_1899_p1 = $signed(arr_1_Q_6_q0);

assign sext_ln184_23_fu_1903_p1 = $signed(arr_1_Q_7_q0);

assign sext_ln184_24_fu_1913_p1 = $signed(arr_1_Q_8_q0);

assign sext_ln184_25_fu_1917_p1 = $signed(arr_1_Q_9_q0);

assign sext_ln184_26_fu_1927_p1 = $signed(arr_1_Q_10_q0);

assign sext_ln184_27_fu_1931_p1 = $signed(arr_1_Q_11_q0);

assign sext_ln184_28_fu_1941_p1 = $signed(arr_1_Q_12_q0);

assign sext_ln184_29_fu_1945_p1 = $signed(arr_1_Q_13_q0);

assign sext_ln184_2_fu_1647_p1 = $signed(arr_1_Q_2_q1);

assign sext_ln184_30_fu_1955_p1 = $signed(arr_1_Q_14_q0);

assign sext_ln184_31_fu_1959_p1 = $signed(arr_1_Q_15_q0);

assign sext_ln184_3_fu_1651_p1 = $signed(arr_1_Q_3_q1);

assign sext_ln184_4_fu_1661_p1 = $signed(arr_1_Q_4_q1);

assign sext_ln184_5_fu_1665_p1 = $signed(arr_1_Q_5_q1);

assign sext_ln184_6_fu_1675_p1 = $signed(arr_1_Q_6_q1);

assign sext_ln184_7_fu_1679_p1 = $signed(arr_1_Q_7_q1);

assign sext_ln184_8_fu_1689_p1 = $signed(arr_1_Q_8_q1);

assign sext_ln184_9_fu_1693_p1 = $signed(arr_1_Q_9_q1);

assign sext_ln184_fu_1633_p1 = $signed(arr_1_Q_q1);

assign zext_ln181_1_fu_1474_p1 = or_ln181_1_fu_1468_p2;

assign zext_ln181_fu_1410_p1 = lshr_ln_fu_1400_p4;

assign zext_ln183_fu_1977_p1 = lshr_ln3_reg_2277_pp0_iter1_reg;

endmodule //receiver_receiver_Pipeline_VITIS_LOOP_181_12
