-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity receiver_receiver_Pipeline_VITIS_LOOP_68_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    samples_I_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    samples_I_11_ce0 : OUT STD_LOGIC;
    samples_I_11_we0 : OUT STD_LOGIC;
    samples_I_11_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    samples_I_11_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    samples_I_11_ce1 : OUT STD_LOGIC;
    samples_I_11_q1 : IN STD_LOGIC_VECTOR (17 downto 0);
    samples_Q_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    samples_Q_11_ce0 : OUT STD_LOGIC;
    samples_Q_11_we0 : OUT STD_LOGIC;
    samples_Q_11_d0 : OUT STD_LOGIC_VECTOR (17 downto 0);
    samples_Q_11_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    samples_Q_11_ce1 : OUT STD_LOGIC;
    samples_Q_11_q1 : IN STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of receiver_receiver_Pipeline_VITIS_LOOP_68_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv12_B : STD_LOGIC_VECTOR (11 downto 0) := "000000001011";
    constant ap_const_lv12_F4B : STD_LOGIC_VECTOR (11 downto 0) := "111101001011";
    constant ap_const_lv12_10 : STD_LOGIC_VECTOR (11 downto 0) := "000000010000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln68_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal samples_I_1_ce0 : STD_LOGIC;
    signal samples_I_1_we0 : STD_LOGIC;
    signal samples_I_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_1_ce1 : STD_LOGIC;
    signal samples_I_1_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_2_ce0 : STD_LOGIC;
    signal samples_I_2_we0 : STD_LOGIC;
    signal samples_I_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_2_ce1 : STD_LOGIC;
    signal samples_I_2_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_3_ce0 : STD_LOGIC;
    signal samples_I_3_we0 : STD_LOGIC;
    signal samples_I_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_3_ce1 : STD_LOGIC;
    signal samples_I_3_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_4_ce0 : STD_LOGIC;
    signal samples_I_4_we0 : STD_LOGIC;
    signal samples_I_4_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_4_ce1 : STD_LOGIC;
    signal samples_I_4_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_5_ce0 : STD_LOGIC;
    signal samples_I_5_we0 : STD_LOGIC;
    signal samples_I_5_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_5_ce1 : STD_LOGIC;
    signal samples_I_5_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_6_ce0 : STD_LOGIC;
    signal samples_I_6_we0 : STD_LOGIC;
    signal samples_I_6_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_6_ce1 : STD_LOGIC;
    signal samples_I_6_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_7_ce0 : STD_LOGIC;
    signal samples_I_7_we0 : STD_LOGIC;
    signal samples_I_7_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_7_ce1 : STD_LOGIC;
    signal samples_I_7_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_8_ce0 : STD_LOGIC;
    signal samples_I_8_we0 : STD_LOGIC;
    signal samples_I_8_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_8_ce1 : STD_LOGIC;
    signal samples_I_8_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_9_ce0 : STD_LOGIC;
    signal samples_I_9_we0 : STD_LOGIC;
    signal samples_I_9_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_9_ce1 : STD_LOGIC;
    signal samples_I_9_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_10_ce0 : STD_LOGIC;
    signal samples_I_10_we0 : STD_LOGIC;
    signal samples_I_10_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_10_ce1 : STD_LOGIC;
    signal samples_I_10_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_0_ce0 : STD_LOGIC;
    signal samples_I_0_we0 : STD_LOGIC;
    signal samples_I_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_0_ce1 : STD_LOGIC;
    signal samples_I_0_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_1_ce0 : STD_LOGIC;
    signal samples_Q_1_we0 : STD_LOGIC;
    signal samples_Q_1_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_1_ce1 : STD_LOGIC;
    signal samples_Q_1_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_0_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_0_ce0 : STD_LOGIC;
    signal samples_Q_0_we0 : STD_LOGIC;
    signal samples_Q_0_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_0_ce1 : STD_LOGIC;
    signal samples_Q_0_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_2_ce0 : STD_LOGIC;
    signal samples_Q_2_we0 : STD_LOGIC;
    signal samples_Q_2_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_2_ce1 : STD_LOGIC;
    signal samples_Q_2_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_3_ce0 : STD_LOGIC;
    signal samples_Q_3_we0 : STD_LOGIC;
    signal samples_Q_3_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_3_ce1 : STD_LOGIC;
    signal samples_Q_3_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_4_ce0 : STD_LOGIC;
    signal samples_Q_4_we0 : STD_LOGIC;
    signal samples_Q_4_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_4_ce1 : STD_LOGIC;
    signal samples_Q_4_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_5_ce0 : STD_LOGIC;
    signal samples_Q_5_we0 : STD_LOGIC;
    signal samples_Q_5_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_5_ce1 : STD_LOGIC;
    signal samples_Q_5_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_6_ce0 : STD_LOGIC;
    signal samples_Q_6_we0 : STD_LOGIC;
    signal samples_Q_6_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_6_ce1 : STD_LOGIC;
    signal samples_Q_6_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_7_ce0 : STD_LOGIC;
    signal samples_Q_7_we0 : STD_LOGIC;
    signal samples_Q_7_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_7_ce1 : STD_LOGIC;
    signal samples_Q_7_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_8_ce0 : STD_LOGIC;
    signal samples_Q_8_we0 : STD_LOGIC;
    signal samples_Q_8_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_8_ce1 : STD_LOGIC;
    signal samples_Q_8_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_9_ce0 : STD_LOGIC;
    signal samples_Q_9_we0 : STD_LOGIC;
    signal samples_Q_9_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_9_ce1 : STD_LOGIC;
    signal samples_Q_9_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_10_ce0 : STD_LOGIC;
    signal samples_Q_10_we0 : STD_LOGIC;
    signal samples_Q_10_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_10_ce1 : STD_LOGIC;
    signal samples_Q_10_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_12_ce0 : STD_LOGIC;
    signal samples_I_12_we0 : STD_LOGIC;
    signal samples_I_12_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_12_ce1 : STD_LOGIC;
    signal samples_I_12_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_13_ce0 : STD_LOGIC;
    signal samples_I_13_we0 : STD_LOGIC;
    signal samples_I_13_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_13_ce1 : STD_LOGIC;
    signal samples_I_13_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_14_ce0 : STD_LOGIC;
    signal samples_I_14_we0 : STD_LOGIC;
    signal samples_I_14_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_14_ce1 : STD_LOGIC;
    signal samples_I_14_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_15_ce0 : STD_LOGIC;
    signal samples_I_15_we0 : STD_LOGIC;
    signal samples_I_15_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_15_ce1 : STD_LOGIC;
    signal samples_I_15_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_12_ce0 : STD_LOGIC;
    signal samples_Q_12_we0 : STD_LOGIC;
    signal samples_Q_12_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_12_ce1 : STD_LOGIC;
    signal samples_Q_12_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_13_ce0 : STD_LOGIC;
    signal samples_Q_13_we0 : STD_LOGIC;
    signal samples_Q_13_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_13_ce1 : STD_LOGIC;
    signal samples_Q_13_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_14_ce0 : STD_LOGIC;
    signal samples_Q_14_we0 : STD_LOGIC;
    signal samples_Q_14_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_14_ce1 : STD_LOGIC;
    signal samples_Q_14_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_15_ce0 : STD_LOGIC;
    signal samples_Q_15_we0 : STD_LOGIC;
    signal samples_Q_15_address1 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_15_ce1 : STD_LOGIC;
    signal samples_Q_15_q1 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln68_fu_682_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln68_reg_758 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln68_reg_758_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal samples_I_1_addr_reg_764 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_1_addr_reg_764_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_1_addr_reg_770 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_1_addr_reg_770_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_2_addr_reg_776 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_2_addr_reg_776_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_2_addr_reg_782 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_2_addr_reg_782_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_3_addr_reg_788 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_3_addr_reg_788_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_3_addr_reg_794 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_3_addr_reg_794_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_4_addr_reg_800 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_4_addr_reg_800_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_4_addr_reg_806 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_4_addr_reg_806_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_5_addr_reg_812 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_5_addr_reg_812_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_5_addr_reg_818 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_5_addr_reg_818_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_6_addr_reg_824 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_6_addr_reg_824_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_6_addr_reg_830 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_6_addr_reg_830_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_7_addr_reg_836 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_7_addr_reg_836_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_7_addr_reg_842 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_7_addr_reg_842_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_8_addr_reg_848 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_8_addr_reg_848_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_8_addr_reg_854 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_8_addr_reg_854_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_9_addr_reg_860 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_9_addr_reg_860_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_9_addr_reg_866 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_9_addr_reg_866_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_10_addr_reg_872 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_10_addr_reg_872_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_10_addr_reg_878 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_10_addr_reg_878_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_11_addr_reg_884 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_11_addr_reg_884_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_11_addr_reg_890 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_11_addr_reg_890_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln68_reg_896 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln68_reg_896_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal samples_I_12_addr_reg_900 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_12_addr_reg_900_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_12_addr_reg_906 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_12_addr_reg_906_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_13_addr_reg_912 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_13_addr_reg_912_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_13_addr_reg_918 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_13_addr_reg_918_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_14_addr_reg_924 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_14_addr_reg_924_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_14_addr_reg_930 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_14_addr_reg_930_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_15_addr_reg_936 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_15_addr_reg_936_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_15_addr_reg_942 : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_Q_15_addr_reg_942_pp0_iter1_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal samples_I_1_load_reg_958 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_2_load_reg_963 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_3_load_reg_968 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_4_load_reg_973 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_5_load_reg_978 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_6_load_reg_983 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_7_load_reg_988 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_8_load_reg_993 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_9_load_reg_998 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_10_load_reg_1003 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_11_load_reg_1008 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_11_load_reg_1013 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_1_load_reg_1018 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_2_load_reg_1023 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_3_load_reg_1028 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_4_load_reg_1033 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_5_load_reg_1038 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_6_load_reg_1043 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_7_load_reg_1048 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_8_load_reg_1053 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_9_load_reg_1058 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_10_load_reg_1063 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_12_load_reg_1068 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_13_load_reg_1073 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_14_load_reg_1078 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_15_load_reg_1083 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_I_0_load_reg_1088 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_0_load_reg_1093 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_12_load_reg_1098 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_13_load_reg_1103 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_14_load_reg_1108 : STD_LOGIC_VECTOR (17 downto 0);
    signal samples_Q_15_load_reg_1113 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln70_fu_740_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_100 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln70_fu_728_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (11 downto 0);
    signal lshr_ln_fu_672_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln70_fu_716_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal add_ln70_1_fu_734_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (17 downto 0);
        address1 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component receiver_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    samples_I_1_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_1_addr_reg_764_pp0_iter1_reg,
        ce0 => samples_I_1_ce0,
        we0 => samples_I_1_we0,
        d0 => samples_I_2_load_reg_963,
        address1 => samples_I_1_address1,
        ce1 => samples_I_1_ce1,
        q1 => samples_I_1_q1);

    samples_I_2_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_2_addr_reg_776_pp0_iter1_reg,
        ce0 => samples_I_2_ce0,
        we0 => samples_I_2_we0,
        d0 => samples_I_3_load_reg_968,
        address1 => samples_I_2_address1,
        ce1 => samples_I_2_ce1,
        q1 => samples_I_2_q1);

    samples_I_3_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_3_addr_reg_788_pp0_iter1_reg,
        ce0 => samples_I_3_ce0,
        we0 => samples_I_3_we0,
        d0 => samples_I_4_load_reg_973,
        address1 => samples_I_3_address1,
        ce1 => samples_I_3_ce1,
        q1 => samples_I_3_q1);

    samples_I_4_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_4_addr_reg_800_pp0_iter1_reg,
        ce0 => samples_I_4_ce0,
        we0 => samples_I_4_we0,
        d0 => samples_I_5_load_reg_978,
        address1 => samples_I_4_address1,
        ce1 => samples_I_4_ce1,
        q1 => samples_I_4_q1);

    samples_I_5_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_5_addr_reg_812_pp0_iter1_reg,
        ce0 => samples_I_5_ce0,
        we0 => samples_I_5_we0,
        d0 => samples_I_6_load_reg_983,
        address1 => samples_I_5_address1,
        ce1 => samples_I_5_ce1,
        q1 => samples_I_5_q1);

    samples_I_6_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_6_addr_reg_824_pp0_iter1_reg,
        ce0 => samples_I_6_ce0,
        we0 => samples_I_6_we0,
        d0 => samples_I_7_load_reg_988,
        address1 => samples_I_6_address1,
        ce1 => samples_I_6_ce1,
        q1 => samples_I_6_q1);

    samples_I_7_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_7_addr_reg_836_pp0_iter1_reg,
        ce0 => samples_I_7_ce0,
        we0 => samples_I_7_we0,
        d0 => samples_I_8_load_reg_993,
        address1 => samples_I_7_address1,
        ce1 => samples_I_7_ce1,
        q1 => samples_I_7_q1);

    samples_I_8_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_8_addr_reg_848_pp0_iter1_reg,
        ce0 => samples_I_8_ce0,
        we0 => samples_I_8_we0,
        d0 => samples_I_9_load_reg_998,
        address1 => samples_I_8_address1,
        ce1 => samples_I_8_ce1,
        q1 => samples_I_8_q1);

    samples_I_9_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_9_addr_reg_860_pp0_iter1_reg,
        ce0 => samples_I_9_ce0,
        we0 => samples_I_9_we0,
        d0 => samples_I_10_load_reg_1003,
        address1 => samples_I_9_address1,
        ce1 => samples_I_9_ce1,
        q1 => samples_I_9_q1);

    samples_I_10_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_10_addr_reg_872_pp0_iter1_reg,
        ce0 => samples_I_10_ce0,
        we0 => samples_I_10_we0,
        d0 => samples_I_11_load_reg_1008,
        address1 => samples_I_10_address1,
        ce1 => samples_I_10_ce1,
        q1 => samples_I_10_q1);

    samples_I_0_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_0_address0,
        ce0 => samples_I_0_ce0,
        we0 => samples_I_0_we0,
        d0 => samples_I_1_load_reg_958,
        address1 => samples_I_0_address1,
        ce1 => samples_I_0_ce1,
        q1 => samples_I_0_q1);

    samples_Q_1_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_1_addr_reg_770_pp0_iter1_reg,
        ce0 => samples_Q_1_ce0,
        we0 => samples_Q_1_we0,
        d0 => samples_Q_2_load_reg_1023,
        address1 => samples_Q_1_address1,
        ce1 => samples_Q_1_ce1,
        q1 => samples_Q_1_q1);

    samples_Q_0_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_0_address0,
        ce0 => samples_Q_0_ce0,
        we0 => samples_Q_0_we0,
        d0 => samples_Q_1_load_reg_1018,
        address1 => samples_Q_0_address1,
        ce1 => samples_Q_0_ce1,
        q1 => samples_Q_0_q1);

    samples_Q_2_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_2_addr_reg_782_pp0_iter1_reg,
        ce0 => samples_Q_2_ce0,
        we0 => samples_Q_2_we0,
        d0 => samples_Q_3_load_reg_1028,
        address1 => samples_Q_2_address1,
        ce1 => samples_Q_2_ce1,
        q1 => samples_Q_2_q1);

    samples_Q_3_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_3_addr_reg_794_pp0_iter1_reg,
        ce0 => samples_Q_3_ce0,
        we0 => samples_Q_3_we0,
        d0 => samples_Q_4_load_reg_1033,
        address1 => samples_Q_3_address1,
        ce1 => samples_Q_3_ce1,
        q1 => samples_Q_3_q1);

    samples_Q_4_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_4_addr_reg_806_pp0_iter1_reg,
        ce0 => samples_Q_4_ce0,
        we0 => samples_Q_4_we0,
        d0 => samples_Q_5_load_reg_1038,
        address1 => samples_Q_4_address1,
        ce1 => samples_Q_4_ce1,
        q1 => samples_Q_4_q1);

    samples_Q_5_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_5_addr_reg_818_pp0_iter1_reg,
        ce0 => samples_Q_5_ce0,
        we0 => samples_Q_5_we0,
        d0 => samples_Q_6_load_reg_1043,
        address1 => samples_Q_5_address1,
        ce1 => samples_Q_5_ce1,
        q1 => samples_Q_5_q1);

    samples_Q_6_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_6_addr_reg_830_pp0_iter1_reg,
        ce0 => samples_Q_6_ce0,
        we0 => samples_Q_6_we0,
        d0 => samples_Q_7_load_reg_1048,
        address1 => samples_Q_6_address1,
        ce1 => samples_Q_6_ce1,
        q1 => samples_Q_6_q1);

    samples_Q_7_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_7_addr_reg_842_pp0_iter1_reg,
        ce0 => samples_Q_7_ce0,
        we0 => samples_Q_7_we0,
        d0 => samples_Q_8_load_reg_1053,
        address1 => samples_Q_7_address1,
        ce1 => samples_Q_7_ce1,
        q1 => samples_Q_7_q1);

    samples_Q_8_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_8_addr_reg_854_pp0_iter1_reg,
        ce0 => samples_Q_8_ce0,
        we0 => samples_Q_8_we0,
        d0 => samples_Q_9_load_reg_1058,
        address1 => samples_Q_8_address1,
        ce1 => samples_Q_8_ce1,
        q1 => samples_Q_8_q1);

    samples_Q_9_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_9_addr_reg_866_pp0_iter1_reg,
        ce0 => samples_Q_9_ce0,
        we0 => samples_Q_9_we0,
        d0 => samples_Q_10_load_reg_1063,
        address1 => samples_Q_9_address1,
        ce1 => samples_Q_9_ce1,
        q1 => samples_Q_9_q1);

    samples_Q_10_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_10_addr_reg_878_pp0_iter1_reg,
        ce0 => samples_Q_10_ce0,
        we0 => samples_Q_10_we0,
        d0 => samples_Q_11_load_reg_1013,
        address1 => samples_Q_10_address1,
        ce1 => samples_Q_10_ce1,
        q1 => samples_Q_10_q1);

    samples_I_12_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_12_addr_reg_900_pp0_iter1_reg,
        ce0 => samples_I_12_ce0,
        we0 => samples_I_12_we0,
        d0 => samples_I_13_load_reg_1073,
        address1 => samples_I_12_address1,
        ce1 => samples_I_12_ce1,
        q1 => samples_I_12_q1);

    samples_I_13_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_13_addr_reg_912_pp0_iter1_reg,
        ce0 => samples_I_13_ce0,
        we0 => samples_I_13_we0,
        d0 => samples_I_14_load_reg_1078,
        address1 => samples_I_13_address1,
        ce1 => samples_I_13_ce1,
        q1 => samples_I_13_q1);

    samples_I_14_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_14_addr_reg_924_pp0_iter1_reg,
        ce0 => samples_I_14_ce0,
        we0 => samples_I_14_we0,
        d0 => samples_I_15_load_reg_1083,
        address1 => samples_I_14_address1,
        ce1 => samples_I_14_ce1,
        q1 => samples_I_14_q1);

    samples_I_15_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_I_15_addr_reg_936_pp0_iter1_reg,
        ce0 => samples_I_15_ce0,
        we0 => samples_I_15_we0,
        d0 => samples_I_0_load_reg_1088,
        address1 => samples_I_15_address1,
        ce1 => samples_I_15_ce1,
        q1 => samples_I_15_q1);

    samples_Q_12_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_12_addr_reg_906_pp0_iter1_reg,
        ce0 => samples_Q_12_ce0,
        we0 => samples_Q_12_we0,
        d0 => samples_Q_13_load_reg_1103,
        address1 => samples_Q_12_address1,
        ce1 => samples_Q_12_ce1,
        q1 => samples_Q_12_q1);

    samples_Q_13_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_13_addr_reg_918_pp0_iter1_reg,
        ce0 => samples_Q_13_ce0,
        we0 => samples_Q_13_we0,
        d0 => samples_Q_14_load_reg_1108,
        address1 => samples_Q_13_address1,
        ce1 => samples_Q_13_ce1,
        q1 => samples_Q_13_q1);

    samples_Q_14_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_14_addr_reg_930_pp0_iter1_reg,
        ce0 => samples_Q_14_ce0,
        we0 => samples_Q_14_we0,
        d0 => samples_Q_15_load_reg_1113,
        address1 => samples_Q_14_address1,
        ce1 => samples_Q_14_ce1,
        q1 => samples_Q_14_q1);

    samples_Q_15_U : component receiver_receiver_Pipeline_VITIS_LOOP_68_1_samples_I_1_RAM_AUTO_1R1W
    generic map (
        DataWidth => 18,
        AddressRange => 245,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => samples_Q_15_addr_reg_942_pp0_iter1_reg,
        ce0 => samples_Q_15_ce0,
        we0 => samples_Q_15_we0,
        d0 => samples_Q_0_load_reg_1093,
        address1 => samples_Q_15_address1,
        ce1 => samples_Q_15_ce1,
        q1 => samples_Q_15_q1);

    flow_control_loop_pipe_sequential_init_U : component receiver_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter2_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_const_logic_0;
            elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
            end if; 
        end if;
    end process;

    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln68_fu_722_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_100 <= add_ln70_fu_728_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_100 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln68_reg_896 <= icmp_ln68_fu_722_p2;
                icmp_ln68_reg_896_pp0_iter1_reg <= icmp_ln68_reg_896;
                samples_I_10_addr_reg_872 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_10_addr_reg_872_pp0_iter1_reg <= samples_I_10_addr_reg_872;
                samples_I_11_addr_reg_884 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_11_addr_reg_884_pp0_iter1_reg <= samples_I_11_addr_reg_884;
                samples_I_12_addr_reg_900_pp0_iter1_reg <= samples_I_12_addr_reg_900;
                samples_I_13_addr_reg_912_pp0_iter1_reg <= samples_I_13_addr_reg_912;
                samples_I_14_addr_reg_924_pp0_iter1_reg <= samples_I_14_addr_reg_924;
                samples_I_15_addr_reg_936_pp0_iter1_reg <= samples_I_15_addr_reg_936;
                samples_I_1_addr_reg_764 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_1_addr_reg_764_pp0_iter1_reg <= samples_I_1_addr_reg_764;
                samples_I_2_addr_reg_776 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_2_addr_reg_776_pp0_iter1_reg <= samples_I_2_addr_reg_776;
                samples_I_3_addr_reg_788 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_3_addr_reg_788_pp0_iter1_reg <= samples_I_3_addr_reg_788;
                samples_I_4_addr_reg_800 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_4_addr_reg_800_pp0_iter1_reg <= samples_I_4_addr_reg_800;
                samples_I_5_addr_reg_812 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_5_addr_reg_812_pp0_iter1_reg <= samples_I_5_addr_reg_812;
                samples_I_6_addr_reg_824 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_6_addr_reg_824_pp0_iter1_reg <= samples_I_6_addr_reg_824;
                samples_I_7_addr_reg_836 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_7_addr_reg_836_pp0_iter1_reg <= samples_I_7_addr_reg_836;
                samples_I_8_addr_reg_848 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_8_addr_reg_848_pp0_iter1_reg <= samples_I_8_addr_reg_848;
                samples_I_9_addr_reg_860 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_9_addr_reg_860_pp0_iter1_reg <= samples_I_9_addr_reg_860;
                samples_Q_10_addr_reg_878 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_10_addr_reg_878_pp0_iter1_reg <= samples_Q_10_addr_reg_878;
                samples_Q_11_addr_reg_890 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_11_addr_reg_890_pp0_iter1_reg <= samples_Q_11_addr_reg_890;
                samples_Q_12_addr_reg_906_pp0_iter1_reg <= samples_Q_12_addr_reg_906;
                samples_Q_13_addr_reg_918_pp0_iter1_reg <= samples_Q_13_addr_reg_918;
                samples_Q_14_addr_reg_930_pp0_iter1_reg <= samples_Q_14_addr_reg_930;
                samples_Q_15_addr_reg_942_pp0_iter1_reg <= samples_Q_15_addr_reg_942;
                samples_Q_1_addr_reg_770 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_1_addr_reg_770_pp0_iter1_reg <= samples_Q_1_addr_reg_770;
                samples_Q_2_addr_reg_782 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_2_addr_reg_782_pp0_iter1_reg <= samples_Q_2_addr_reg_782;
                samples_Q_3_addr_reg_794 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_3_addr_reg_794_pp0_iter1_reg <= samples_Q_3_addr_reg_794;
                samples_Q_4_addr_reg_806 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_4_addr_reg_806_pp0_iter1_reg <= samples_Q_4_addr_reg_806;
                samples_Q_5_addr_reg_818 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_5_addr_reg_818_pp0_iter1_reg <= samples_Q_5_addr_reg_818;
                samples_Q_6_addr_reg_830 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_6_addr_reg_830_pp0_iter1_reg <= samples_Q_6_addr_reg_830;
                samples_Q_7_addr_reg_842 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_7_addr_reg_842_pp0_iter1_reg <= samples_Q_7_addr_reg_842;
                samples_Q_8_addr_reg_854 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_8_addr_reg_854_pp0_iter1_reg <= samples_Q_8_addr_reg_854;
                samples_Q_9_addr_reg_866 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_9_addr_reg_866_pp0_iter1_reg <= samples_Q_9_addr_reg_866;
                    zext_ln68_reg_758(7 downto 0) <= zext_ln68_fu_682_p1(7 downto 0);
                    zext_ln68_reg_758_pp0_iter1_reg(7 downto 0) <= zext_ln68_reg_758(7 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln68_reg_896 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                samples_I_0_load_reg_1088 <= samples_I_0_q1;
                samples_I_12_load_reg_1068 <= samples_I_12_q1;
                samples_I_13_load_reg_1073 <= samples_I_13_q1;
                samples_I_14_load_reg_1078 <= samples_I_14_q1;
                samples_I_15_load_reg_1083 <= samples_I_15_q1;
                samples_Q_0_load_reg_1093 <= samples_Q_0_q1;
                samples_Q_12_load_reg_1098 <= samples_Q_12_q1;
                samples_Q_13_load_reg_1103 <= samples_Q_13_q1;
                samples_Q_14_load_reg_1108 <= samples_Q_14_q1;
                samples_Q_15_load_reg_1113 <= samples_Q_15_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                samples_I_10_load_reg_1003 <= samples_I_10_q1;
                samples_I_11_load_reg_1008 <= samples_I_11_q1;
                samples_I_1_load_reg_958 <= samples_I_1_q1;
                samples_I_2_load_reg_963 <= samples_I_2_q1;
                samples_I_3_load_reg_968 <= samples_I_3_q1;
                samples_I_4_load_reg_973 <= samples_I_4_q1;
                samples_I_5_load_reg_978 <= samples_I_5_q1;
                samples_I_6_load_reg_983 <= samples_I_6_q1;
                samples_I_7_load_reg_988 <= samples_I_7_q1;
                samples_I_8_load_reg_993 <= samples_I_8_q1;
                samples_I_9_load_reg_998 <= samples_I_9_q1;
                samples_Q_10_load_reg_1063 <= samples_Q_10_q1;
                samples_Q_11_load_reg_1013 <= samples_Q_11_q1;
                samples_Q_1_load_reg_1018 <= samples_Q_1_q1;
                samples_Q_2_load_reg_1023 <= samples_Q_2_q1;
                samples_Q_3_load_reg_1028 <= samples_Q_3_q1;
                samples_Q_4_load_reg_1033 <= samples_Q_4_q1;
                samples_Q_5_load_reg_1038 <= samples_Q_5_q1;
                samples_Q_6_load_reg_1043 <= samples_Q_6_q1;
                samples_Q_7_load_reg_1048 <= samples_Q_7_q1;
                samples_Q_8_load_reg_1053 <= samples_Q_8_q1;
                samples_Q_9_load_reg_1058 <= samples_Q_9_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln68_fu_722_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                samples_I_12_addr_reg_900 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_13_addr_reg_912 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_14_addr_reg_924 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_I_15_addr_reg_936 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_12_addr_reg_906 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_13_addr_reg_918 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_14_addr_reg_930 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
                samples_Q_15_addr_reg_942 <= zext_ln68_fu_682_p1(8 - 1 downto 0);
            end if;
        end if;
    end process;
    zext_ln68_reg_758(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";
    zext_ln68_reg_758_pp0_iter1_reg(63 downto 8) <= "00000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln70_1_fu_734_p2 <= std_logic_vector(unsigned(lshr_ln_fu_672_p4) + unsigned(ap_const_lv8_1));
    add_ln70_fu_728_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv12_10));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln68_fu_722_p2)
    begin
        if (((icmp_ln68_fu_722_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter2_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter2_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_100, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_100;
        end if; 
    end process;

    icmp_ln68_fu_722_p2 <= "1" when (unsigned(or_ln70_fu_716_p2) < unsigned(ap_const_lv12_F4B)) else "0";
    lshr_ln_fu_672_p4 <= ap_sig_allocacmp_i_2(11 downto 4);
    or_ln70_fu_716_p2 <= (ap_sig_allocacmp_i_2 or ap_const_lv12_B);
    samples_I_0_address0 <= zext_ln68_reg_758_pp0_iter1_reg(8 - 1 downto 0);
    samples_I_0_address1 <= zext_ln70_fu_740_p1(8 - 1 downto 0);

    samples_I_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_0_ce0 <= ap_const_logic_1;
        else 
            samples_I_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_0_ce1 <= ap_const_logic_1;
        else 
            samples_I_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_0_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_0_we0 <= ap_const_logic_1;
        else 
            samples_I_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_10_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_10_ce0 <= ap_const_logic_1;
        else 
            samples_I_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_10_ce1 <= ap_const_logic_1;
        else 
            samples_I_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_10_we0 <= ap_const_logic_1;
        else 
            samples_I_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_11_address0 <= samples_I_11_addr_reg_884_pp0_iter1_reg;
    samples_I_11_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_11_ce0 <= ap_const_logic_1;
        else 
            samples_I_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_11_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_11_ce1 <= ap_const_logic_1;
        else 
            samples_I_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_11_d0 <= samples_I_12_load_reg_1068;

    samples_I_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_11_we0 <= ap_const_logic_1;
        else 
            samples_I_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_12_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_12_ce0 <= ap_const_logic_1;
        else 
            samples_I_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_12_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_12_ce1 <= ap_const_logic_1;
        else 
            samples_I_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_12_we0 <= ap_const_logic_1;
        else 
            samples_I_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_13_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_13_ce0 <= ap_const_logic_1;
        else 
            samples_I_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_13_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_13_ce1 <= ap_const_logic_1;
        else 
            samples_I_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_13_we0 <= ap_const_logic_1;
        else 
            samples_I_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_14_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_14_ce0 <= ap_const_logic_1;
        else 
            samples_I_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_14_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_14_ce1 <= ap_const_logic_1;
        else 
            samples_I_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_14_we0 <= ap_const_logic_1;
        else 
            samples_I_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_15_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_15_ce0 <= ap_const_logic_1;
        else 
            samples_I_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_15_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_15_ce1 <= ap_const_logic_1;
        else 
            samples_I_15_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_15_we0 <= ap_const_logic_1;
        else 
            samples_I_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_1_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_1_ce0 <= ap_const_logic_1;
        else 
            samples_I_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_1_ce1 <= ap_const_logic_1;
        else 
            samples_I_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_1_we0 <= ap_const_logic_1;
        else 
            samples_I_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_2_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_2_ce0 <= ap_const_logic_1;
        else 
            samples_I_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_2_ce1 <= ap_const_logic_1;
        else 
            samples_I_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_2_we0 <= ap_const_logic_1;
        else 
            samples_I_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_3_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_3_ce0 <= ap_const_logic_1;
        else 
            samples_I_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_3_ce1 <= ap_const_logic_1;
        else 
            samples_I_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_3_we0 <= ap_const_logic_1;
        else 
            samples_I_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_4_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_4_ce0 <= ap_const_logic_1;
        else 
            samples_I_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_4_ce1 <= ap_const_logic_1;
        else 
            samples_I_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_4_we0 <= ap_const_logic_1;
        else 
            samples_I_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_5_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_5_ce0 <= ap_const_logic_1;
        else 
            samples_I_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_5_ce1 <= ap_const_logic_1;
        else 
            samples_I_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_5_we0 <= ap_const_logic_1;
        else 
            samples_I_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_6_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_6_ce0 <= ap_const_logic_1;
        else 
            samples_I_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_6_ce1 <= ap_const_logic_1;
        else 
            samples_I_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_6_we0 <= ap_const_logic_1;
        else 
            samples_I_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_7_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_7_ce0 <= ap_const_logic_1;
        else 
            samples_I_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_7_ce1 <= ap_const_logic_1;
        else 
            samples_I_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_7_we0 <= ap_const_logic_1;
        else 
            samples_I_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_8_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_8_ce0 <= ap_const_logic_1;
        else 
            samples_I_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_8_ce1 <= ap_const_logic_1;
        else 
            samples_I_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_8_we0 <= ap_const_logic_1;
        else 
            samples_I_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_I_9_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_I_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_9_ce0 <= ap_const_logic_1;
        else 
            samples_I_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_I_9_ce1 <= ap_const_logic_1;
        else 
            samples_I_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_I_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_I_9_we0 <= ap_const_logic_1;
        else 
            samples_I_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_0_address0 <= zext_ln68_reg_758_pp0_iter1_reg(8 - 1 downto 0);
    samples_Q_0_address1 <= zext_ln70_fu_740_p1(8 - 1 downto 0);

    samples_Q_0_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_0_ce0 <= ap_const_logic_1;
        else 
            samples_Q_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_0_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_0_ce1 <= ap_const_logic_1;
        else 
            samples_Q_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_0_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_0_we0 <= ap_const_logic_1;
        else 
            samples_Q_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_10_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_10_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_10_ce0 <= ap_const_logic_1;
        else 
            samples_Q_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_10_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_10_ce1 <= ap_const_logic_1;
        else 
            samples_Q_10_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_10_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_10_we0 <= ap_const_logic_1;
        else 
            samples_Q_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_11_address0 <= samples_Q_11_addr_reg_890_pp0_iter1_reg;
    samples_Q_11_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_11_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_11_ce0 <= ap_const_logic_1;
        else 
            samples_Q_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_11_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_11_ce1 <= ap_const_logic_1;
        else 
            samples_Q_11_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_11_d0 <= samples_Q_12_load_reg_1098;

    samples_Q_11_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_11_we0 <= ap_const_logic_1;
        else 
            samples_Q_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_12_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_12_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_12_ce0 <= ap_const_logic_1;
        else 
            samples_Q_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_12_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_12_ce1 <= ap_const_logic_1;
        else 
            samples_Q_12_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_12_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_12_we0 <= ap_const_logic_1;
        else 
            samples_Q_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_13_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_13_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_13_ce0 <= ap_const_logic_1;
        else 
            samples_Q_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_13_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_13_ce1 <= ap_const_logic_1;
        else 
            samples_Q_13_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_13_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_13_we0 <= ap_const_logic_1;
        else 
            samples_Q_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_14_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_14_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_14_ce0 <= ap_const_logic_1;
        else 
            samples_Q_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_14_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_14_ce1 <= ap_const_logic_1;
        else 
            samples_Q_14_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_14_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_14_we0 <= ap_const_logic_1;
        else 
            samples_Q_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_15_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_15_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_15_ce0 <= ap_const_logic_1;
        else 
            samples_Q_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_15_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_15_ce1 <= ap_const_logic_1;
        else 
            samples_Q_15_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_15_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001, icmp_ln68_reg_896_pp0_iter1_reg)
    begin
        if (((icmp_ln68_reg_896_pp0_iter1_reg = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_15_we0 <= ap_const_logic_1;
        else 
            samples_Q_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_1_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_1_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_1_ce0 <= ap_const_logic_1;
        else 
            samples_Q_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_1_ce1 <= ap_const_logic_1;
        else 
            samples_Q_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_1_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_1_we0 <= ap_const_logic_1;
        else 
            samples_Q_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_2_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_2_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_2_ce0 <= ap_const_logic_1;
        else 
            samples_Q_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_2_ce1 <= ap_const_logic_1;
        else 
            samples_Q_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_2_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_2_we0 <= ap_const_logic_1;
        else 
            samples_Q_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_3_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_3_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_3_ce0 <= ap_const_logic_1;
        else 
            samples_Q_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_3_ce1 <= ap_const_logic_1;
        else 
            samples_Q_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_3_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_3_we0 <= ap_const_logic_1;
        else 
            samples_Q_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_4_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_4_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_4_ce0 <= ap_const_logic_1;
        else 
            samples_Q_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_4_ce1 <= ap_const_logic_1;
        else 
            samples_Q_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_4_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_4_we0 <= ap_const_logic_1;
        else 
            samples_Q_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_5_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_5_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_5_ce0 <= ap_const_logic_1;
        else 
            samples_Q_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_5_ce1 <= ap_const_logic_1;
        else 
            samples_Q_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_5_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_5_we0 <= ap_const_logic_1;
        else 
            samples_Q_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_6_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_6_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_6_ce0 <= ap_const_logic_1;
        else 
            samples_Q_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_6_ce1 <= ap_const_logic_1;
        else 
            samples_Q_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_6_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_6_we0 <= ap_const_logic_1;
        else 
            samples_Q_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_7_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_7_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_7_ce0 <= ap_const_logic_1;
        else 
            samples_Q_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_7_ce1 <= ap_const_logic_1;
        else 
            samples_Q_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_7_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_7_we0 <= ap_const_logic_1;
        else 
            samples_Q_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_8_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_8_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_8_ce0 <= ap_const_logic_1;
        else 
            samples_Q_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_8_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_8_ce1 <= ap_const_logic_1;
        else 
            samples_Q_8_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_8_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_8_we0 <= ap_const_logic_1;
        else 
            samples_Q_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    samples_Q_9_address1 <= zext_ln68_fu_682_p1(8 - 1 downto 0);

    samples_Q_9_ce0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_9_ce0 <= ap_const_logic_1;
        else 
            samples_Q_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_9_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            samples_Q_9_ce1 <= ap_const_logic_1;
        else 
            samples_Q_9_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    samples_Q_9_we0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            samples_Q_9_we0 <= ap_const_logic_1;
        else 
            samples_Q_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    zext_ln68_fu_682_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(lshr_ln_fu_672_p4),64));
    zext_ln70_fu_740_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_1_fu_734_p2),64));
end behav;
